package crypto

import (
	"bytes"
	"encoding/hex"
	"errors"
	"strings"
	"testing"
)

// Known-answer vectors for transit (transit ADR invariant 1). Construction,
// frozen once and never regenerated by re-running the code under test (the
// derivation and MAC were cross-checked against an independent HKDF/HMAC
// implementation when frozen):
// material = bytes 0x00..0x1f; binding org_1/prj_1/env_1, key tk_1, version 3;
// nonce = 24×0xA5; plaintext "golden transit"; context "ctx"; signed and MACed
// message "golden".
const (
	transitGoldenAEADKeyHex   = "74ecebe391dab624bbb4619b017d978b2f0e54db45d158fb94ae3f8fe9c55bff"
	transitGoldenHMACKeyHex   = "7c106bdc633c34bed6d711df3f38aad3b149f0fc1f37f7aa57e9181ca122260e"
	transitGoldenPublicKeyHex = "9701d2c503ad739844915e9b47b6e17f4c0f95b8e121841e6c74b9e767af2d1d"
	transitGoldenRecordHex    = "01080100000004746b5f310000000300000018a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5f8e6985809daa893d199eb689d4d40b9cd97e8ecceb46670fa3b133fdc51"
	transitGoldenSignatureHex = "63fb4177133385b6134502e38300858773a1cea5addbe4b3f702b7619470c889bccb79355a6b3c4d47dfdb83639e9d8d9c7f93e0781164aa9e33f4927b7e4c09"
	transitGoldenMACHex       = "defddfc738e4e2b34d75fb1b5f674a532d454208022b72ee1dbfc307141e8d19"
)

func goldenMaterial() []byte {
	m := make([]byte, TransitMaterialSize)
	for i := range m {
		m[i] = byte(i)
	}
	return m
}

func goldenBinding(a TransitAlgorithm) TransitBinding {
	return TransitBinding{Algorithm: a, OrgID: "org_1", ProjectID: "prj_1", EnvID: "env_1", KeyID: "tk_1", Version: 3}
}

func mustTransitKey(t *testing.T, a TransitAlgorithm) *TransitKey {
	t.Helper()
	k, err := OpenTransitKey(goldenMaterial(), goldenBinding(a))
	if err != nil {
		t.Fatal(err)
	}
	return k
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad frozen vector %q: %v", s, err)
	}
	return b
}

func TestTransitKnownAnswerDerivation(t *testing.T) {
	aead := mustTransitKey(t, TransitXChaCha20Poly1305)
	if got := hex.EncodeToString(aead.key); got != transitGoldenAEADKeyHex {
		t.Errorf("xchacha derived key = %s, want %s: the derivation changed", got, transitGoldenAEADKeyHex)
	}
	mac := mustTransitKey(t, TransitHMACSHA256)
	if got := hex.EncodeToString(mac.key); got != transitGoldenHMACKeyHex {
		t.Errorf("hmac derived key = %s, want %s: the derivation changed", got, transitGoldenHMACKeyHex)
	}
	if bytes.Equal(aead.key, mac.key) {
		t.Error("two algorithms over one material derived the same key: the algorithm is not bound")
	}
	sig := mustTransitKey(t, TransitEd25519)
	pub, err := sig.PublicKey()
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(pub); got != transitGoldenPublicKeyHex {
		t.Errorf("ed25519 public key = %s, want %s: the derivation changed", got, transitGoldenPublicKeyHex)
	}
}

func TestTransitKnownAnswerRecordOpens(t *testing.T) {
	k := mustTransitKey(t, TransitXChaCha20Poly1305)
	pt, err := k.Decrypt(mustHex(t, transitGoldenRecordHex), []byte("ctx"))
	if err != nil {
		t.Fatalf("golden transit record failed to open, the wire format changed: %v", err)
	}
	if string(pt) != "golden transit" {
		t.Fatalf("plaintext = %q", pt)
	}
	// And sealing with the frozen nonce reproduces it byte for byte.
	k.rnd = bytes.NewReader(bytes.Repeat([]byte{0xA5}, 24))
	record, err := k.Encrypt([]byte("golden transit"), []byte("ctx"))
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(record); got != transitGoldenRecordHex {
		t.Fatalf("record = %s, want %s", got, transitGoldenRecordHex)
	}
}

func TestTransitKnownAnswerSignatureAndMAC(t *testing.T) {
	sig, err := mustTransitKey(t, TransitEd25519).Sign([]byte("golden"))
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(sig); got != transitGoldenSignatureHex {
		t.Errorf("signature = %s, want %s", got, transitGoldenSignatureHex)
	}
	if !VerifyTransitSignature(mustHex(t, transitGoldenPublicKeyHex), []byte("golden"), mustHex(t, transitGoldenSignatureHex)) {
		t.Error("frozen signature does not verify")
	}
	mac, err := mustTransitKey(t, TransitHMACSHA256).MAC([]byte("golden"))
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(mac); got != transitGoldenMACHex {
		t.Errorf("mac = %s, want %s", got, transitGoldenMACHex)
	}
}

func TestTransitKindBytePinned(t *testing.T) {
	if byte(TransitAAD{}.kind()) != 8 {
		t.Fatal("transit kind byte must be 8: kind bytes are persisted format")
	}
}

// Transplant (transit ADR invariant 2): a ciphertext opens under exactly one
// key, version, environment, project, org and context.
func TestTransitTransplantRefused(t *testing.T) {
	base := goldenBinding(TransitXChaCha20Poly1305)
	k, err := OpenTransitKey(goldenMaterial(), base)
	if err != nil {
		t.Fatal(err)
	}
	record, err := k.Encrypt([]byte("secret"), []byte("ctx"))
	if err != nil {
		t.Fatal(err)
	}
	mutate := map[string]func(b *TransitBinding){
		"org":     func(b *TransitBinding) { b.OrgID = "org_2" },
		"project": func(b *TransitBinding) { b.ProjectID = "prj_2" },
		"env":     func(b *TransitBinding) { b.EnvID = "env_2" },
		"key":     func(b *TransitBinding) { b.KeyID = "tk_2" },
		"version": func(b *TransitBinding) { b.Version = 4 },
	}
	for name, m := range mutate {
		b := base
		m(&b)
		other, err := OpenTransitKey(goldenMaterial(), b)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := other.Decrypt(record, []byte("ctx")); !errors.Is(err, ErrDecrypt) {
			t.Errorf("%s transplant opened: %v", name, err)
		}
	}
	if _, err := k.Decrypt(record, []byte("other")); !errors.Is(err, ErrDecrypt) {
		t.Error("wrong context opened")
	}
	if _, err := k.Decrypt(record, nil); !errors.Is(err, ErrDecrypt) {
		t.Error("missing context opened")
	}
	// A non-transit envelope kind under the same key bytes never opens as
	// transit, and a header edit fails authentication.
	tampered := bytes.Clone(record)
	tampered[1] = byte(KindProjectField)
	if _, err := k.Decrypt(tampered, []byte("ctx")); !errors.Is(err, ErrDecrypt) {
		t.Error("kind-byte tamper opened")
	}
}

func TestTransitWrongAlgorithmRefused(t *testing.T) {
	sig := mustTransitKey(t, TransitEd25519)
	if _, err := sig.Encrypt([]byte("x"), nil); err == nil {
		t.Error("signing key encrypted")
	}
	if _, err := sig.MAC([]byte("x")); err == nil {
		t.Error("signing key MACed")
	}
	aead := mustTransitKey(t, TransitXChaCha20Poly1305)
	if _, err := aead.Sign([]byte("x")); err == nil {
		t.Error("encryption key signed")
	}
	if _, err := aead.PublicKey(); err == nil {
		t.Error("encryption key exposed a public key")
	}
	if _, err := mustTransitKey(t, TransitHMACSHA256).Encrypt([]byte("x"), nil); err == nil {
		t.Error("hmac key encrypted")
	}
}

func TestTransitBoundsEnforced(t *testing.T) {
	k := mustTransitKey(t, TransitXChaCha20Poly1305)
	if _, err := k.Encrypt(make([]byte, MaxTransitPlaintextBytes+1), nil); err == nil {
		t.Error("oversized plaintext sealed")
	}
	if _, err := k.Encrypt(nil, make([]byte, MaxTransitContextBytes+1)); err == nil {
		t.Error("oversized context sealed")
	}
	if _, err := mustTransitKey(t, TransitEd25519).Sign(make([]byte, MaxTransitPlaintextBytes+1)); err == nil {
		t.Error("oversized message signed")
	}
	for _, bits := range []int{0, 8, 64, 192, 1024, 257} {
		if _, err := NewTransitDataKey(bits); err == nil {
			t.Errorf("data key of %d bits accepted", bits)
		}
	}
	for _, bits := range []int{128, 256, 512} {
		dk, err := NewTransitDataKey(bits)
		if err != nil || len(dk) != bits/8 {
			t.Errorf("data key of %d bits: len %d err %v", bits, len(dk), err)
		}
	}
}

func TestTransitBindingValidated(t *testing.T) {
	b := goldenBinding(TransitXChaCha20Poly1305)
	b.Version = 0
	if _, err := OpenTransitKey(goldenMaterial(), b); err == nil {
		t.Error("version 0 accepted")
	}
	b = goldenBinding("aes-ecb")
	if _, err := OpenTransitKey(goldenMaterial(), b); err == nil {
		t.Error("unknown algorithm accepted")
	}
	if _, err := OpenTransitKey(make([]byte, 16), goldenBinding(TransitHMACSHA256)); err == nil {
		t.Error("short material accepted")
	}
}

func TestTransitValueRoundTripAndRefusals(t *testing.T) {
	k := mustTransitKey(t, TransitXChaCha20Poly1305)
	record, err := k.Encrypt([]byte("hello"), nil)
	if err != nil {
		t.Fatal(err)
	}
	wire := FormatTransitValue(3, record)
	if !strings.HasPrefix(wire, "hikyo:v3:") {
		t.Fatalf("wire = %s", wire)
	}
	v, got, err := ParseTransitCiphertext(wire, "tk_1")
	if err != nil || v != 3 || !bytes.Equal(got, record) {
		t.Fatalf("round trip: v=%d err=%v", v, err)
	}
	// The textual version must equal the authenticated header version.
	if _, _, err := ParseTransitCiphertext(FormatTransitValue(4, record), "tk_1"); err == nil {
		t.Error("prefix/header version mismatch accepted")
	}
	if _, _, err := ParseTransitCiphertext(wire, "tk_2"); err == nil {
		t.Error("ciphertext of another key accepted")
	}
	for _, bad := range []string{
		"", "hikyo:v", "hikyo:v0:AA", "hikyo:v01:AA", "hikyo:v-1:AA", "hikyo:v+1:AA",
		"hikyo:v4294967296:AA", "hikyo:v1:", "hikyo:v1:AA==", "hikyo:v1:A/+", "vault:v1:AA",
		"hikyo:v1:" + strings.Repeat("A", MaxTransitWireBytes),
	} {
		if _, _, err := ParseTransitValue(bad); err == nil {
			t.Errorf("ParseTransitValue(%.40q) accepted", bad)
		}
	}
}

func TestTransitMACCompare(t *testing.T) {
	k := mustTransitKey(t, TransitHMACSHA256)
	a, _ := k.MAC([]byte("m"))
	b, _ := k.MAC([]byte("m"))
	c, _ := k.MAC([]byte("n"))
	if !EqualTransitMAC(a, b) || EqualTransitMAC(a, c) || EqualTransitMAC(a, a[:5]) {
		t.Fatal("MAC comparison wrong")
	}
	if VerifyTransitSignature(make([]byte, 5), []byte("m"), make([]byte, 64)) {
		t.Fatal("short public key verified")
	}
}

func TestTransitKeyRedacts(t *testing.T) {
	k := mustTransitKey(t, TransitXChaCha20Poly1305)
	if k.String() != Redacted || k.GoString() != Redacted {
		t.Fatal("transit key does not redact")
	}
	k.Destroy()
	if !bytes.Equal(k.key, make([]byte, KeySize)) {
		t.Fatal("destroy did not zero the key")
	}
}

func TestTransitRandomnessFailureIsFatal(t *testing.T) {
	k := mustTransitKey(t, TransitXChaCha20Poly1305)
	k.rnd = bytes.NewReader(make([]byte, 10))
	if _, err := k.Encrypt([]byte("x"), nil); err == nil {
		t.Fatal("seal proceeded on a short randomness read")
	}
	if _, err := readRandom(bytes.NewReader(nil), 32); err == nil {
		t.Fatal("material generated from an empty reader")
	}
}
