FROM gcr.io/distroless/static-debian13:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6

ARG TARGETARCH
COPY --chown=65532:65532 image-root/${TARGETARCH}/hikyo /usr/local/bin/hikyo

USER 65532:65532
EXPOSE 8080 8081
ENTRYPOINT ["/usr/local/bin/hikyo"]
CMD ["server"]
