// Code generated by go run ./internal/authz/gen; DO NOT EDIT.

package authz

import (
	"context"
	"time"

	"github.com/Hikyo-Org/hikyo/internal/domain"
	"github.com/Hikyo-Org/hikyo/internal/jwkssource"
	"github.com/Hikyo-Org/hikyo/internal/store/authn"
)

var _ txForwarded = (*TxAuthorizer)(nil)

func (a *TxAuthorizer) AccountByEmail(ctx context.Context, email string) (Account, error) {
	return a.r.AccountByEmail(ctx, email)
}

// AccountByID resolves an account by id.
func (a *TxAuthorizer) AccountByID(ctx context.Context, id string) (Account, error) {
	return a.r.AccountByID(ctx, id)
}

// AccountByPrincipal resolves the account a session's principal owns — the
// bridge the factor paths need to reach an account's password/TOTP/recovery
// rows from the principal a session carries.
func (a *TxAuthorizer) AccountByPrincipal(ctx context.Context, p domain.PrincipalID) (Account, error) {
	return a.r.AccountByPrincipal(ctx, p)
}

// AccountByUsername resolves a login handle inside this transaction.
func (a *TxAuthorizer) AccountByUsername(ctx context.Context, username string) (Account, error) {
	return a.r.AccountByUsername(ctx, username)
}

// AccountByWebAuthnUserHandle resolves the account a discoverable assertion names.
func (a *TxAuthorizer) AccountByWebAuthnUserHandle(ctx context.Context, handle []byte) (Account, error) {
	return a.r.AccountByWebAuthnUserHandle(ctx, handle)
}

// AccountCount answers the bootstrap path's one question. It has no network
// route: `hikyo admin create` runs on the server's own host.
func (a *TxAuthorizer) AccountCount(ctx context.Context) (int64, error) {
	return a.r.AccountCount(ctx)
}

func (a *TxAuthorizer) AccountProfile(ctx context.Context, accountID string) (AccountProfile, error) {
	return a.r.AccountProfile(ctx, accountID)
}

// ActiveSAMLSPKey resolves the signing key used for AuthnRequests.
func (a *TxAuthorizer) ActiveSAMLSPKey(ctx context.Context) (SAMLSPKey, error) {
	return a.r.ActiveSAMLSPKey(ctx)
}

// AddGrantOrigin attaches one origin to a grant row.
func (a *TxAuthorizer) AddGrantOrigin(ctx context.Context, id, grantID string, p domain.PrincipalID, o Origin, at time.Time) error {
	return a.r.AddGrantOrigin(ctx, id, grantID, p, o, at)
}

// AdvanceGeneration invalidates every session of a principal at once. It runs
// in the same transaction as the change that triggered it.
func (a *TxAuthorizer) AdvanceGeneration(ctx context.Context, p domain.PrincipalID) error {
	return a.r.AdvanceGeneration(ctx, p)
}

// AdvanceRestoreEpoch performs the restore's invalidation.
func (a *TxAuthorizer) AdvanceRestoreEpoch(ctx context.Context, now time.Time) error {
	return a.r.AdvanceRestoreEpoch(ctx, now)
}

// AdvanceTOTPStep consumes a code's step; false means it was not beyond the last.
func (a *TxAuthorizer) AdvanceTOTPStep(ctx context.Context, id string, rowVersion, step int64) (bool, error) {
	return a.r.AdvanceTOTPStep(ctx, id, rowVersion, step)
}

// AdvanceWebAuthnSignCount writes the presented counter under a row_version CAS;
// false means the row moved or was disabled.
func (a *TxAuthorizer) AdvanceWebAuthnSignCount(ctx context.Context, id string, rowVersion, count int64, at time.Time) (bool, error) {
	return a.r.AdvanceWebAuthnSignCount(ctx, id, rowVersion, count, at)
}

func (a *TxAuthorizer) AllowWorkspaceOrigin(ctx context.Context, o authn.WorkspaceOrigin) error {
	return a.r.AllowWorkspaceOrigin(ctx, o)
}

func (a *TxAuthorizer) ApproveCLIReauthHandoff(ctx context.Context, id string, codeVerifier, windows []byte) (bool, error) {
	return a.r.ApproveCLIReauthHandoff(ctx, id, codeVerifier, windows)
}

func (a *TxAuthorizer) ApproveWorkspaceHandoff(ctx context.Context, id string, codeVerifier []byte, p domain.PrincipalID, factors, factorClass string, authenticatedAt time.Time) (bool, error) {
	return a.r.ApproveWorkspaceHandoff(ctx, id, codeVerifier, p, factors, factorClass, authenticatedAt)
}

// AssertActiveInstanceDEKVersion is the writer fence for authentication-surface
// credential writes, which seal under the instance DEK with no tenant proof to
// carry the proof-based fence. It refuses (domain.ErrConflict) a write whose
// sealed instance DEK version a concurrent rotate-dek --instance has retired.
// See the authn.Resolver method for the query semantics.
func (a *TxAuthorizer) AssertActiveInstanceDEKVersion(ctx context.Context, version int64) error {
	return a.r.AssertActiveInstanceDEKVersion(ctx, version)
}

// AuthorityByValue resolves a presented credential-establishment authority.
func (a *TxAuthorizer) AuthorityByValue(ctx context.Context, verifier []byte) (CredentialAuthority, error) {
	return a.r.CredentialAuthorityByVerifier(ctx, verifier)
}

func (a *TxAuthorizer) BindSessionToOAuth2Provider(ctx context.Context, sessionID, providerID string) (bool, error) {
	return a.r.BindSessionToOAuth2Provider(ctx, sessionID, providerID)
}

// BindSessionToSAMLProvider records SAML provider provenance in the same
// transaction that mints the session.
func (a *TxAuthorizer) BindSessionToSAMLProvider(ctx context.Context, sessionID, providerID string) (bool, error) {
	return a.r.BindSessionToSAMLProvider(ctx, sessionID, providerID)
}

// BindingsForIssuer is the delete guard's census: removing the issuer of a
// live binding is an authorization change wearing a configuration change's
// clothes.
func (a *TxAuthorizer) BindingsForIssuer(ctx context.Context, id string) (int64, error) {
	return a.r.BindingsForIssuer(ctx, id)
}

func (a *TxAuthorizer) CLIReauthHandoffByCode(ctx context.Context, verifier []byte) (CLIReauthHandoff, error) {
	return a.r.CLIReauthHandoffByCode(ctx, verifier)
}

func (a *TxAuthorizer) CLIReauthHandoffByState(ctx context.Context, verifier []byte) (CLIReauthHandoff, error) {
	return a.r.CLIReauthHandoffByState(ctx, verifier)
}

func (a *TxAuthorizer) ClaimFederatedAuthority(ctx context.Context, id, kind string, at time.Time) (bool, error) {
	return a.r.ClaimFederatedAuthority(ctx, id, kind, at)
}

// ClaimSAMLReplay atomically records an assertion ID. False means replay.
func (a *TxAuthorizer) ClaimSAMLReplay(ctx context.Context, replay NewSAMLReplay) (bool, error) {
	return a.r.ClaimSAMLReplay(ctx, replay)
}

func (a *TxAuthorizer) ClampCredentialExpiry(ctx context.Context, ceiling time.Time) (int64, error) {
	return a.r.ClampCredentialExpiry(ctx, ceiling)
}

func (a *TxAuthorizer) ClampIndefiniteCredentials(ctx context.Context, ceiling time.Time) (int64, error) {
	return a.r.ClampIndefiniteCredentials(ctx, ceiling)
}

// ClearPendingTOTP removes only in-progress enrolments.
func (a *TxAuthorizer) ClearPendingTOTP(ctx context.Context, accountID string) error {
	return a.r.DeletePendingTOTPForAccount(ctx, accountID)
}

// ConfirmTOTP promotes and consumes a step in one CAS; false means the row
// moved or the step was not beyond the last.
func (a *TxAuthorizer) ConfirmTOTP(ctx context.Context, id string, rowVersion, step int64, at time.Time) (bool, error) {
	return a.r.ConfirmTOTP(ctx, id, rowVersion, step, at)
}

// ConfirmedTOTP resolves an account's confirmed TOTP factor.
func (a *TxAuthorizer) ConfirmedTOTP(ctx context.Context, accountID string) (TOTPCredential, error) {
	return a.r.ConfirmedTOTP(ctx, accountID)
}

// ConsumeAuthority claims an authority atomically; false means it was already
// consumed and the caller must fail closed.
func (a *TxAuthorizer) ConsumeAuthority(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeCredentialAuthority(ctx, id, at)
}

func (a *TxAuthorizer) ConsumeCLIReauthHandoff(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeCLIReauthHandoff(ctx, id, at)
}

// ConsumeLoginChallenge claims a login challenge atomically; false means it was
// already consumed and the caller must fail closed.
func (a *TxAuthorizer) ConsumeLoginChallenge(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeLoginChallenge(ctx, id, at)
}

func (a *TxAuthorizer) ConsumeOAuth2Transaction(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeOAuth2Transaction(ctx, id, at)
}

// ConsumeOIDCTransaction claims a transaction atomically; false means it moved.
func (a *TxAuthorizer) ConsumeOIDCTransaction(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeOIDCTransaction(ctx, id, at)
}

// ConsumeOutstandingAuthorities marks every unconsumed authority of an account
// consumed, in the same transaction as a fresh mint or consumption.
func (a *TxAuthorizer) ConsumeOutstandingAuthorities(ctx context.Context, accountID string, at time.Time) error {
	return a.r.ConsumeOutstandingAuthorities(ctx, accountID, at)
}

func (a *TxAuthorizer) ConsumeRegistrationSignup(ctx context.Context, id string, verifier []byte) (bool, error) {
	return a.r.ConsumeRegistrationSignup(ctx, id, verifier)
}

// ConsumeSAMLTransaction spends a transaction on first presentation, success
// or failure.
func (a *TxAuthorizer) ConsumeSAMLTransaction(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeSAMLTransaction(ctx, id, at)
}

// ConsumeSingleDecisionWindow claims a single-decision window exactly once;
// false means it was already spent (B11 double-spend).
func (a *TxAuthorizer) ConsumeSingleDecisionWindow(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeSingleDecisionWindow(ctx, id, at)
}

// ConsumeWebAuthnCeremony claims a ceremony atomically and stamps the credential
// that answered it; false means it was already consumed.
func (a *TxAuthorizer) ConsumeWebAuthnCeremony(ctx context.Context, id, credentialID string, at time.Time) (bool, error) {
	return a.r.ConsumeWebAuthnCeremony(ctx, id, credentialID, at)
}

func (a *TxAuthorizer) ConsumeWorkspaceHandoff(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ConsumeWorkspaceHandoff(ctx, id, at)
}

func (a *TxAuthorizer) CorrectPrivacyAccount(ctx context.Context, account, username, displayName string) error {
	return a.r.CorrectPrivacyAccount(ctx, account, username, displayName)
}

// CountExternalIdentitiesForIssuer counts the links under one (kind, issuer).
func (a *TxAuthorizer) CountExternalIdentitiesForIssuer(ctx context.Context, kind, issuer string) (int64, error) {
	return a.r.CountExternalIdentitiesForIssuer(ctx, kind, issuer)
}

// CountGrantsInOrg reports how many grant rows an organization holds — the
// read behind the per-org grant sanity cap.
func (a *TxAuthorizer) CountGrantsInOrg(ctx context.Context, org string) (int64, error) {
	return a.r.CountGrantsInOrg(ctx, org)
}

// CountRegistrationPolicyOrgs counts the live orgs a policy minted.
func (a *TxAuthorizer) CountRegistrationPolicyOrgs(ctx context.Context, policyID string) (int64, error) {
	return a.r.CountRegistrationPolicyOrgs(ctx, policyID)
}

// CreateAccessGrant writes one environment-scoped temporary grant row.
func (a *TxAuthorizer) CreateAccessGrant(ctx context.Context, id string, p domain.PrincipalID, g domain.Grant,
	requestID string, at, expiresAt time.Time) error {
	return a.r.CreateAccessGrant(ctx, id, p, g, requestID, at, expiresAt)
}

func (a *TxAuthorizer) CreateAccount(ctx context.Context, acc Account) error {
	return a.r.CreateAccount(ctx, acc)
}

func (a *TxAuthorizer) CreateCLIReauthHandoff(ctx context.Context, h NewCLIReauthHandoff) error {
	return a.r.CreateCLIReauthHandoff(ctx, h)
}

// CreateExternalIdentity writes a link.
func (a *TxAuthorizer) CreateExternalIdentity(ctx context.Context, n NewExternalIdentity) error {
	return a.r.CreateExternalIdentity(ctx, n)
}

func (a *TxAuthorizer) CreateFederationIssuer(ctx context.Context, iss NewFederationIssuer) error {
	return a.r.CreateFederationIssuer(ctx, iss)
}

// CreateGrant writes one grant row. The bootstrap path uses it to expand the
// `admin` template into separate, visible, individually revocable rows rather
// than an implicit bundle. The general grant surface is #55's.
func (a *TxAuthorizer) CreateGrant(ctx context.Context, id string, p domain.PrincipalID, g domain.Grant, at time.Time) error {
	return a.r.CreateGrant(ctx, id, p, g, at)
}

// CreateLoginChallenge writes a single-use, expiring login challenge (#760).
func (a *TxAuthorizer) CreateLoginChallenge(ctx context.Context, c NewLoginChallenge) error {
	return a.r.CreateLoginChallenge(ctx, c)
}

func (a *TxAuthorizer) CreateMachineCredential(ctx context.Context, c NewCredential) error {
	return a.r.CreateMachineCredential(ctx, c)
}

func (a *TxAuthorizer) CreateMachinePrincipal(ctx context.Context, id domain.PrincipalID, class domain.PrincipalClass, at time.Time) error {
	return a.r.CreateMachinePrincipal(ctx, id, class, at)
}

// OAuth2's profile-pinned provider and single-use transaction resolution.
func (a *TxAuthorizer) CreateOAuth2Provider(ctx context.Context, n NewOAuth2Provider) error {
	return a.r.CreateOAuth2Provider(ctx, n)
}

func (a *TxAuthorizer) CreateOAuth2Transaction(ctx context.Context, t NewOAuth2Transaction) error {
	return a.r.CreateOAuth2Transaction(ctx, t)
}

// CreateOIDCTransaction writes a single-use transaction row.
func (a *TxAuthorizer) CreateOIDCTransaction(ctx context.Context, t NewOIDCTransaction) error {
	return a.r.CreateOIDCTransaction(ctx, t)
}

// CreateProvider inserts a provider row (authorized at the chokepoint first).
func (a *TxAuthorizer) CreateProvider(ctx context.Context, n NewProvider) error {
	return a.r.CreateProvider(ctx, n)
}

// The two ends of the provisioning connection's life: created with its binding,
// retired by §6's state machine atomically with the structural grant it held.
// Neither takes a class: the first hardcodes it and the second requires it.
func (a *TxAuthorizer) CreateProvisioningPrincipal(ctx context.Context, id domain.PrincipalID, at time.Time) error {
	return a.r.CreateProvisioningPrincipal(ctx, id, at)
}

// CreateRegistrationPolicy inserts a policy; a second one per scope is ErrConflict.
func (a *TxAuthorizer) CreateRegistrationPolicy(ctx context.Context, p RegistrationPolicy) error {
	return a.r.CreateRegistrationPolicy(ctx, p)
}

// CreateRegistrationSignup inserts a pending local sign-up row.
func (a *TxAuthorizer) CreateRegistrationSignup(ctx context.Context, n NewRegistrationSignup) error {
	return a.r.CreateRegistrationSignup(ctx, n)
}

func (a *TxAuthorizer) CreateRule(ctx context.Context, rule domain.Rule, createdBy domain.PrincipalID, at time.Time, newItemID func() (string, error)) error {
	return a.r.CreateRule(ctx, rule, createdBy, at, newItemID)
}

// CreateSAMLProvider inserts a provider after instance-config authorization.
func (a *TxAuthorizer) CreateSAMLProvider(ctx context.Context, provider NewSAMLProvider) error {
	return a.r.CreateSAMLProvider(ctx, provider)
}

// CreateSAMLSPKey stores a freshly minted encrypted private key.
func (a *TxAuthorizer) CreateSAMLSPKey(ctx context.Context, key NewSAMLSPKey) error {
	return a.r.CreateSAMLSPKey(ctx, key)
}

// CreateSAMLTransaction writes a single-use AuthnRequest transaction.
func (a *TxAuthorizer) CreateSAMLTransaction(ctx context.Context, transaction NewSAMLTransaction) error {
	return a.r.CreateSAMLTransaction(ctx, transaction)
}

func (a *TxAuthorizer) CreateServiceAccountAggregate(ctx context.Context, sa NewServiceAccount) (ServiceAccountCreation, error) {
	return a.r.CreateServiceAccountAggregate(ctx, sa)
}

// CreateTOTP inserts a pending TOTP enrolment.
func (a *TxAuthorizer) CreateTOTP(ctx context.Context, c NewTOTPCredential) error {
	return a.r.CreateTOTP(ctx, c)
}

// CreateWebAuthnCeremony writes a single-use, expiring challenge row.
func (a *TxAuthorizer) CreateWebAuthnCeremony(ctx context.Context, c NewWebAuthnCeremony) error {
	return a.r.CreateWebAuthnCeremony(ctx, c)
}

// CreateWebAuthnCredential inserts a freshly enrolled passkey.
func (a *TxAuthorizer) CreateWebAuthnCredential(ctx context.Context, c NewWebAuthnCredential) error {
	return a.r.CreateWebAuthnCredential(ctx, c)
}

func (a *TxAuthorizer) CreateWorkspaceHandoff(ctx context.Context, h authn.NewWorkspaceHandoff) error {
	return a.r.CreateWorkspaceHandoff(ctx, h)
}

func (a *TxAuthorizer) CredentialAuthorityByID(ctx context.Context, id string) (CredentialAuthority, error) {
	return a.r.CredentialAuthorityByID(ctx, id)
}

// CredentialEpoch reads the instance epoch.
func (a *TxAuthorizer) CredentialEpoch(ctx context.Context) (int64, error) {
	return a.r.CredentialEpoch(ctx)
}

func (a *TxAuthorizer) CredentialPolicy(ctx context.Context) (CredentialPolicy, error) {
	return a.r.CredentialPolicy(ctx)
}

func (a *TxAuthorizer) CredentialsBeyondCeiling(ctx context.Context, ceiling time.Time) ([]AffectedCredential, error) {
	return a.r.CredentialsBeyondCeiling(ctx, ceiling)
}

// DeleteAccessGrantsForRequest releases every temporary row one request wrote.
func (a *TxAuthorizer) DeleteAccessGrantsForRequest(ctx context.Context, p domain.PrincipalID, requestID string) (int64, error) {
	return a.r.DeleteAccessGrantsForRequest(ctx, p, requestID)
}

// DeleteExpiredSAMLReplay removes replay rows after their signed validity plus
// skew has elapsed.
func (a *TxAuthorizer) DeleteExpiredSAMLReplay(ctx context.Context, at time.Time) (int64, error) {
	return a.r.DeleteExpiredSAMLReplay(ctx, at)
}

func (a *TxAuthorizer) DeleteFederationIssuer(ctx context.Context, id string) (bool, error) {
	return a.r.DeleteFederationIssuer(ctx, id)
}

// DeleteGrantRow removes a grant row whose last origin was released.
func (a *TxAuthorizer) DeleteGrantRow(ctx context.Context, grantID string, p domain.PrincipalID) (bool, error) {
	return a.r.DeleteGrantRow(ctx, grantID, p)
}

func (a *TxAuthorizer) DeleteOAuth2Provider(ctx context.Context, id string) error {
	return a.r.DeleteOAuth2Provider(ctx, id)
}

// DeleteProvider removes a provider.
func (a *TxAuthorizer) DeleteProvider(ctx context.Context, id string) error {
	return a.r.DeleteProvider(ctx, id)
}

// DeleteRegistrationPolicy removes a policy at an expected row version.
func (a *TxAuthorizer) DeleteRegistrationPolicy(ctx context.Context, id string, expected int64) (bool, error) {
	return a.r.DeleteRegistrationPolicy(ctx, id, expected)
}

// DeleteRegistrationSignup deletes one pending local sign-up row.
func (a *TxAuthorizer) DeleteRegistrationSignup(ctx context.Context, id string) (bool, error) {
	return a.r.DeleteRegistrationSignup(ctx, id)
}

// DeleteRetiringSAMLSPKey erases a retiring key.
func (a *TxAuthorizer) DeleteRetiringSAMLSPKey(ctx context.Context, id string) (bool, error) {
	return a.r.DeleteRetiringSAMLSPKey(ctx, id)
}

func (a *TxAuthorizer) DeleteRule(ctx context.Context, id string, p domain.PrincipalID) (bool, error) {
	return a.r.DeleteRule(ctx, id, p)
}

func (a *TxAuthorizer) DeleteRuleItem(ctx context.Context, ruleID, itemID string, p domain.PrincipalID) error {
	return a.r.DeleteRuleItem(ctx, ruleID, itemID, p)
}

// DeleteSAMLProvider removes a locked provider row.
func (a *TxAuthorizer) DeleteSAMLProvider(ctx context.Context, id string) error {
	return a.r.DeleteSAMLProvider(ctx, id)
}

func (a *TxAuthorizer) DeleteServiceAccountAggregate(ctx context.Context, in DeleteServiceAccountAggregateInput) (ServiceAccountDeletion, error) {
	return a.r.DeleteServiceAccountAggregate(ctx, in)
}

func (a *TxAuthorizer) DeleteSessionsForOAuth2Provider(ctx context.Context, providerID string) (int64, error) {
	return a.r.DeleteSessionsForOAuth2Provider(ctx, providerID)
}

// DeleteWebAuthnCredential removes a credential (de-enrolment) under an
// account_id predicate. False means zero rows matched — refused fail-closed.
func (a *TxAuthorizer) DeleteWebAuthnCredential(ctx context.Context, id, accountID string) (bool, error) {
	return a.r.DeleteWebAuthnCredential(ctx, id, accountID)
}

// DisableWebAuthnCredential sets disabled_at under a CAS (the clone response);
// false means the row moved or was already disabled.
func (a *TxAuthorizer) DisableWebAuthnCredential(ctx context.Context, id string, rowVersion int64, at time.Time) (bool, error) {
	return a.r.DisableWebAuthnCredential(ctx, id, rowVersion, at)
}

// EnabledProviderByIssuer resolves the currently enabled provider for an issuer.
func (a *TxAuthorizer) EnabledProviderByIssuer(ctx context.Context, kind, issuer string) (OIDCProvider, error) {
	return a.r.EnabledProviderByIssuer(ctx, kind, issuer)
}

// EnabledProviderBySlug resolves an enabled provider by slug, for start.
func (a *TxAuthorizer) EnabledProviderBySlug(ctx context.Context, slug string) (OIDCProvider, error) {
	return a.r.EnabledProviderBySlug(ctx, slug)
}

// EnvironmentChainByID resolves an environment's chain from its id, so
// LowerEffectiveWindow can build the grant-coverage predicate from an env id.
func (a *TxAuthorizer) EnvironmentChainByID(ctx context.Context, envID string) (EnvironmentChain, error) {
	return a.r.EnvironmentChainByID(ctx, envID)
}

// EnvironmentReauthSettings reads an environment's protection state and its
// own reauthentication window, if it has one.
func (a *TxAuthorizer) EnvironmentReauthSettings(ctx context.Context, envID string) (EnvSetting, error) {
	return a.r.EnvironmentReauthSettings(ctx, envID)
}

// EnvironmentsInProject is the universe the mint and widen reachability
// formulas range over.
func (a *TxAuthorizer) EnvironmentsInProject(ctx context.Context, scope domain.Scope) ([]domain.EnvID, error) {
	return a.r.EnvironmentsInProject(ctx, scope)
}

func (a *TxAuthorizer) ErasePrivacyAccount(ctx context.Context, account, p, username string) error {
	return a.r.ErasePrivacyAccount(ctx, account, p, username)
}

func (a *TxAuthorizer) ExpiredRegistrationSignups(ctx context.Context, at time.Time) ([]ExpiredRegistrationSignup, error) {
	return a.r.ExpiredRegistrationSignups(ctx, at)
}

// ExternalIdentitiesForAccount lists an account's linked identities.
func (a *TxAuthorizer) ExternalIdentitiesForAccount(ctx context.Context, accountID string) ([]ExternalIdentity, error) {
	return a.r.ExternalIdentitiesForAccount(ctx, accountID)
}

// ExternalIdentityByID resolves a link by id.
func (a *TxAuthorizer) ExternalIdentityByID(ctx context.Context, id string) (ExternalIdentity, error) {
	return a.r.ExternalIdentityByID(ctx, id)
}

// ExternalIdentityByKey resolves a byte-exact (kind, issuer, subject).
func (a *TxAuthorizer) ExternalIdentityByKey(ctx context.Context, kind, issuer, subject string) (ExternalIdentity, error) {
	return a.r.ExternalIdentityByKey(ctx, kind, issuer, subject)
}

func (a *TxAuthorizer) FederationIssuerByID(ctx context.Context, id string) (FederationIssuer, error) {
	return a.r.FederationIssuerByID(ctx, id)
}

// FederationIssuerByIssuer resolves a configuration by its BYTE-EXACT `iss`.
func (a *TxAuthorizer) FederationIssuerByIssuer(ctx context.Context, issuer string) (FederationIssuer, error) {
	return a.r.FederationIssuerByIssuer(ctx, issuer)
}

func (a *TxAuthorizer) FederationIssuers(ctx context.Context) ([]FederationIssuer, error) {
	return a.r.FederationIssuers(ctx)
}

// GetRule reads one stored rule, ungated; valid is false for a stored rule
// that no longer validates (the caller should delete it).
func (a *TxAuthorizer) GetRule(ctx context.Context, id string) (StoredRule, bool, error) {
	return a.r.GetRule(ctx, id)
}

// GrantLinesAtInstance lists the instance-scope membership surface.
func (a *TxAuthorizer) GrantLinesAtInstance(ctx context.Context) ([]GrantLine, error) {
	return a.r.GrantLinesAtInstance(ctx)
}

// GrantLinesInOrg lists the membership surface for one org.
func (a *TxAuthorizer) GrantLinesInOrg(ctx context.Context, org string) ([]GrantLine, error) {
	return a.r.GrantLinesInOrg(ctx, org)
}

// GrantLinesInProject lists the membership surface for one project.
func (a *TxAuthorizer) GrantLinesInProject(ctx context.Context, org, project string) ([]GrantLine, error) {
	return a.r.GrantLinesInProject(ctx, org, project)
}

// GrantOriginCount reports how many origins still hold a grant row.
func (a *TxAuthorizer) GrantOriginCount(ctx context.Context, grantID string) (int64, error) {
	return a.r.GrantOriginCount(ctx, grantID)
}

// GrantOriginsFor lists the origins holding one grant row.
func (a *TxAuthorizer) GrantOriginsFor(ctx context.Context, grantID string) ([]Origin, error) {
	return a.r.GrantOriginsFor(ctx, grantID)
}

// GrantOriginsForPrincipal lists every origin holding every grant row of one
// principal, read at one instant. The SCIM release algorithm (#73 §2.4) decides
// per origin and then counts what remains per row; seeing the two tables at
// different instants would let a row be judged against origins that had already
// moved.
func (a *TxAuthorizer) GrantOriginsForPrincipal(ctx context.Context, p domain.PrincipalID) ([]GrantOriginRow, error) {
	return a.r.GrantOriginsForPrincipal(ctx, p)
}

// GrantRowsForPrincipal lists a principal's grants with their row ids — the
// dedup read every create performs under the principal-row lock.
func (a *TxAuthorizer) GrantRowsForPrincipal(ctx context.Context, p domain.PrincipalID) ([]GrantRow, error) {
	return a.r.GrantRowsForPrincipal(ctx, p)
}

// GrantsForResetTarget reads the credential-reset target's full grant set for
// the org-bounded test, under the row lock the reset holds.
func (a *TxAuthorizer) GrantsForResetTarget(ctx context.Context, p domain.PrincipalID) ([]domain.Grant, error) {
	return a.r.GrantsForResetTarget(ctx, p)
}

// GrantsOf returns a principal's full grant set — the pre-state input to the
// reachability diff.
func (a *TxAuthorizer) GrantsOf(ctx context.Context, p domain.PrincipalID) ([]domain.Grant, error) {
	return a.r.Grants(ctx, p)
}

func (a *TxAuthorizer) GuardOAuth2ProviderForMint(ctx context.Context, id string, rowVersion int64, issuer string) (bool, error) {
	return a.r.GuardOAuth2ProviderForMint(ctx, id, rowVersion, issuer)
}

// GuardProviderForMint locks the pinned provider row inside a Phase-C mint tx
// and reports whether it still matches the Phase-A snapshot; false means the
// provider moved and the mint must refuse (A4 TOCTOU, sweep wins).
func (a *TxAuthorizer) GuardProviderForMint(ctx context.Context, id string, rowVersion int64, issuer string) (bool, error) {
	return a.r.GuardProviderForMint(ctx, id, rowVersion, issuer)
}

// GuardSAMLProviderForMint proves the provider still matches the Phase-A
// snapshot immediately before a session or reauth window is written.
func (a *TxAuthorizer) GuardSAMLProviderForMint(ctx context.Context, id string, rowVersion int64, entityID string) (bool, error) {
	return a.r.GuardSAMLProviderForMint(ctx, id, rowVersion, entityID)
}

func (a *TxAuthorizer) HoldRestoredPKIIssuers(ctx context.Context) error {
	return a.r.HoldRestoredPKIIssuers(ctx)
}

// IncompatiblePasswordKDFCount is for startup/configuration admission, not a
// public authentication route. It exposes only aggregate parameter metadata.
func (a *TxAuthorizer) IncompatiblePasswordKDFCount(ctx context.Context, kdf KDFParams) (int64, error) {
	return a.r.IncompatiblePasswordKDFCount(ctx, kdf)
}

func (a *TxAuthorizer) IndefiniteCredentials(ctx context.Context) ([]AffectedCredential, error) {
	return a.r.IndefiniteCredentials(ctx)
}

func (a *TxAuthorizer) InstanceConnectionByID(ctx context.Context, id string) (authn.InstanceConnection, error) {
	return a.r.InstanceConnectionByID(ctx, id)
}

func (a *TxAuthorizer) InstanceConnections(ctx context.Context) ([]authn.InstanceConnection, error) {
	return a.r.InstanceConnections(ctx)
}

// InstanceIdentity is this instance's own opaque id — the value a directory
// listing carries and the one self-connection refusal compares against.
func (a *TxAuthorizer) InstanceIdentity(ctx context.Context) (string, error) {
	return a.r.InstanceIdentity(ctx)
}

// InvalidateReauthWindowsForEnvironment deletes every open window on one
// environment (the effective-window transition, B6) and returns the count.
func (a *TxAuthorizer) InvalidateReauthWindowsForEnvironment(ctx context.Context, environmentID string) (int64, error) {
	return a.r.DeleteReauthWindowsForEnvironment(ctx, environmentID)
}

func (a *TxAuthorizer) InvalidateRestoredAdapterCredentials(ctx context.Context) error {
	return a.r.InvalidateRestoredAdapterCredentials(ctx)
}

func (a *TxAuthorizer) InvalidateRestoredDynamicProviderCredentials(ctx context.Context) error {
	return a.r.InvalidateRestoredDynamicProviderCredentials(ctx)
}

func (a *TxAuthorizer) InvalidateRestoredExternalCredentials(ctx context.Context, now time.Time) error {
	return a.r.InvalidateRestoredExternalCredentials(ctx, now)
}

func (a *TxAuthorizer) ListOAuth2Providers(ctx context.Context) ([]OAuth2Provider, error) {
	return a.r.ListOAuth2Providers(ctx)
}

// ListProviders lists every configured provider.
func (a *TxAuthorizer) ListProviders(ctx context.Context) ([]OIDCProvider, error) {
	return a.r.ListProviders(ctx)
}

// ListSAMLProviders lists all configured SAML providers.
func (a *TxAuthorizer) ListSAMLProviders(ctx context.Context) ([]SAMLProvider, error) {
	return a.r.ListSAMLProviders(ctx)
}

// LiveAccessGrants lists a principal's unexpired temporary grants.
func (a *TxAuthorizer) LiveAccessGrants(ctx context.Context, p domain.PrincipalID, now time.Time) ([]AccessGrant, error) {
	return a.r.LiveAccessGrants(ctx, p, now)
}

func (a *TxAuthorizer) LiveMachineCredentialCount(ctx context.Context, serviceAccountID string, epoch int64, now time.Time) (int64, error) {
	return a.r.LiveMachineCredentialCount(ctx, serviceAccountID, epoch, now)
}

func (a *TxAuthorizer) LiveMachineCredentialCounts(ctx context.Context, scope domain.Scope, epoch int64, now time.Time) (map[string]int64, error) {
	return a.r.LiveMachineCredentialCounts(ctx, scope, epoch, now)
}

// LockCredentialPolicy serializes a mint against a concurrent tightening.
func (a *TxAuthorizer) LockCredentialPolicy(ctx context.Context) error {
	return a.r.LockCredentialPolicy(ctx)
}

func (a *TxAuthorizer) LockInstanceIdentityRow(ctx context.Context) error {
	return a.r.LockInstanceIdentityRow(ctx)
}

// LockMachinePrincipal takes a service account's principal-row lock — THE SAME
// LOCK the grant writers take — so a mint and a grant landing on that
// principal serialize. Without it a grant can widen the account between the
// mint's post-state check and its insert, producing a token whose authority
// never passed the gate.
func (a *TxAuthorizer) LockMachinePrincipal(ctx context.Context, p domain.PrincipalID) error {
	return a.r.LockPrincipalRow(ctx, p)
}

func (a *TxAuthorizer) LockOAuth2ProviderForDelete(ctx context.Context, id string) error {
	return a.r.LockOAuth2ProviderForDelete(ctx, id)
}

// LockProviderForDelete locks the provider row inside the delete tx so the
// session sweep runs with the row held and a concurrent mint guard serializes
// behind it (A14). ErrNotFound means a concurrent delete already removed it.
func (a *TxAuthorizer) LockProviderForDelete(ctx context.Context, id string) error {
	return a.r.LockProviderForDelete(ctx, id)
}

// LockSAMLProviderForDelete serializes provider deletion against Phase-C mints.
func (a *TxAuthorizer) LockSAMLProviderForDelete(ctx context.Context, id string) error {
	return a.r.LockSAMLProviderForDelete(ctx, id)
}

// LockTargetPrincipal takes the target principal's row lock so the org-bounded
// test and every grant mutation serialize on the same row (B14).
func (a *TxAuthorizer) LockTargetPrincipal(ctx context.Context, p domain.PrincipalID) error {
	return a.r.LockPrincipalRow(ctx, p)
}

// LockWorkspaceOrigin and LockInstanceIdentityRow are the two row locks the
// serving side's read-then-write decisions serialize on under postgres' READ
// COMMITTED semantics.
func (a *TxAuthorizer) LockWorkspaceOrigin(ctx context.Context, origin string) (bool, error) {
	return a.r.LockWorkspaceOrigin(ctx, origin)
}

// LockoutRetentions lists every `lockout-retention` origin in the instance,
// which is what the deterministic cure sweep walks (#73 §2.4).
func (a *TxAuthorizer) LockoutRetentions(ctx context.Context) ([]LockoutRetention, error) {
	return a.r.LockoutRetentions(ctx)
}

// LockoutRetentionsInOrg is the org-bounded cure sweep.
func (a *TxAuthorizer) LockoutRetentionsInOrg(ctx context.Context, org domain.OrgID) ([]LockoutRetention, error) {
	return a.r.LockoutRetentionsInOrg(ctx, org)
}

// LoginChallengeByID resolves a login challenge, or domain.ErrNotFound.
func (a *TxAuthorizer) LoginChallengeByID(ctx context.Context, id string) (LoginChallenge, error) {
	return a.r.LoginChallengeByID(ctx, id)
}

func (a *TxAuthorizer) MachineCredentialsFor(ctx context.Context, serviceAccountID string) ([]MachineCredential, error) {
	return a.r.MachineCredentialsFor(ctx, serviceAccountID)
}

// ManageMembersHolders is the lockout invariant's census at one org, or at
// instance scope when org is empty.
func (a *TxAuthorizer) ManageMembersHolders(ctx context.Context, org string) ([]domain.PrincipalID, error) {
	return a.r.ManageMembersHolders(ctx, org)
}

// MarkSAMLSPKeyRetiring compare-and-swaps an active key into overlap state.
func (a *TxAuthorizer) MarkSAMLSPKeyRetiring(ctx context.Context, id string, rowVersion int64) (bool, error) {
	return a.r.MarkSAMLSPKeyRetiring(ctx, id, rowVersion)
}

// MintAuthority writes a new credential-establishment authority.
func (a *TxAuthorizer) MintAuthority(ctx context.Context, n NewCredentialAuthority) error {
	return a.r.CreateCredentialAuthority(ctx, n)
}

func (a *TxAuthorizer) MintInstanceConnection(ctx context.Context, n authn.NewInstanceConnection) error {
	return a.r.MintInstanceConnection(ctx, n)
}

// MintSession writes a session row.
func (a *TxAuthorizer) MintSession(ctx context.Context, s NewSession) error {
	return a.r.CreateSession(ctx, s)
}

func (a *TxAuthorizer) OAuth2ProviderBySlug(ctx context.Context, slug string) (OAuth2Provider, error) {
	return a.r.OAuth2ProviderBySlug(ctx, slug)
}

func (a *TxAuthorizer) OAuth2ProviderForCallback(ctx context.Context, id string) (OAuth2Provider, error) {
	return a.r.OAuth2ProviderForCallback(ctx, id)
}

func (a *TxAuthorizer) OAuth2TransactionByState(ctx context.Context, stateVerifier []byte) (OAuth2Transaction, error) {
	return a.r.OAuth2TransactionByState(ctx, stateVerifier)
}

// OIDCTransactionByState resolves a transaction by its state verifier.
func (a *TxAuthorizer) OIDCTransactionByState(ctx context.Context, stateVerifier []byte) (OIDCTransaction, error) {
	return a.r.OIDCTransactionByState(ctx, stateVerifier)
}

// OpenReauthWindow opens a reauthentication window over one environment.
func (a *TxAuthorizer) OpenReauthWindow(ctx context.Context, w NewReauthWindow) error {
	return a.r.CreateReauthWindow(ctx, w)
}

// PasswordCredentialFor reads an account's verifier row.
func (a *TxAuthorizer) PasswordCredentialFor(ctx context.Context, accountID string) (PasswordCredential, error) {
	return a.r.PasswordCredential(ctx, accountID)
}

// PendingTOTP resolves an account's in-progress enrolment.
func (a *TxAuthorizer) PendingTOTP(ctx context.Context, accountID string) (TOTPCredential, error) {
	return a.r.PendingTOTP(ctx, accountID)
}

// PinGeneration reads the conditional cursor's pin component.
func (a *TxAuthorizer) PinGeneration(ctx context.Context, p domain.PrincipalID, env domain.EnvID) (int64, error) {
	return a.r.PinGeneration(ctx, p, env)
}

// PrincipalClass resolves a principal's class for the normative machine
// allowlists.
func (a *TxAuthorizer) PrincipalClass(ctx context.Context, p domain.PrincipalID) (domain.PrincipalClass, error) {
	return a.r.PrincipalClass(ctx, p)
}

// PrincipalGeneration reads the principal's current session generation, so a
// freshly minted session records the generation it was born under.
func (a *TxAuthorizer) PrincipalGeneration(ctx context.Context, p domain.PrincipalID) (int64, error) {
	return a.r.PrincipalGeneration(ctx, p)
}

func (a *TxAuthorizer) PrivacyAccount(ctx context.Context, p string) (PrivacyAccountView, error) {
	return a.r.PrivacyAccount(ctx, p)
}

func (a *TxAuthorizer) PrivacyActivity(ctx context.Context, p string) ([]PrivacyActivity, error) {
	return a.r.PrivacyActivity(ctx, p)
}

func (a *TxAuthorizer) PrivacySessions(ctx context.Context, p string) ([]PrivacySession, error) {
	return a.r.PrivacySessions(ctx, p)
}

// ProjectMachineReveal reads the per-project machine-reveal opt-in
// (source-of-truth ADR). ErrNotFound for an unknown project.
func (a *TxAuthorizer) ProjectMachineReveal(ctx context.Context, projectID string) (authn.MachineRevealState, error) {
	return a.r.ProjectMachineReveal(ctx, projectID)
}

// ProviderBySlug resolves a provider by slug for administration (any state).
// The mutation that follows is authorized at the chokepoint first.
func (a *TxAuthorizer) ProviderBySlug(ctx context.Context, slug string) (OIDCProvider, error) {
	return a.r.ProviderBySlug(ctx, slug)
}

// ProviderForCallback resolves the provider a transaction pinned, by id.
func (a *TxAuthorizer) ProviderForCallback(ctx context.Context, id string) (OIDCProvider, error) {
	return a.r.ProviderForCallback(ctx, id)
}

func (a *TxAuthorizer) PruneExpiredRegistrationSignup(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.PruneExpiredRegistrationSignup(ctx, id, at)
}

// ReactivateBinding records a restore-time re-validation (§ Restore). #76 owns
// the operator ceremony; the write exists here because the refusal it drives
// exists now.
func (a *TxAuthorizer) ReactivateBinding(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.ReactivateBinding(ctx, id, at)
}

// ReauthWindowFor resolves the window over one environment for one session.
func (a *TxAuthorizer) ReauthWindowFor(ctx context.Context, sessionID, environmentID string) (ReauthWindow, error) {
	return a.r.ReauthWindowFor(ctx, sessionID, environmentID)
}

// RebindSAMLExternalIdentityProvider compare-and-swaps provider provenance
// after the same byte-exact entity has been removed and configured again.
func (a *TxAuthorizer) RebindSAMLExternalIdentityProvider(ctx context.Context, id, expectedProviderID, newProviderID string) (bool, error) {
	return a.r.RebindSAMLExternalIdentityProvider(ctx, id, expectedProviderID, newProviderID)
}

// ReconcilePrincipal commits ONE principal's reconciliation. The signature is
// the guarantee: one id in, one answer out. There is no set-taking sibling of
// this method anywhere in the module, and the drill asserts that.
func (a *TxAuthorizer) ReconcilePrincipal(ctx context.Context, p domain.PrincipalID) (bool, error) {
	return a.r.ReconcilePrincipal(ctx, p)
}

// RecoveryCodesFor resolves an account's batch.
func (a *TxAuthorizer) RecoveryCodesFor(ctx context.Context, accountID string) (RecoveryBatch, error) {
	return a.r.RecoveryCodes(ctx, accountID)
}

// RegistrationPolicyFor resolves the policy of one scope ("" = instance).
func (a *TxAuthorizer) RegistrationPolicyFor(ctx context.Context, org domain.OrgID) (RegistrationPolicy, error) {
	return a.r.RegistrationPolicyFor(ctx, org)
}

func (a *TxAuthorizer) RegistrationSignupByEmail(ctx context.Context, email string) (RegistrationSignup, error) {
	return a.r.RegistrationSignupByEmail(ctx, email)
}

func (a *TxAuthorizer) RegistrationSignupByVerifier(ctx context.Context, verifier []byte) (RegistrationSignup, error) {
	return a.r.RegistrationSignupByVerifier(ctx, verifier)
}

// RegistrationSignupsForPolicy lists a policy's pending local sign-ups.
func (a *TxAuthorizer) RegistrationSignupsForPolicy(ctx context.Context, policyID string) ([]RegistrationSignupRef, error) {
	return a.r.RegistrationSignupsForPolicy(ctx, policyID)
}

func (a *TxAuthorizer) ReissueRegistrationSignup(ctx context.Context, n NewRegistrationSignup) error {
	return a.r.ReissueRegistrationSignup(ctx, n)
}

// ReleaseGrantOrigin releases one origin, reporting whether it held the row.
func (a *TxAuthorizer) ReleaseGrantOrigin(ctx context.Context, grantID string, p domain.PrincipalID, o Origin) (bool, error) {
	return a.r.ReleaseGrantOrigin(ctx, grantID, p, o)
}

// RemoveExternalIdentity removes a link (unlink).
func (a *TxAuthorizer) RemoveExternalIdentity(ctx context.Context, id string) error {
	return a.r.DeleteExternalIdentity(ctx, id)
}

// RemoveTOTPForAccount deletes every TOTP row of an account.
func (a *TxAuthorizer) RemoveTOTPForAccount(ctx context.Context, accountID string) error {
	return a.r.DeleteTOTPForAccount(ctx, accountID)
}

// RemoveWorkspaceOrigin and RevokeWorkspaceSessionsForOrigin are ONE ACT in two
// statements and must be called in one transaction. That pairing is the ADR's
// atomic kill switch; splitting it leaves a window in which an origin is
// de-allowlisted and its sessions still authenticate.
func (a *TxAuthorizer) RemoveWorkspaceOrigin(ctx context.Context, origin string) (bool, error) {
	return a.r.RemoveWorkspaceOrigin(ctx, origin)
}

// ReplacePasswordCredential compare-and-swaps an existing verifier. False
// means the row moved underneath and the caller must not write a stale
// verifier back.
func (a *TxAuthorizer) ReplacePasswordCredential(ctx context.Context, c PasswordCredential, at time.Time) (bool, error) {
	return a.r.UpdatePasswordCredential(ctx, c, at)
}

// ReplaceRecoveryCodes compare-and-swaps the batch; false means it moved.
func (a *TxAuthorizer) ReplaceRecoveryCodes(ctx context.Context, b RecoveryBatch, at time.Time) (bool, error) {
	return a.r.UpdateRecoveryCodes(ctx, b, at)
}

// ReplaceRegistrationPolicy compare-and-swaps a policy and replaces its children.
func (a *TxAuthorizer) ReplaceRegistrationPolicy(ctx context.Context, p RegistrationPolicy, expected int64) (bool, error) {
	return a.r.ReplaceRegistrationPolicy(ctx, p, expected)
}

// ResolveChain answers "is this (org, project, environment) a real chain" —
// the same single-query resolution authorize() itself performs, exposed for the
// one caller that must ask about a scope it is NOT currently authorizing: a
// SCIM mapping row names a scope at AUTHORING time and expands it at every
// sync, and a row whose environment does not belong to its project would write
// grants against a chain that never existed.
// It mints no proof and reveals nothing a caller could not learn by addressing
// the scope: an unresolvable chain answers domain.ErrNotFound uniformly,
// whether the link is missing or foreign.
func (a *TxAuthorizer) ResolveChain(ctx context.Context, scope domain.Scope) (domain.Scope, error) {
	return a.r.ResolveChain(ctx, scope)
}

// RestoreState reads the instance's restore posture.
func (a *TxAuthorizer) RestoreState(ctx context.Context) (RestoreState, error) {
	return a.r.RestoreState(ctx)
}

func (a *TxAuthorizer) RestrictPrivacyPrincipal(ctx context.Context, p, state string) error {
	return a.r.RestrictPrivacyPrincipal(ctx, p, state)
}

// RevokeAllSessionsFor deletes every session of a principal.
func (a *TxAuthorizer) RevokeAllSessionsFor(ctx context.Context, p domain.PrincipalID) error {
	return a.r.DeleteSessionsForPrincipal(ctx, p)
}

func (a *TxAuthorizer) RevokeInstanceConnection(ctx context.Context, id string, at time.Time) (bool, error) {
	return a.r.RevokeInstanceConnection(ctx, id, at)
}

func (a *TxAuthorizer) RevokeMachineCredential(ctx context.Context, serviceAccountID, id string, at time.Time) (bool, error) {
	return a.r.RevokeMachineCredential(ctx, serviceAccountID, id, at)
}

// RevokeSession deletes one session in this transaction.
func (a *TxAuthorizer) RevokeSession(ctx context.Context, id string) error {
	return a.r.DeleteSession(ctx, id)
}

func (a *TxAuthorizer) RevokeSessionForPrincipal(ctx context.Context, id string, p domain.PrincipalID) (bool, error) {
	return a.r.RevokeSessionForPrincipal(ctx, id, p)
}

func (a *TxAuthorizer) RevokeWorkspaceSessionsForOrigin(ctx context.Context, origin string) (int64, error) {
	return a.r.RevokeWorkspaceSessionsForOrigin(ctx, origin)
}

// RotateSessionFactors rotates the acting session token and rewrites its
// factor set on step-up, preserving the original authentication attribution.
func (a *TxAuthorizer) RotateSessionFactors(ctx context.Context, id string, verifier []byte, factors string) error {
	return a.r.RotateSessionFactors(ctx, id, verifier, factors)
}

// SAMLProviderBySlug resolves a provider in any state for administration.
func (a *TxAuthorizer) SAMLProviderBySlug(ctx context.Context, slug string) (SAMLProvider, error) {
	return a.r.SAMLProviderBySlug(ctx, slug)
}

// SAMLProviderForCallback resolves the provider pinned by a transaction.
func (a *TxAuthorizer) SAMLProviderForCallback(ctx context.Context, id string) (SAMLProvider, error) {
	return a.r.SAMLProviderForCallback(ctx, id)
}

// SAMLSPKeys lists active and overlap-retiring public material.
func (a *TxAuthorizer) SAMLSPKeys(ctx context.Context) ([]SAMLSPKey, error) {
	return a.r.SAMLSPKeys(ctx)
}

// SAMLTransactionByRelayState resolves the opaque front-channel handle before
// the strict wrapper's single response-validation pass.
func (a *TxAuthorizer) SAMLTransactionByRelayState(ctx context.Context, verifier []byte) (SAMLTransaction, error) {
	return a.r.SAMLTransactionByRelayState(ctx, verifier)
}

func (a *TxAuthorizer) SCIMCredentialByVerifier(ctx context.Context, presented []byte) (SCIMCredential, error) {
	return a.r.SCIMCredentialByVerifier(ctx, presented)
}

// ServiceAccountAt resolves one service account within an addressed project;
// an id from another project answers domain.ErrNotFound.
func (a *TxAuthorizer) ServiceAccountAt(ctx context.Context, scope domain.Scope, id string) (ServiceAccount, error) {
	return a.r.ServiceAccountAt(ctx, scope, id)
}

// ServiceAccountByPrincipal resolves the service account a machine principal
// is, for the grant surface's subtree confinement.
func (a *TxAuthorizer) ServiceAccountByPrincipal(ctx context.Context, p domain.PrincipalID) (ServiceAccount, error) {
	return a.r.ServiceAccountByPrincipal(ctx, p)
}

func (a *TxAuthorizer) ServiceAccountsIn(ctx context.Context, scope domain.Scope) ([]ServiceAccount, error) {
	return a.r.ServiceAccountsIn(ctx, scope)
}

// SessionsForPrincipal and RevokeSessionForPrincipal are the self-scoped
// active-session surface (#71 criterion 5). The principal conjunct is in the
// SQL, so one caller structurally cannot reach another's row.
func (a *TxAuthorizer) SessionsForPrincipal(ctx context.Context, p domain.PrincipalID) ([]authn.SessionSummary, error) {
	return a.r.SessionsForPrincipal(ctx, p)
}

// SetClock fixes the instant time-bound grants are evaluated against for the
// rest of this transaction. The service layer's authorize prelude sets it from
// the service clock, so expiry is judged by one clock per operation. Zero
// restores wall-clock evaluation at each lookup.
func (a *TxAuthorizer) SetClock(now time.Time) {
	a.r.SetClock(now)
}

func (a *TxAuthorizer) SetCredentialPolicy(ctx context.Context, p CredentialPolicy, actor domain.PrincipalID, at time.Time) error {
	return a.r.SetCredentialPolicy(ctx, p, actor, at)
}

func (a *TxAuthorizer) SetLocalAccountEmail(ctx context.Context, id, email string, at time.Time) error {
	return a.r.SetLocalAccountEmail(ctx, id, email, at)
}

// SetPinGeneration advances it. #52 owns pin creation, reassignment and release.
func (a *TxAuthorizer) SetPinGeneration(ctx context.Context, p domain.PrincipalID, env domain.EnvID, generation int64) error {
	return a.r.SetPinGeneration(ctx, p, env, generation)
}

// SetWebAuthnUserHandle sets the opaque handle once; false means one already
// exists (the caller reads it back rather than rotating).
func (a *TxAuthorizer) SetWebAuthnUserHandle(ctx context.Context, accountID string, handle []byte) (bool, error) {
	return a.r.SetWebAuthnUserHandle(ctx, accountID, handle)
}

// SlideReauthWindow advances a sliding window's idle clock; false means the row
// moved and the caller must not extend it.
func (a *TxAuthorizer) SlideReauthWindow(ctx context.Context, id string, windowExpires time.Time) (bool, error) {
	return a.r.SlideReauthWindow(ctx, id, windowExpires)
}

// SlideSession advances the idle clock only. The absolute lifetime is never
// extended by activity — two independent clocks is the design.
func (a *TxAuthorizer) SlideSession(ctx context.Context, id string, seen, idleExpires time.Time) error {
	return a.r.TouchSession(ctx, id, seen, idleExpires)
}

func (a *TxAuthorizer) StampCredentialEstablish(ctx context.Context, sessionID, identityID string, expires time.Time) error {
	return a.r.StampCredentialEstablish(ctx, sessionID, identityID, expires)
}

// StrandedRevealPrincipals enumerates the reveal-holding principals a 0
// effective window would strand on the given environment chain (B6).
func (a *TxAuthorizer) StrandedRevealPrincipals(ctx context.Context, org, project, env string) ([]domain.PrincipalID, error) {
	return a.r.StrandedRevealPrincipals(ctx, org, project, env)
}

func (a *TxAuthorizer) SweepExpiredWorkspaceHandoffs(ctx context.Context, before time.Time) (int64, error) {
	return a.r.SweepExpiredWorkspaceHandoffs(ctx, before)
}

// SweepSessionsForProvider deletes every session minted through a provider and
// returns the count for audit (A4).
func (a *TxAuthorizer) SweepSessionsForProvider(ctx context.Context, providerID string) (int64, error) {
	return a.r.DeleteSessionsForProvider(ctx, providerID)
}

// SweepSessionsForSAMLProvider deletes all sessions minted through a SAML IdP.
func (a *TxAuthorizer) SweepSessionsForSAMLProvider(ctx context.Context, providerID string) (int64, error) {
	return a.r.DeleteSessionsForSAMLProvider(ctx, providerID)
}

// SweepSessionsForWebAuthnCredential deletes every session a passkey login
// minted through a credential and returns the count for audit (B9 clone sweep).
func (a *TxAuthorizer) SweepSessionsForWebAuthnCredential(ctx context.Context, credentialID string) (int64, error) {
	return a.r.DeleteSessionsForWebAuthnCredential(ctx, credentialID)
}

func (a *TxAuthorizer) TouchInstanceConnection(ctx context.Context, id string, at time.Time) error {
	return a.r.TouchInstanceConnection(ctx, id, at)
}

func (a *TxAuthorizer) TouchMachineCredential(ctx context.Context, id string, at time.Time) error {
	return a.r.TouchMachineCredential(ctx, id, at)
}

func (a *TxAuthorizer) TouchSCIMCredential(ctx context.Context, id string, at time.Time) error {
	return a.r.TouchSCIMCredential(ctx, id, at)
}

// UnreconciledPrincipals lists who is still inert.
func (a *TxAuthorizer) UnreconciledPrincipals(ctx context.Context) ([]PrincipalRef, error) {
	return a.r.UnreconciledPrincipals(ctx)
}

func (a *TxAuthorizer) UpdateAccountProfile(ctx context.Context, accountID string, profile AccountProfile) error {
	return a.r.UpdateAccountProfile(ctx, accountID, profile)
}

func (a *TxAuthorizer) UpdateFederationIssuer(ctx context.Context, id string, source jwkssource.KeySource, refused []string, caBundle string, actor domain.PrincipalID, at time.Time) (bool, error) {
	return a.r.UpdateFederationIssuer(ctx, id, source, refused, caBundle, actor, at)
}

func (a *TxAuthorizer) UpdateOAuth2Provider(ctx context.Context, u OAuth2ProviderUpdate) (bool, error) {
	return a.r.UpdateOAuth2Provider(ctx, u)
}

// UpdateProvider compare-and-swaps a provider; false means the row moved.
func (a *TxAuthorizer) UpdateProvider(ctx context.Context, u ProviderUpdate) (bool, error) {
	return a.r.UpdateProvider(ctx, u)
}

// UpdateSAMLProvider compare-and-swaps a provider configuration.
func (a *TxAuthorizer) UpdateSAMLProvider(ctx context.Context, provider SAMLProviderUpdate) (bool, error) {
	return a.r.UpdateSAMLProvider(ctx, provider)
}

func (a *TxAuthorizer) VerifiedAccountEmailExists(ctx context.Context, email string) (bool, error) {
	return a.r.VerifiedAccountEmailExists(ctx, email)
}

// WebAuthnCeremonyByChallenge resolves a ceremony by its challenge verifier.
func (a *TxAuthorizer) WebAuthnCeremonyByChallenge(ctx context.Context, challengeVerifier []byte) (WebAuthnCeremony, error) {
	return a.r.WebAuthnCeremonyByChallenge(ctx, challengeVerifier)
}

// WebAuthnCeremonyByID resolves a ceremony by id, for single-decision window
// unit matching at disclosure.
func (a *TxAuthorizer) WebAuthnCeremonyByID(ctx context.Context, id string) (WebAuthnCeremony, error) {
	return a.r.WebAuthnCeremonyByID(ctx, id)
}

// WebAuthnCredentialByCredentialID resolves the row a passkey assertion names.
func (a *TxAuthorizer) WebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebAuthnCredential, error) {
	return a.r.WebAuthnCredentialByCredentialID(ctx, credentialID)
}

// WebAuthnCredentialByID resolves a credential by its surrogate id.
func (a *TxAuthorizer) WebAuthnCredentialByID(ctx context.Context, id string) (WebAuthnCredential, error) {
	return a.r.WebAuthnCredentialByID(ctx, id)
}

// WebAuthnCredentialsForAccount lists an account's passkeys.
func (a *TxAuthorizer) WebAuthnCredentialsForAccount(ctx context.Context, accountID string) ([]WebAuthnCredential, error) {
	return a.r.WebAuthnCredentialsForAccount(ctx, accountID)
}

// WebAuthnUserHandle reads an account's opaque handle, or nil when unset.
func (a *TxAuthorizer) WebAuthnUserHandle(ctx context.Context, accountID string) ([]byte, error) {
	return a.r.WebAuthnUserHandle(ctx, accountID)
}

// WorkloadPinState reads the conditional reveal-history admission fact.
func (a *TxAuthorizer) WorkloadPinState(ctx context.Context, p domain.PrincipalID, env domain.EnvID) (WorkloadPinState, error) {
	return a.r.WorkloadPinState(ctx, p, env)
}

func (a *TxAuthorizer) WorkspaceHandoffByCode(ctx context.Context, verifier []byte) (authn.WorkspaceHandoff, error) {
	return a.r.WorkspaceHandoffByCode(ctx, verifier)
}

func (a *TxAuthorizer) WorkspaceHandoffByState(ctx context.Context, verifier []byte) (authn.WorkspaceHandoff, error) {
	return a.r.WorkspaceHandoffByState(ctx, verifier)
}

func (a *TxAuthorizer) WorkspaceOriginAllowed(ctx context.Context, origin string) (bool, error) {
	return a.r.WorkspaceOriginAllowed(ctx, origin)
}

func (a *TxAuthorizer) WorkspaceOrigins(ctx context.Context) ([]authn.WorkspaceOrigin, error) {
	return a.r.WorkspaceOrigins(ctx)
}

// WritePasswordCredential inserts the first verifier for an account.
func (a *TxAuthorizer) WritePasswordCredential(ctx context.Context, c PasswordCredential, at time.Time) error {
	return a.r.CreatePasswordCredential(ctx, c, at)
}

// WriteRecoveryCodes writes the first batch for an account.
func (a *TxAuthorizer) WriteRecoveryCodes(ctx context.Context, b RecoveryBatch, at time.Time) error {
	return a.r.CreateRecoveryCodes(ctx, b, at)
}
