// compatibility builds the source-owned declaration before any release binary.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/Hikyo-Org/hikyo/internal/app"
	"github.com/Hikyo-Org/hikyo/internal/buildcompat"
	"github.com/Hikyo-Org/hikyo/internal/definitions"
	"github.com/Hikyo-Org/hikyo/internal/releaseidentity"
	"github.com/Hikyo-Org/hikyo/internal/releasetrust"
	"github.com/Hikyo-Org/hikyo/internal/upgradecompat"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "compatibility:", err)
		os.Exit(1)
	}
}
func run() error {
	candidatePath := flag.String("candidate", "", "resolved release candidate")
	sourcesPath := flag.String("sources", "release/compatibility/sources.json", "reviewed exact source edges")
	output := flag.String("out", "", "output declaration; must not exist")
	development := flag.Bool("development", false, "generate isolated source-owned development claims")
	profile := flag.String("profile", string(releaseidentity.StableV1), "stable/v1 or nightly/v1 build profile")
	check := flag.String("check", "", "compare exact regenerated bytes with a committed declaration")
	flag.Parse()
	if (*candidatePath == "" && !*development) || (*output == "") == (*check == "") || flag.NArg() != 0 {
		return fmt.Errorf("--candidate and --out are required; HIKYO_RELEASE_SCHEMA_POSTGRES_DSN must name an empty scratch database")
	}
	var candidate releasetrust.Candidate
	if *development {
		if *profile != string(releaseidentity.StableV1) {
			return fmt.Errorf("development cannot select a release profile")
		}
		if *candidatePath != "" {
			return fmt.Errorf("development mode cannot claim a release candidate")
		}
		candidate = releasetrust.Candidate{Version: buildcompat.DevelopmentVersion, Sequence: 1, Commit: buildcompat.DevelopmentCommit}
	} else {
		raw, err := os.ReadFile(*candidatePath)
		if err != nil {
			return err
		}
		if len(raw) > releasetrust.MaxDocumentBytes {
			return fmt.Errorf("candidate too large")
		}
		if err := definitions.DecodeStrict(raw, &candidate); err != nil {
			return err
		}
	}
	raw, err := os.ReadFile(*sourcesPath)
	if err != nil {
		return err
	}
	var sources struct {
		Schema  string                                                `json:"schema"`
		Engines map[releaseidentity.Engine][]upgradecompat.SourceEdge `json:"engines"`
	}
	if len(raw) > releasetrust.MaxDocumentBytes {
		return fmt.Errorf("sources too large")
	}
	if err := definitions.DecodeStrict(raw, &sources); err != nil {
		return err
	}
	if sources.Schema != "hikyo.dev/upgrade-sources/v1" || candidate.Sequence < 1 {
		return fmt.Errorf("invalid source schema or candidate sequence")
	}
	if *development {
		for engine, edges := range sources.Engines {
			fresh := []upgradecompat.SourceEdge{}
			for _, edge := range edges {
				if edge.Source.Genesis == releaseidentity.FreshGenesisV1 {
					fresh = append(fresh, edge)
				}
			}
			sources.Engines[engine] = fresh
		}
	}
	declaration, err := app.GenerateReleaseCompatibility(context.Background(), app.ReleaseCompatibilityRequest{Profile: releaseidentity.Profile(*profile), Version: candidate.Version, Sequence: uint64(candidate.Sequence), Commit: candidate.Commit, Sources: sources.Engines, PostgreSQLDSN: os.Getenv("HIKYO_RELEASE_SCHEMA_POSTGRES_DSN")})
	if err != nil {
		return err
	}
	if *check != "" {
		existing, err := os.ReadFile(*check)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, declaration) {
			return fmt.Errorf("committed declaration differs from actual embedded SQL or migrated catalog; regenerate and review")
		}
		return nil
	}
	file, err := os.OpenFile(*output, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return err
	}
	if _, err := file.Write(declaration); err != nil {
		file.Close()
		return err
	}
	return file.Close()
}
