package lint

// Reviewed timestamp representation pairs, scoped by query and semantic field.
var timestampQueryFields = map[string]map[string]bool{
	"AdapterWorkerActivateOriginRouteMoveActivateAdapter": {"Expires": true},
	"AdapterWorkerClaimDueUpdate":                         {"LeaseUntil": true},
	"AdapterWorkerFinishJobQuery":                         {"Due": true},
	"AdapterWorkerPrepareLease":                           {"LeaseUntil": true},
	"AdapterWorkerPrepareProviderLease":                   {"LeaseUntil": true, "NowStamp": true},
	"CoordinationClaimLease":                              {"Expires": true},
	"CoordinationCountLiveNodes":                          {"Since": true},
	"CoordinationForeignRootKeyFingerprints":              {"Since": true},
	"CoordinationMCPRateBucket":                           {"CoordinationMCPRateBucket": true},
	"CoordinationPruneAccountBackoff":                     {"Cutoff": true},
	"CoordinationPruneAdmissionWindows":                   {"Cutoff": true},
	"CoordinationPruneNodes":                              {"Cutoff": true},
	"CoordinationReleaseLease":                            {"Expires": true},
	"CoordinationRenewLease":                              {"Expires": true},
	"DynamicCreateLease":                                  {"Grace": true},
	"PKIActiveIssuer":                                     {"CrlNextUpdate": true, "CrlThisUpdate": true, "NotAfter": true, "NotBefore": true},
	"PKICreateCertificate":                                {"IssuingDeadline": true, "NotAfter": true, "NotBefore": true},
	"PKICreateIssuer":                                     {"NotAfter": true, "NotBefore": true},
	"PKIGetCertificate":                                   {"IssuingDeadline": true, "NotAfter": true, "NotBefore": true},
	"PKIGetIssuer":                                        {"CrlNextUpdate": true, "CrlThisUpdate": true, "NotAfter": true, "NotBefore": true},
	"PKIInstallIssuer":                                    {"NotAfter": true, "NotBefore": true},
	"PKIListCertificates":                                 {"IssuingDeadline": true, "NotAfter": true, "NotBefore": true},
	"PKIListIssuers":                                      {"CrlNextUpdate": true, "CrlThisUpdate": true, "NotAfter": true, "NotBefore": true},
	"PKIPublishCRL":                                       {"NextUpdate": true, "ThisUpdate": true},
	"PKISigningIssuer":                                    {"CrlNextUpdate": true, "CrlThisUpdate": true, "NotAfter": true, "NotBefore": true},
	"RuntimeDynamicClaimLease":                            {"Until": true},
	"RuntimeDynamicRetryLease":                            {"NextAttempt": true},
	"RuntimeDynamicSettleLease":                           {"NextAttempt": true},
	"RuntimePKIDueCRLs":                                   {"HalfLife": true},
	"SSHActiveKeyLastExpiry":                              {"SSHActiveKeyLastExpiry": true},
	"SSHCAKeys":                                           {"RetireAfter": true},
	"SSHGetCertificate":                                   {"CaKeyRetireAfter": true, "ValidAfter": true, "ValidBefore": true},
	"SSHInsertCertificate":                                {"ValidAfter": true, "ValidBefore": true},
	"SSHListCertificates":                                 {"CaKeyRetireAfter": true, "ValidAfter": true, "ValidBefore": true},
	"SSHRetireActiveCAKey":                                {"RetireAfter": true},
	"TransitChangeState":                                  {"DeletionAfter": true},
	"TransitGetKey":                                       {"DeletionAfter": true},
	"TransitGetKeyForUse":                                 {"DeletionAfter": true},
	"TransitKeyByID":                                      {"DeletionAfter": true},
	"TransitListKeys":                                     {"DeletionAfter": true},
	"TransitSelectDeletionDue":                            {"DeletionAfter": true},
	"TransitSelectRotationDue":                            {"DeletionAfter": true},
}
