package lint

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// These are tenant-scoped queries reviewed beyond the bounded SQL grammar.
// They are still generated by sqlc and retain their scope classification.
type scopedQueryReview struct {
	SQLHash   string   `json:"sql_hash"`
	APIHash   string   `json:"api_hash"`
	Authority string   `json:"authority"`
	Tests     []string `json:"tests"`
	FlowTests []string `json:"flow_tests,omitempty"`
}

//go:embed testdata/scoped_query_reviews.json
var scopedQueryReviewsJSON []byte

func readScopedQueryReviews() (map[string]map[string]scopedQueryReview, error) {
	var reviews map[string]map[string]scopedQueryReview
	err := json.Unmarshal(scopedQueryReviewsJSON, &reviews)
	return reviews, err
}

func checkScopedQueryReview(engine string, q Query, api generatedContract, generated bool, review scopedQueryReview, root string) []string {
	label := fmt.Sprintf("sqlpredicate(%s): %s", engine, q.Name)
	if q.Annotation != "" || !generated || !api.BindSitesKnown || strings.TrimSpace(review.Authority) == "" || review.SQLHash != q.Hash() || review.APIHash != api.hash() || len(review.Tests) == 0 {
		return []string{fmt.Sprintf("%s: changed or incomplete reviewed scoped query: sql=%s api=%s", label, q.Hash(), api.hash())}
	}
	var findings []string
	queryReferenced := false
	evidenceRefs := append(append([]string{}, review.Tests...), review.FlowTests...)
	for index, evidence := range evidenceRefs {
		path, name, ok := strings.Cut(evidence, ":")
		clean := filepath.Clean(path)
		if !ok || filepath.IsAbs(path) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) || !strings.HasSuffix(path, "_test.go") || !strings.HasPrefix(name, "Test") {
			findings = append(findings, label+": invalid scoped-query test reference "+evidence)
			continue
		}
		full := filepath.Join(root, clean)
		info, err := os.Lstat(full)
		if err != nil || !info.Mode().IsRegular() {
			findings = append(findings, label+": missing scoped-query test source "+evidence)
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), full, nil, 0)
		if err != nil {
			findings = append(findings, label+": invalid scoped-query test source "+evidence)
			continue
		}
		found := false
		for _, declaration := range file.Decls {
			if function, ok := declaration.(*ast.FuncDecl); ok && function.Recv == nil && function.Name.Name == name && function.Body != nil {
				found = true
				if index >= len(review.Tests) {
					continue
				}
				ast.Inspect(function.Body, func(node ast.Node) bool {
					switch node := node.(type) {
					case *ast.Ident:
						queryReferenced = queryReferenced || node.Name == q.Name
					case *ast.BasicLit:
						if node.Kind == token.STRING {
							value, err := strconv.Unquote(node.Value)
							queryReferenced = queryReferenced || err == nil && value == q.Name
						}
					}
					return true
				})
			}
		}
		if !found {
			findings = append(findings, label+": missing scoped-query regression "+evidence)
		}
	}
	if !queryReferenced {
		findings = append(findings, label+": query is absent from referenced test bodies")
	}
	return findings
}
