// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOfflineRecord = `-- name: ClaimOfflineRecord :execrows
INSERT INTO offline_records (principal_id, record_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (principal_id, record_id) DO NOTHING
`

type ClaimOfflineRecordParams struct {
	PrincipalID string
	RecordID    string
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) ClaimOfflineRecord(ctx context.Context, arg ClaimOfflineRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimOfflineRecord, arg.PrincipalID, arg.RecordID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInstanceAuditEvent = `-- name: InsertInstanceAuditEvent :exec
INSERT INTO audit_instance_events (
    id, type, schema_version, occurred_at, occurred_asserted,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (
    $1, $2, $3, $4,
    $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17
)
`

type InsertInstanceAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

func (q *Queries) InsertInstanceAuditEvent(ctx context.Context, arg InsertInstanceAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertInstanceAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec

INSERT INTO audit_tenant_events (
    id, type, schema_version, occurred_at, occurred_asserted,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (
    $1, $2, $3, $4,
    $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21
)
`

type InsertTenantAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ScopeClass        string
	ChainOrgID        string
	ProjectID         pgtype.Text
	EnvID             pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

// Audit trails (#45): the application layer holds INSERT and SELECT only on
// both audit tables - the append-only CI invariant scans this file. The
// reserved chain_* parameters are bound by the store's binding layer (and,
// for the denial writer, by the authorization package's enumerated surface)
// from resolved chains only - never from caller arguments.
//
// Query page order is seq (allocation order). Export pages use commit_seq,
// assigned by the deferred commit appender in migration 00010; the public
// after_seq filter remains a seq lower bound.
func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ScopeClass,
		arg.ChainOrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const maxInstanceAudit = `-- name: MaxInstanceAudit :one
SELECT CAST(COALESCE(MAX(seq), 0) AS BIGINT) FROM audit_instance_events
`

func (q *Queries) MaxInstanceAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxInstanceAudit)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxTenantAuditEnv = `-- name: MaxTenantAuditEnv :one
SELECT CAST(COALESCE(MAX(seq), 0) AS BIGINT) FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND env_id = $3
`

type MaxTenantAuditEnvParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	ChainEnvID     pgtype.Text
}

func (q *Queries) MaxTenantAuditEnv(ctx context.Context, arg MaxTenantAuditEnvParams) (int64, error) {
	row := q.db.QueryRow(ctx, maxTenantAuditEnv, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxTenantAuditOrg = `-- name: MaxTenantAuditOrg :one

SELECT CAST(COALESCE(MAX(seq), 0) AS BIGINT) FROM audit_tenant_events
WHERE org_id = $1
`

// Session ceiling reads (#502): the interactive query pins a stable upper seq
// bound on its first page so paging terminates across concurrent writes, and
// so a query never chases the audit.query events its own reads append. Chain-
// confined exactly like the page reads. The CAST pins the type for sqlc; an
// empty trail is a 0 ceiling, not NULL.
func (q *Queries) MaxTenantAuditOrg(ctx context.Context, chainOrgID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxTenantAuditOrg, chainOrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxTenantAuditProject = `-- name: MaxTenantAuditProject :one
SELECT CAST(COALESCE(MAX(seq), 0) AS BIGINT) FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
`

type MaxTenantAuditProjectParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
}

func (q *Queries) MaxTenantAuditProject(ctx context.Context, arg MaxTenantAuditProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, maxTenantAuditProject, arg.ChainOrgID, arg.ChainProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pageInstanceAudit = `-- name: PageInstanceAudit :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_instance_events
WHERE seq > $1
    AND recorded_at >= $2 AND recorded_at <= $3
ORDER BY seq LIMIT $4
`

type PageInstanceAuditParams struct {
	AfterSeq  int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
	PageLimit int32
}

func (q *Queries) PageInstanceAudit(ctx context.Context, arg PageInstanceAuditParams) ([]AuditInstanceEvent, error) {
	rows, err := q.db.Query(ctx, pageInstanceAudit,
		arg.AfterSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditInstanceEvent
	for rows.Next() {
		var i AuditInstanceEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageInstanceAuditExport = `-- name: PageInstanceAuditExport :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_instance_events
WHERE seq > $1 AND commit_seq > $2
    AND recorded_at >= $3 AND recorded_at <= $4
ORDER BY commit_seq LIMIT $5
`

type PageInstanceAuditExportParams struct {
	AfterSeq       int64
	AfterCommitSeq pgtype.Int8
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageInstanceAuditExport(ctx context.Context, arg PageInstanceAuditExportParams) ([]AuditInstanceEvent, error) {
	rows, err := q.db.Query(ctx, pageInstanceAuditExport,
		arg.AfterSeq,
		arg.AfterCommitSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditInstanceEvent
	for rows.Next() {
		var i AuditInstanceEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditEnv = `-- name: PageTenantAuditEnv :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND env_id = $3 AND seq > $4
    AND recorded_at >= $5 AND recorded_at <= $6
ORDER BY seq LIMIT $7
`

type PageTenantAuditEnvParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	ChainEnvID     pgtype.Text
	AfterSeq       int64
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditEnv(ctx context.Context, arg PageTenantAuditEnvParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditEnv,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.AfterSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditExportEnv = `-- name: PageTenantAuditExportEnv :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND env_id = $3
    AND seq > $4 AND commit_seq > $5
    AND recorded_at >= $6 AND recorded_at <= $7
ORDER BY commit_seq LIMIT $8
`

type PageTenantAuditExportEnvParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	ChainEnvID     pgtype.Text
	AfterSeq       int64
	AfterCommitSeq pgtype.Int8
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditExportEnv(ctx context.Context, arg PageTenantAuditExportEnvParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditExportEnv,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.AfterSeq,
		arg.AfterCommitSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditExportOrg = `-- name: PageTenantAuditExportOrg :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1
    AND seq > $2 AND commit_seq > $3
    AND recorded_at >= $4 AND recorded_at <= $5
ORDER BY commit_seq LIMIT $6
`

type PageTenantAuditExportOrgParams struct {
	ChainOrgID     string
	AfterSeq       int64
	AfterCommitSeq pgtype.Int8
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditExportOrg(ctx context.Context, arg PageTenantAuditExportOrgParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditExportOrg,
		arg.ChainOrgID,
		arg.AfterSeq,
		arg.AfterCommitSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditExportProject = `-- name: PageTenantAuditExportProject :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND seq > $3 AND commit_seq > $4
    AND recorded_at >= $5 AND recorded_at <= $6
ORDER BY commit_seq LIMIT $7
`

type PageTenantAuditExportProjectParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	AfterSeq       int64
	AfterCommitSeq pgtype.Int8
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditExportProject(ctx context.Context, arg PageTenantAuditExportProjectParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditExportProject,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.AfterSeq,
		arg.AfterCommitSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditOrg = `-- name: PageTenantAuditOrg :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1 AND seq > $2
    AND recorded_at >= $3 AND recorded_at <= $4
ORDER BY seq LIMIT $5
`

type PageTenantAuditOrgParams struct {
	ChainOrgID string
	AfterSeq   int64
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageLimit  int32
}

func (q *Queries) PageTenantAuditOrg(ctx context.Context, arg PageTenantAuditOrgParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditOrg,
		arg.ChainOrgID,
		arg.AfterSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditProject = `-- name: PageTenantAuditProject :many
SELECT seq, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload, commit_seq
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND seq > $3
    AND recorded_at >= $4 AND recorded_at <= $5
ORDER BY seq LIMIT $6
`

type PageTenantAuditProjectParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	AfterSeq       int64
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditProject(ctx context.Context, arg PageTenantAuditProjectParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditProject,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.AfterSeq,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
			&i.CommitSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
