// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: developer_credentials.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clampDeveloperCredentialExpiry = `-- name: ClampDeveloperCredentialExpiry :exec
UPDATE developer_credentials SET expires_at = $1 WHERE id = $2 AND expires_at > $1
`

type ClampDeveloperCredentialExpiryParams struct {
	Ceiling pgtype.Timestamptz
	ID      string
}

// hikyo:reason Authorized instance policy lowering persists monotonic expiry reductions before commit.
// hikyo:authn-resolution
func (q *Queries) ClampDeveloperCredentialExpiry(ctx context.Context, arg ClampDeveloperCredentialExpiryParams) error {
	_, err := q.db.Exec(ctx, clampDeveloperCredentialExpiry, arg.Ceiling, arg.ID)
	return err
}

const developerCredentialByVerifier = `-- name: DeveloperCredentialByVerifier :one
SELECT id,principal_id,authority_principal_id,org_id,project_id,env_id,verifier,prefix_hint,parent_session_id,provider_id,oauth2_provider_id,saml_provider_id,auth_method,authority_generation,credential_epoch,created_at,expires_at,revoked_at FROM developer_credentials WHERE verifier = $1
`

// hikyo:reason Authentication resolves the presented verifier before any authorization proof can exist.
// hikyo:authn-resolution
func (q *Queries) DeveloperCredentialByVerifier(ctx context.Context, verifier []byte) (DeveloperCredential, error) {
	row := q.db.QueryRow(ctx, developerCredentialByVerifier, verifier)
	var i DeveloperCredential
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.AuthorityPrincipalID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvID,
		&i.Verifier,
		&i.PrefixHint,
		&i.ParentSessionID,
		&i.ProviderID,
		&i.Oauth2ProviderID,
		&i.SamlProviderID,
		&i.AuthMethod,
		&i.AuthorityGeneration,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeveloperCredentialPolicy = `-- name: GetDeveloperCredentialPolicy :one
SELECT max_lifetime_seconds FROM developer_credential_policy WHERE id=1 FOR UPDATE
`

// hikyo:reason Mint and policy tightening serialize on this shared instance policy before changing delegation authority.
// hikyo:authn-resolution
func (q *Queries) GetDeveloperCredentialPolicy(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDeveloperCredentialPolicy)
	var max_lifetime_seconds int64
	err := row.Scan(&max_lifetime_seconds)
	return max_lifetime_seconds, err
}

const insertDeveloperCredential = `-- name: InsertDeveloperCredential :exec
INSERT INTO developer_credentials (id,principal_id,authority_principal_id,org_id,project_id,env_id,verifier,prefix_hint,parent_session_id,provider_id,oauth2_provider_id,saml_provider_id,auth_method,authority_generation,credential_epoch,created_at,expires_at,revoked_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
`

type InsertDeveloperCredentialParams struct {
	ID                   string
	PrincipalID          string
	AuthorityPrincipalID string
	OrgID                string
	ProjectID            string
	EnvID                string
	Verifier             []byte
	PrefixHint           string
	ParentSessionID      string
	ProviderID           string
	Oauth2ProviderID     string
	SamlProviderID       string
	AuthMethod           string
	AuthorityGeneration  int64
	CredentialEpoch      int64
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
}

// hikyo:reason Mint authenticated human delegation only after exact scope-bound reauthentication and tenant authorization in this transaction.
// hikyo:authn-resolution
func (q *Queries) InsertDeveloperCredential(ctx context.Context, arg InsertDeveloperCredentialParams) error {
	_, err := q.db.Exec(ctx, insertDeveloperCredential,
		arg.ID,
		arg.PrincipalID,
		arg.AuthorityPrincipalID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.Verifier,
		arg.PrefixHint,
		arg.ParentSessionID,
		arg.ProviderID,
		arg.Oauth2ProviderID,
		arg.SamlProviderID,
		arg.AuthMethod,
		arg.AuthorityGeneration,
		arg.CredentialEpoch,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const listDeveloperCredentials = `-- name: ListDeveloperCredentials :many
SELECT id,principal_id,authority_principal_id,org_id,project_id,env_id,verifier,prefix_hint,parent_session_id,provider_id,oauth2_provider_id,saml_provider_id,auth_method,authority_generation,credential_epoch,created_at,expires_at,revoked_at FROM developer_credentials ORDER BY created_at,id
`

// hikyo:reason Transaction-local lifecycle administration filters this metadata after self or project authorization; no bearer can be recovered.
// hikyo:authn-resolution
func (q *Queries) ListDeveloperCredentials(ctx context.Context) ([]DeveloperCredential, error) {
	rows, err := q.db.Query(ctx, listDeveloperCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeveloperCredential
	for rows.Next() {
		var i DeveloperCredential
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.AuthorityPrincipalID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.Verifier,
			&i.PrefixHint,
			&i.ParentSessionID,
			&i.ProviderID,
			&i.Oauth2ProviderID,
			&i.SamlProviderID,
			&i.AuthMethod,
			&i.AuthorityGeneration,
			&i.CredentialEpoch,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDeveloperPolicySeedOccupied = `-- name: RestoreDeveloperPolicySeedOccupied :one
SELECT EXISTS (SELECT 1 FROM developer_credential_policy WHERE id <> 1 OR max_lifetime_seconds <> 28800)
`

// Only untouched migration policy defaults may be replaced by a restore.
// hikyo:reason restore target admission checks developer policy without exposing authentication verifiers
// hikyo:authn-resolution
func (q *Queries) RestoreDeveloperPolicySeedOccupied(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, restoreDeveloperPolicySeedOccupied)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeDeveloperCredential = `-- name: RevokeDeveloperCredential :exec
UPDATE developer_credentials SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeDeveloperCredentialParams struct {
	RevokedAt pgtype.Timestamptz
	ID        string
}

// hikyo:reason Terminal security invalidation writes authentication state atomically with its authorizing mutation.
// hikyo:authn-resolution
func (q *Queries) RevokeDeveloperCredential(ctx context.Context, arg RevokeDeveloperCredentialParams) error {
	_, err := q.db.Exec(ctx, revokeDeveloperCredential, arg.RevokedAt, arg.ID)
	return err
}

const setDeveloperCredentialPolicy = `-- name: SetDeveloperCredentialPolicy :exec
UPDATE developer_credential_policy SET max_lifetime_seconds = $1 WHERE id=1
`

// hikyo:reason Instance-config authorization precedes the shared lifetime policy mutation in the same transaction.
// hikyo:authn-resolution
func (q *Queries) SetDeveloperCredentialPolicy(ctx context.Context, maxLifetimeSeconds int64) error {
	_, err := q.db.Exec(ctx, setDeveloperCredentialPolicy, maxLifetimeSeconds)
	return err
}
