// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federation.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBindingsForIssuer = `-- name: CountBindingsForIssuer :one
SELECT COUNT(*) FROM machine_credentials
WHERE issuer_id = $1
`

// Every binding naming an issuer, live or historical; see the sqlite dialect for
// why the revoked rows count too.
// hikyo:authn-resolution
func (q *Queries) CountBindingsForIssuer(ctx context.Context, issuerID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countBindingsForIssuer, issuerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFederationIssuer = `-- name: DeleteFederationIssuer :execrows
DELETE FROM federation_issuers WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeleteFederationIssuer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFederationIssuer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePinGenerationsForPrincipal = `-- name: DeletePinGenerationsForPrincipal :execrows
DELETE FROM pin_generations WHERE principal_id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeletePinGenerationsForPrincipal(ctx context.Context, principalID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePinGenerationsForPrincipal, principalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const federatedBindingByIdentity = `-- name: FederatedBindingByIdentity :one
SELECT id, service_account_id, kind, prefix_hint, lifetime, expires_at,
       credential_epoch, created_at, created_by, revoked_at, last_used_at,
       issuer_id, subject, audience, required_claims, reactivated_at
FROM machine_credentials
WHERE issuer_id = $1 AND subject = $2 AND revoked_at IS NULL
`

type FederatedBindingByIdentityParams struct {
	IssuerID pgtype.Text
	Subject  pgtype.Text
}

type FederatedBindingByIdentityRow struct {
	ID               string
	ServiceAccountID string
	Kind             string
	PrefixHint       pgtype.Text
	Lifetime         string
	ExpiresAt        pgtype.Timestamptz
	CredentialEpoch  int64
	CreatedAt        pgtype.Timestamptz
	CreatedBy        string
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	IssuerID         pgtype.Text
	Subject          pgtype.Text
	Audience         pgtype.Text
	RequiredClaims   pgtype.Text
	ReactivatedAt    pgtype.Timestamptz
}

// Federated authentication's single indexed read, over the live-row partial
// unique index; see the sqlite dialect.
// hikyo:authn-resolution
func (q *Queries) FederatedBindingByIdentity(ctx context.Context, arg FederatedBindingByIdentityParams) (FederatedBindingByIdentityRow, error) {
	row := q.db.QueryRow(ctx, federatedBindingByIdentity, arg.IssuerID, arg.Subject)
	var i FederatedBindingByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.Kind,
		&i.PrefixHint,
		&i.Lifetime,
		&i.ExpiresAt,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.IssuerID,
		&i.Subject,
		&i.Audience,
		&i.RequiredClaims,
		&i.ReactivatedAt,
	)
	return i, err
}

const federationIssuerByID = `-- name: FederationIssuerByID :one
SELECT id, issuer, issuer_type, jwks_mode, static_jwks, refused_audiences,
       created_at, created_by, updated_at, updated_by
FROM federation_issuers
WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) FederationIssuerByID(ctx context.Context, id string) (FederationIssuer, error) {
	row := q.db.QueryRow(ctx, federationIssuerByID, id)
	var i FederationIssuer
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.IssuerType,
		&i.JwksMode,
		&i.StaticJwks,
		&i.RefusedAudiences,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const federationIssuerByIssuer = `-- name: FederationIssuerByIssuer :one
SELECT id, issuer, issuer_type, jwks_mode, static_jwks, refused_audiences,
       created_at, created_by, updated_at, updated_by
FROM federation_issuers
WHERE issuer = $1
`

// The BYTE-EXACT issuer lookup; see the sqlite dialect for why nothing folds.
// hikyo:authn-resolution
func (q *Queries) FederationIssuerByIssuer(ctx context.Context, issuer string) (FederationIssuer, error) {
	row := q.db.QueryRow(ctx, federationIssuerByIssuer, issuer)
	var i FederationIssuer
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.IssuerType,
		&i.JwksMode,
		&i.StaticJwks,
		&i.RefusedAudiences,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getPinGeneration = `-- name: GetPinGeneration :one
SELECT generation FROM pin_generations
WHERE principal_id = $1 AND environment_id = $2
`

type GetPinGenerationParams struct {
	PrincipalID   string
	EnvironmentID string
}

// hikyo:authn-resolution
func (q *Queries) GetPinGeneration(ctx context.Context, arg GetPinGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPinGeneration, arg.PrincipalID, arg.EnvironmentID)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const insertFederationIssuer = `-- name: InsertFederationIssuer :exec

INSERT INTO federation_issuers (
    id, issuer, issuer_type, jwks_mode, static_jwks, refused_audiences,
    created_at, created_by, updated_at, updated_by
) VALUES ($1, $2, $3, $4,
          $5, $6,
          $7, $8, NULL, NULL)
`

type InsertFederationIssuerParams struct {
	ID               string
	Issuer           string
	IssuerType       string
	JwksMode         string
	StaticJwks       pgtype.Text
	RefusedAudiences string
	CreatedAt        pgtype.Timestamptz
	CreatedBy        string
}

// OIDC federation (#62). Structurally identical to the sqlite dialect; see
// that file for the reasoning behind every statement here.
// hikyo:authn-resolution
func (q *Queries) InsertFederationIssuer(ctx context.Context, arg InsertFederationIssuerParams) error {
	_, err := q.db.Exec(ctx, insertFederationIssuer,
		arg.ID,
		arg.Issuer,
		arg.IssuerType,
		arg.JwksMode,
		arg.StaticJwks,
		arg.RefusedAudiences,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const listFederationIssuers = `-- name: ListFederationIssuers :many
SELECT id, issuer, issuer_type, jwks_mode, static_jwks, refused_audiences,
       created_at, created_by, updated_at, updated_by
FROM federation_issuers
ORDER BY issuer
`

// hikyo:authn-resolution
func (q *Queries) ListFederationIssuers(ctx context.Context) ([]FederationIssuer, error) {
	rows, err := q.db.Query(ctx, listFederationIssuers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationIssuer
	for rows.Next() {
		var i FederationIssuer
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.IssuerType,
			&i.JwksMode,
			&i.StaticJwks,
			&i.RefusedAudiences,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateFederatedBinding = `-- name: ReactivateFederatedBinding :execrows
UPDATE machine_credentials SET reactivated_at = $1
WHERE id = $2 AND kind = 'oidc-federation'
`

type ReactivateFederatedBindingParams struct {
	ReactivatedAt pgtype.Timestamptz
	ID            string
}

// The restore predicate's writer (section Restore); see the sqlite dialect.
// hikyo:authn-resolution
func (q *Queries) ReactivateFederatedBinding(ctx context.Context, arg ReactivateFederatedBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateFederatedBinding, arg.ReactivatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPinGeneration = `-- name: SetPinGeneration :exec
INSERT INTO pin_generations (principal_id, environment_id, generation)
VALUES ($1, $2, $3)
ON CONFLICT (principal_id, environment_id) DO UPDATE SET generation = excluded.generation
`

type SetPinGenerationParams struct {
	PrincipalID   string
	EnvironmentID string
	Generation    int64
}

// hikyo:authn-resolution
func (q *Queries) SetPinGeneration(ctx context.Context, arg SetPinGenerationParams) error {
	_, err := q.db.Exec(ctx, setPinGeneration, arg.PrincipalID, arg.EnvironmentID, arg.Generation)
	return err
}

const updateFederationIssuer = `-- name: UpdateFederationIssuer :execrows
UPDATE federation_issuers
SET jwks_mode = $1, static_jwks = $2,
    refused_audiences = $3,
    updated_at = $4, updated_by = $5
WHERE id = $6
`

type UpdateFederationIssuerParams struct {
	JwksMode         string
	StaticJwks       pgtype.Text
	RefusedAudiences string
	UpdatedAt        pgtype.Timestamptz
	UpdatedBy        pgtype.Text
	ID               string
}

// The issuer's configuration is mutable; its identity is not.
// hikyo:authn-resolution
func (q *Queries) UpdateFederationIssuer(ctx context.Context, arg UpdateFederationIssuerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFederationIssuer,
		arg.JwksMode,
		arg.StaticJwks,
		arg.RefusedAudiences,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
