// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pki_repository.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pKIActiveIssuer = `-- name: PKIActiveIssuer :one
SELECT id,name,version,kind,origin,COALESCE(parent_id,'') AS parent_id,state,key_algorithm,key_fingerprint,CAST(CASE WHEN encrypted_private_key IS NULL THEN 0 ELSE 1 END AS INTEGER) AS key_present,certificate_der,csr_der,chain_pem,subject_cn,subject_org,not_before,not_after,crl_distribution_url,restore_hold,issued_count,crl_der,crl_number,revocation_seq,crl_this_update,crl_next_update,row_version,created_by,created_at,updated_at FROM pki_issuers WHERE name=$1 AND state='active'
`

type PKIActiveIssuerRow struct {
	ID                 string
	Name               string
	Version            int32
	Kind               string
	Origin             string
	ParentID           string
	State              string
	KeyAlgorithm       string
	KeyFingerprint     string
	KeyPresent         int32
	CertificateDer     []byte
	CsrDer             []byte
	ChainPem           string
	SubjectCn          string
	SubjectOrg         string
	NotBefore          pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	CrlDistributionUrl string
	RestoreHold        int32
	IssuedCount        int64
	CrlDer             []byte
	CrlNumber          int64
	RevocationSeq      int64
	CrlThisUpdate      pgtype.Timestamptz
	CrlNextUpdate      pgtype.Timestamptz
	RowVersion         int64
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// hikyo:reason StorePKIIssuersActivePublic permits the existing instance-wide active CA projection for a verified environment operation; sealed keys are excluded.
// hikyo:instance-scoped
func (q *Queries) PKIActiveIssuer(ctx context.Context, name string) (PKIActiveIssuerRow, error) {
	row := q.db.QueryRow(ctx, pKIActiveIssuer, name)
	var i PKIActiveIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Kind,
		&i.Origin,
		&i.ParentID,
		&i.State,
		&i.KeyAlgorithm,
		&i.KeyFingerprint,
		&i.KeyPresent,
		&i.CertificateDer,
		&i.CsrDer,
		&i.ChainPem,
		&i.SubjectCn,
		&i.SubjectOrg,
		&i.NotBefore,
		&i.NotAfter,
		&i.CrlDistributionUrl,
		&i.RestoreHold,
		&i.IssuedCount,
		&i.CrlDer,
		&i.CrlNumber,
		&i.RevocationSeq,
		&i.CrlThisUpdate,
		&i.CrlNextUpdate,
		&i.RowVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKIBoundProfile = `-- name: PKIBoundProfile :one
SELECT id,name,policy,row_version,created_by,created_at,updated_at FROM pki_profiles WHERE name=$1 AND id IN (SELECT profile_id FROM pki_profile_bindings WHERE org_id=$2 AND project_id=$3 AND (environment_id IS NULL OR environment_id=$4))
`

type PKIBoundProfileParams struct {
	Name         string
	ChainOrg     string
	ChainProject string
	ChainEnv     pgtype.Text
}

func (q *Queries) PKIBoundProfile(ctx context.Context, arg PKIBoundProfileParams) (PkiProfile, error) {
	row := q.db.QueryRow(ctx, pKIBoundProfile,
		arg.Name,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i PkiProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Policy,
		&i.RowVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKIBoundProfiles = `-- name: PKIBoundProfiles :many
SELECT id,name,policy,row_version,created_by,created_at,updated_at FROM pki_profiles WHERE id IN (SELECT profile_id FROM pki_profile_bindings WHERE org_id=$1 AND project_id=$2 AND (environment_id IS NULL OR environment_id=$3)) ORDER BY name
`

type PKIBoundProfilesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     pgtype.Text
}

func (q *Queries) PKIBoundProfiles(ctx context.Context, arg PKIBoundProfilesParams) ([]PkiProfile, error) {
	rows, err := q.db.Query(ctx, pKIBoundProfiles, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PkiProfile
	for rows.Next() {
		var i PkiProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Policy,
			&i.RowVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIBumpCertificateRevocation = `-- name: PKIBumpCertificateRevocation :exec
UPDATE pki_issuers SET revocation_seq=revocation_seq+1 WHERE id=(SELECT c.issuer_id FROM pki_certificates c WHERE c.id=$1)
`

// hikyo:reason Called only after a proof-scoped certificate revoke CAS or closed PKIRuntime unknown-state CAS succeeds in the same transaction; bumps that certificate issuer CRL sequence.
// hikyo:instance-scoped
func (q *Queries) PKIBumpCertificateRevocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, pKIBumpCertificateRevocation, id)
	return err
}

const pKIBumpIssuerRevocation = `-- name: PKIBumpIssuerRevocation :exec
UPDATE pki_issuers SET revocation_seq=revocation_seq+1 WHERE id=$1
`

// hikyo:reason Called only after successful StorePKICertificatesRevokeLive changes in the same transaction; global CA sequence forces CRL refresh for those leaves.
// hikyo:instance-scoped
func (q *Queries) PKIBumpIssuerRevocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, pKIBumpIssuerRevocation, id)
	return err
}

const pKIClaimRenewal = `-- name: PKIClaimRenewal :execrows
UPDATE pki_certificates SET renewed_by=$1,updated_at=$2,row_version=row_version+1 WHERE id=$3 AND state='issued' AND renewed_by IS NULL AND org_id=$4 AND project_id=$5 AND environment_id=$6
`

type PKIClaimRenewalParams struct {
	SuccessorID  pgtype.Text
	At           pgtype.Timestamptz
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKIClaimRenewal(ctx context.Context, arg PKIClaimRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIClaimRenewal,
		arg.SuccessorID,
		arg.At,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKICompleteRenewal = `-- name: PKICompleteRenewal :execrows
UPDATE pki_certificates SET state='renewed',updated_at=$1,row_version=row_version+1 WHERE id=$2 AND state='issued' AND renewed_by=$3 AND org_id=$4 AND project_id=$5 AND environment_id=$6
`

type PKICompleteRenewalParams struct {
	At           pgtype.Timestamptz
	ID           string
	SuccessorID  pgtype.Text
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKICompleteRenewal(ctx context.Context, arg PKICompleteRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKICompleteRenewal,
		arg.At,
		arg.ID,
		arg.SuccessorID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKICountLiveCertificates = `-- name: PKICountLiveCertificates :one
SELECT CAST((SELECT COUNT(*) FROM pki_certificates c WHERE c.issuer_id=$1 AND c.state IN ('issuing','issued','renewed','unknown','revoked') AND c.not_after>$2) + (SELECT COUNT(*) FROM pki_issuers child WHERE child.parent_id=$1 AND child.certificate_der IS NOT NULL AND child.not_after>$2) AS BIGINT) AS total
`

type PKICountLiveCertificatesParams struct {
	IssuerID string
	Now      pgtype.Timestamptz
}

// hikyo:reason StorePKICertificatesCountLive verifies instance-config authority; retiring a global CA must count all dependent unexpired tenant leaves and child CAs.
// hikyo:instance-scoped
func (q *Queries) PKICountLiveCertificates(ctx context.Context, arg PKICountLiveCertificatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, pKICountLiveCertificates, arg.IssuerID, arg.Now)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const pKICreateBinding = `-- name: PKICreateBinding :exec
INSERT INTO pki_profile_bindings (id,profile_id,org_id,project_id,environment_id,created_by,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type PKICreateBindingParams struct {
	ID            string
	ProfileID     string
	OrgID         string
	ProjectID     string
	EnvironmentID pgtype.Text
	CreatedBy     string
	At            pgtype.Timestamptz
}

// hikyo:reason StorePKIBindingsCreate verifies instance-config authority; operator explicitly names a policy reach, with existing tenant foreign-key and duplicate constraints.
// hikyo:instance-scoped
func (q *Queries) PKICreateBinding(ctx context.Context, arg PKICreateBindingParams) error {
	_, err := q.db.Exec(ctx, pKICreateBinding,
		arg.ID,
		arg.ProfileID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.CreatedBy,
		arg.At,
	)
	return err
}

const pKICreateCertificate = `-- name: PKICreateCertificate :exec
INSERT INTO pki_certificates (id,org_id,project_id,environment_id,profile_id,profile_name,issuer_id,serial,state,key_source,key_algorithm,key_fingerprint,common_name,sans,not_before,not_after,principal_id,principal_class,renewed_from,issuing_deadline,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'issuing',$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$20)
`

type PKICreateCertificateParams struct {
	ID              string
	ChainOrg        string
	ChainProject    string
	ChainEnv        string
	ProfileID       string
	ProfileName     string
	IssuerID        string
	Serial          string
	KeySource       string
	KeyAlgorithm    string
	KeyFingerprint  string
	CommonName      string
	Sans            string
	NotBefore       pgtype.Timestamptz
	NotAfter        pgtype.Timestamptz
	PrincipalID     string
	PrincipalClass  string
	RenewedFrom     pgtype.Text
	IssuingDeadline pgtype.Timestamptz
	At              pgtype.Timestamptz
}

func (q *Queries) PKICreateCertificate(ctx context.Context, arg PKICreateCertificateParams) error {
	_, err := q.db.Exec(ctx, pKICreateCertificate,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.ProfileID,
		arg.ProfileName,
		arg.IssuerID,
		arg.Serial,
		arg.KeySource,
		arg.KeyAlgorithm,
		arg.KeyFingerprint,
		arg.CommonName,
		arg.Sans,
		arg.NotBefore,
		arg.NotAfter,
		arg.PrincipalID,
		arg.PrincipalClass,
		arg.RenewedFrom,
		arg.IssuingDeadline,
		arg.At,
	)
	return err
}

const pKICreateIssuer = `-- name: PKICreateIssuer :exec
INSERT INTO pki_issuers (id,name,version,kind,origin,parent_id,state,key_algorithm,key_fingerprint,encrypted_private_key,dek_version,certificate_der,csr_der,chain_pem,subject_cn,subject_org,not_before,not_after,crl_distribution_url,created_by,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$21)
`

type PKICreateIssuerParams struct {
	ID                  string
	Name                string
	Version             int32
	Kind                string
	Origin              string
	ParentID            pgtype.Text
	State               string
	KeyAlgorithm        string
	KeyFingerprint      string
	EncryptedPrivateKey []byte
	DekVersion          pgtype.Int8
	CertificateDer      []byte
	CsrDer              []byte
	ChainPem            string
	SubjectCn           string
	SubjectOrg          string
	NotBefore           pgtype.Timestamptz
	NotAfter            pgtype.Timestamptz
	CrlDistributionUrl  string
	CreatedBy           string
	At                  pgtype.Timestamptz
}

// hikyo:reason StorePKIIssuersCreate verifies instance-config authority before creating an instance-wide CA key version.
// hikyo:instance-scoped
func (q *Queries) PKICreateIssuer(ctx context.Context, arg PKICreateIssuerParams) error {
	_, err := q.db.Exec(ctx, pKICreateIssuer,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Kind,
		arg.Origin,
		arg.ParentID,
		arg.State,
		arg.KeyAlgorithm,
		arg.KeyFingerprint,
		arg.EncryptedPrivateKey,
		arg.DekVersion,
		arg.CertificateDer,
		arg.CsrDer,
		arg.ChainPem,
		arg.SubjectCn,
		arg.SubjectOrg,
		arg.NotBefore,
		arg.NotAfter,
		arg.CrlDistributionUrl,
		arg.CreatedBy,
		arg.At,
	)
	return err
}

const pKICreateProfile = `-- name: PKICreateProfile :exec
INSERT INTO pki_profiles (id,name,policy,created_by,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$5)
`

type PKICreateProfileParams struct {
	ID        string
	Name      string
	Policy    string
	CreatedBy string
	At        pgtype.Timestamptz
}

// hikyo:reason StorePKIProfilesCreate verifies instance-config authority before creating a global certificate policy definition.
// hikyo:instance-scoped
func (q *Queries) PKICreateProfile(ctx context.Context, arg PKICreateProfileParams) error {
	_, err := q.db.Exec(ctx, pKICreateProfile,
		arg.ID,
		arg.Name,
		arg.Policy,
		arg.CreatedBy,
		arg.At,
	)
	return err
}

const pKIDeleteBinding = `-- name: PKIDeleteBinding :execrows
DELETE FROM pki_profile_bindings WHERE id=$1 AND profile_id=$2
`

type PKIDeleteBindingParams struct {
	ID        string
	ProfileID string
}

// hikyo:reason StorePKIBindingsDelete verifies instance-config authority; operator deletes only the named binding belonging to the named global policy.
// hikyo:instance-scoped
func (q *Queries) PKIDeleteBinding(ctx context.Context, arg PKIDeleteBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIDeleteBinding, arg.ID, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIDeleteProfile = `-- name: PKIDeleteProfile :execrows
DELETE FROM pki_profiles WHERE id=$1
`

// hikyo:reason StorePKIProfilesDelete verifies instance-config authority; deletes the global policy after its bindings are removed in the same transaction.
// hikyo:instance-scoped
func (q *Queries) PKIDeleteProfile(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, pKIDeleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIDeleteProfileBindings = `-- name: PKIDeleteProfileBindings :exec
DELETE FROM pki_profile_bindings WHERE profile_id=$1
`

// hikyo:reason StorePKIProfilesDelete verifies instance-config authority; removes an operator-owned global policy reach before deleting that policy in the same transaction.
// hikyo:instance-scoped
func (q *Queries) PKIDeleteProfileBindings(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, pKIDeleteProfileBindings, id)
	return err
}

const pKIDestroyIssuerKey = `-- name: PKIDestroyIssuerKey :execrows
UPDATE pki_issuers SET state=$1,encrypted_private_key=NULL,dek_version=NULL,row_version=row_version+1,updated_at=$2 WHERE id=$3 AND state=$4 AND row_version=$5
`

type PKIDestroyIssuerKeyParams struct {
	NextState  string
	At         pgtype.Timestamptz
	ID         string
	PriorState string
	RowVersion int64
}

// hikyo:reason StorePKIIssuersDestroyKey verifies instance-config authority; terminal CA transition destroys the sealed key under state/version CAS.
// hikyo:instance-scoped
func (q *Queries) PKIDestroyIssuerKey(ctx context.Context, arg PKIDestroyIssuerKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIDestroyIssuerKey,
		arg.NextState,
		arg.At,
		arg.ID,
		arg.PriorState,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIFailCertificate = `-- name: PKIFailCertificate :execrows
UPDATE pki_certificates SET state='failed',updated_at=$1,row_version=row_version+1 WHERE id=$2 AND state='issuing' AND org_id=$3 AND project_id=$4 AND environment_id=$5
`

type PKIFailCertificateParams struct {
	At           pgtype.Timestamptz
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKIFailCertificate(ctx context.Context, arg PKIFailCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIFailCertificate,
		arg.At,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIFenceIssuance = `-- name: PKIFenceIssuance :execrows
UPDATE pki_issuers SET issued_count=issued_count+1 WHERE id=$1 AND state='active' AND restore_hold=0
`

// hikyo:reason StorePKIIssuersFence verifies issuance authority; writes the global CA counter only while active and not held, preserving the cross-node signing fence.
// hikyo:instance-scoped
func (q *Queries) PKIFenceIssuance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, pKIFenceIssuance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIFinishCertificate = `-- name: PKIFinishCertificate :execrows
UPDATE pki_certificates SET state='issued',certificate_der=$1,updated_at=$2,row_version=row_version+1 WHERE id=$3 AND state='issuing' AND org_id=$4 AND project_id=$5 AND environment_id=$6
`

type PKIFinishCertificateParams struct {
	Der          []byte
	At           pgtype.Timestamptz
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKIFinishCertificate(ctx context.Context, arg PKIFinishCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIFinishCertificate,
		arg.Der,
		arg.At,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIGetCertificate = `-- name: PKIGetCertificate :one
SELECT id,environment_id,profile_id,profile_name,issuer_id,serial,state,key_source,key_algorithm,key_fingerprint,common_name,sans,not_before,not_after,certificate_der,principal_id,principal_class,COALESCE(renewed_from,'') AS renewed_from,COALESCE(renewed_by,'') AS renewed_by,revoked_at,COALESCE(revocation_reason,'') AS revocation_reason,issuing_deadline,row_version,created_at,updated_at FROM pki_certificates WHERE id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4
`

type PKIGetCertificateParams struct {
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type PKIGetCertificateRow struct {
	ID               string
	EnvironmentID    string
	ProfileID        string
	ProfileName      string
	IssuerID         string
	Serial           string
	State            string
	KeySource        string
	KeyAlgorithm     string
	KeyFingerprint   string
	CommonName       string
	Sans             string
	NotBefore        pgtype.Timestamptz
	NotAfter         pgtype.Timestamptz
	CertificateDer   []byte
	PrincipalID      string
	PrincipalClass   string
	RenewedFrom      string
	RenewedBy        string
	RevokedAt        pgtype.Timestamptz
	RevocationReason string
	IssuingDeadline  pgtype.Timestamptz
	RowVersion       int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) PKIGetCertificate(ctx context.Context, arg PKIGetCertificateParams) (PKIGetCertificateRow, error) {
	row := q.db.QueryRow(ctx, pKIGetCertificate,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i PKIGetCertificateRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProfileID,
		&i.ProfileName,
		&i.IssuerID,
		&i.Serial,
		&i.State,
		&i.KeySource,
		&i.KeyAlgorithm,
		&i.KeyFingerprint,
		&i.CommonName,
		&i.Sans,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertificateDer,
		&i.PrincipalID,
		&i.PrincipalClass,
		&i.RenewedFrom,
		&i.RenewedBy,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.IssuingDeadline,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKIGetIssuer = `-- name: PKIGetIssuer :one
SELECT id,name,version,kind,origin,COALESCE(parent_id,'') AS parent_id,state,key_algorithm,key_fingerprint,CAST(CASE WHEN encrypted_private_key IS NULL THEN 0 ELSE 1 END AS INTEGER) AS key_present,certificate_der,csr_der,chain_pem,subject_cn,subject_org,not_before,not_after,crl_distribution_url,restore_hold,issued_count,crl_der,crl_number,revocation_seq,crl_this_update,crl_next_update,row_version,created_by,created_at,updated_at FROM pki_issuers WHERE id=$1
`

type PKIGetIssuerRow struct {
	ID                 string
	Name               string
	Version            int32
	Kind               string
	Origin             string
	ParentID           string
	State              string
	KeyAlgorithm       string
	KeyFingerprint     string
	KeyPresent         int32
	CertificateDer     []byte
	CsrDer             []byte
	ChainPem           string
	SubjectCn          string
	SubjectOrg         string
	NotBefore          pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	CrlDistributionUrl string
	RestoreHold        int32
	IssuedCount        int64
	CrlDer             []byte
	CrlNumber          int64
	RevocationSeq      int64
	CrlThisUpdate      pgtype.Timestamptz
	CrlNextUpdate      pgtype.Timestamptz
	RowVersion         int64
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// hikyo:reason StorePKIIssuersGet verifies instance-config, or StorePKIIssuersPublic permits the existing global public CA projection; this query excludes sealed keys.
// hikyo:instance-scoped
func (q *Queries) PKIGetIssuer(ctx context.Context, id string) (PKIGetIssuerRow, error) {
	row := q.db.QueryRow(ctx, pKIGetIssuer, id)
	var i PKIGetIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Kind,
		&i.Origin,
		&i.ParentID,
		&i.State,
		&i.KeyAlgorithm,
		&i.KeyFingerprint,
		&i.KeyPresent,
		&i.CertificateDer,
		&i.CsrDer,
		&i.ChainPem,
		&i.SubjectCn,
		&i.SubjectOrg,
		&i.NotBefore,
		&i.NotAfter,
		&i.CrlDistributionUrl,
		&i.RestoreHold,
		&i.IssuedCount,
		&i.CrlDer,
		&i.CrlNumber,
		&i.RevocationSeq,
		&i.CrlThisUpdate,
		&i.CrlNextUpdate,
		&i.RowVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKIGetProfile = `-- name: PKIGetProfile :one
SELECT id,name,policy,row_version,created_by,created_at,updated_at FROM pki_profiles WHERE name=$1
`

// hikyo:reason StorePKIProfilesGet verifies instance-config authority; resolves an instance-wide policy definition by name.
// hikyo:instance-scoped
func (q *Queries) PKIGetProfile(ctx context.Context, name string) (PkiProfile, error) {
	row := q.db.QueryRow(ctx, pKIGetProfile, name)
	var i PkiProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Policy,
		&i.RowVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKIInstallIssuer = `-- name: PKIInstallIssuer :execrows
UPDATE pki_issuers SET state='active',certificate_der=$1,chain_pem=$2,not_before=$3,not_after=$4,row_version=row_version+1,updated_at=$5 WHERE id=$6 AND state='pending' AND row_version=$7
`

type PKIInstallIssuerParams struct {
	CertificateDer []byte
	ChainPem       string
	NotBefore      pgtype.Timestamptz
	NotAfter       pgtype.Timestamptz
	At             pgtype.Timestamptz
	ID             string
	RowVersion     int64
}

// hikyo:reason StorePKIIssuersInstall verifies instance-config authority; pending CA activation retains the original state and row-version CAS.
// hikyo:instance-scoped
func (q *Queries) PKIInstallIssuer(ctx context.Context, arg PKIInstallIssuerParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIInstallIssuer,
		arg.CertificateDer,
		arg.ChainPem,
		arg.NotBefore,
		arg.NotAfter,
		arg.At,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIIssuerKey = `-- name: PKIIssuerKey :one
SELECT encrypted_private_key,dek_version FROM pki_issuers WHERE id=$1 AND encrypted_private_key IS NOT NULL AND dek_version IS NOT NULL
`

type PKIIssuerKeyRow struct {
	EncryptedPrivateKey []byte
	DekVersion          pgtype.Int8
}

// hikyo:reason StorePKIIssuersKey or StorePKIIssuersSigning verifies the closed in-process signer capability before reading sealed CA key material.
// hikyo:instance-scoped
func (q *Queries) PKIIssuerKey(ctx context.Context, id string) (PKIIssuerKeyRow, error) {
	row := q.db.QueryRow(ctx, pKIIssuerKey, id)
	var i PKIIssuerKeyRow
	err := row.Scan(&i.EncryptedPrivateKey, &i.DekVersion)
	return i, err
}

const pKIListBindings = `-- name: PKIListBindings :many
SELECT id,profile_id,org_id,project_id,COALESCE(environment_id,'') AS environment_id,created_by,created_at FROM pki_profile_bindings WHERE profile_id=$1 ORDER BY org_id,project_id,environment_id
`

type PKIListBindingsRow struct {
	ID            string
	ProfileID     string
	OrgID         string
	ProjectID     string
	EnvironmentID string
	CreatedBy     string
	CreatedAt     pgtype.Timestamptz
}

// hikyo:reason StorePKIBindingsList verifies instance-config authority; operator reads explicit tenant reaches of one global policy.
// hikyo:instance-scoped
func (q *Queries) PKIListBindings(ctx context.Context, profileID string) ([]PKIListBindingsRow, error) {
	rows, err := q.db.Query(ctx, pKIListBindings, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PKIListBindingsRow
	for rows.Next() {
		var i PKIListBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIListCertificates = `-- name: PKIListCertificates :many
SELECT id,environment_id,profile_id,profile_name,issuer_id,serial,state,key_source,key_algorithm,key_fingerprint,common_name,sans,not_before,not_after,certificate_der,principal_id,principal_class,COALESCE(renewed_from,'') AS renewed_from,COALESCE(renewed_by,'') AS renewed_by,revoked_at,COALESCE(revocation_reason,'') AS revocation_reason,issuing_deadline,row_version,created_at,updated_at FROM pki_certificates WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY created_at DESC,id DESC LIMIT 500
`

type PKIListCertificatesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type PKIListCertificatesRow struct {
	ID               string
	EnvironmentID    string
	ProfileID        string
	ProfileName      string
	IssuerID         string
	Serial           string
	State            string
	KeySource        string
	KeyAlgorithm     string
	KeyFingerprint   string
	CommonName       string
	Sans             string
	NotBefore        pgtype.Timestamptz
	NotAfter         pgtype.Timestamptz
	CertificateDer   []byte
	PrincipalID      string
	PrincipalClass   string
	RenewedFrom      string
	RenewedBy        string
	RevokedAt        pgtype.Timestamptz
	RevocationReason string
	IssuingDeadline  pgtype.Timestamptz
	RowVersion       int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) PKIListCertificates(ctx context.Context, arg PKIListCertificatesParams) ([]PKIListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, pKIListCertificates, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PKIListCertificatesRow
	for rows.Next() {
		var i PKIListCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProfileID,
			&i.ProfileName,
			&i.IssuerID,
			&i.Serial,
			&i.State,
			&i.KeySource,
			&i.KeyAlgorithm,
			&i.KeyFingerprint,
			&i.CommonName,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.CertificateDer,
			&i.PrincipalID,
			&i.PrincipalClass,
			&i.RenewedFrom,
			&i.RenewedBy,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.IssuingDeadline,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIListIssuers = `-- name: PKIListIssuers :many
SELECT id,name,version,kind,origin,COALESCE(parent_id,'') AS parent_id,state,key_algorithm,key_fingerprint,CAST(CASE WHEN encrypted_private_key IS NULL THEN 0 ELSE 1 END AS INTEGER) AS key_present,certificate_der,csr_der,chain_pem,subject_cn,subject_org,not_before,not_after,crl_distribution_url,restore_hold,issued_count,crl_der,crl_number,revocation_seq,crl_this_update,crl_next_update,row_version,created_by,created_at,updated_at FROM pki_issuers ORDER BY name,version
`

type PKIListIssuersRow struct {
	ID                 string
	Name               string
	Version            int32
	Kind               string
	Origin             string
	ParentID           string
	State              string
	KeyAlgorithm       string
	KeyFingerprint     string
	KeyPresent         int32
	CertificateDer     []byte
	CsrDer             []byte
	ChainPem           string
	SubjectCn          string
	SubjectOrg         string
	NotBefore          pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	CrlDistributionUrl string
	RestoreHold        int32
	IssuedCount        int64
	CrlDer             []byte
	CrlNumber          int64
	RevocationSeq      int64
	CrlThisUpdate      pgtype.Timestamptz
	CrlNextUpdate      pgtype.Timestamptz
	RowVersion         int64
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// hikyo:reason StorePKIIssuersList verifies instance-config authority; CA issuer versions are instance-wide public metadata ordered by name/version.
// hikyo:instance-scoped
func (q *Queries) PKIListIssuers(ctx context.Context) ([]PKIListIssuersRow, error) {
	rows, err := q.db.Query(ctx, pKIListIssuers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PKIListIssuersRow
	for rows.Next() {
		var i PKIListIssuersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Kind,
			&i.Origin,
			&i.ParentID,
			&i.State,
			&i.KeyAlgorithm,
			&i.KeyFingerprint,
			&i.KeyPresent,
			&i.CertificateDer,
			&i.CsrDer,
			&i.ChainPem,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.NotBefore,
			&i.NotAfter,
			&i.CrlDistributionUrl,
			&i.RestoreHold,
			&i.IssuedCount,
			&i.CrlDer,
			&i.CrlNumber,
			&i.RevocationSeq,
			&i.CrlThisUpdate,
			&i.CrlNextUpdate,
			&i.RowVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIListProfiles = `-- name: PKIListProfiles :many
SELECT id,name,policy,row_version,created_by,created_at,updated_at FROM pki_profiles ORDER BY name
`

// hikyo:reason StorePKIProfilesList verifies instance-config authority; certificate policy definitions are instance-wide and contain no tenant certificate rows.
// hikyo:instance-scoped
func (q *Queries) PKIListProfiles(ctx context.Context) ([]PkiProfile, error) {
	rows, err := q.db.Query(ctx, pKIListProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PkiProfile
	for rows.Next() {
		var i PkiProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Policy,
			&i.RowVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIPublishCRL = `-- name: PKIPublishCRL :execrows
UPDATE pki_issuers SET crl_der=$1,crl_number=$2,crl_revocation_seq=$3,crl_this_update=$4,crl_next_update=$5 WHERE id=$6 AND crl_number=$7 AND state IN ('active','retiring')
`

type PKIPublishCRLParams struct {
	Der            []byte
	Number         int64
	RevocationSeq  int64
	ThisUpdate     pgtype.Timestamptz
	NextUpdate     pgtype.Timestamptz
	ID             string
	PreviousNumber int64
}

// hikyo:reason StorePKIIssuersPublishCRL verifies instance-config, or closed PKIRuntime publishes a signed global CA CRL; original active/retiring state and prior-number CAS remain.
// hikyo:instance-scoped
func (q *Queries) PKIPublishCRL(ctx context.Context, arg PKIPublishCRLParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIPublishCRL,
		arg.Der,
		arg.Number,
		arg.RevocationSeq,
		arg.ThisUpdate,
		arg.NextUpdate,
		arg.ID,
		arg.PreviousNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIReleaseRenewal = `-- name: PKIReleaseRenewal :execrows
UPDATE pki_certificates SET renewed_by=NULL,updated_at=$1,row_version=row_version+1 WHERE id=$2 AND renewed_by=$3 AND org_id=$4 AND project_id=$5 AND environment_id=$6
`

type PKIReleaseRenewalParams struct {
	At           pgtype.Timestamptz
	ID           string
	SuccessorID  pgtype.Text
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKIReleaseRenewal(ctx context.Context, arg PKIReleaseRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIReleaseRenewal,
		arg.At,
		arg.ID,
		arg.SuccessorID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIRevokeCertificate = `-- name: PKIRevokeCertificate :execrows
UPDATE pki_certificates SET state='revoked',revoked_at=$1,revocation_reason=$2,updated_at=$1,row_version=row_version+1 WHERE id=$3 AND state IN ('issued','renewed','unknown') AND org_id=$4 AND project_id=$5 AND environment_id=$6
`

type PKIRevokeCertificateParams struct {
	At           pgtype.Timestamptz
	Reason       pgtype.Text
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) PKIRevokeCertificate(ctx context.Context, arg PKIRevokeCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIRevokeCertificate,
		arg.At,
		arg.Reason,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIRevokeLiveCertificates = `-- name: PKIRevokeLiveCertificates :execrows
UPDATE pki_certificates SET state='revoked',revoked_at=$1,revocation_reason=$2,row_version=row_version+1,updated_at=$1 WHERE issuer_id=$3 AND state IN ('issuing','issued','renewed','unknown')
`

type PKIRevokeLiveCertificatesParams struct {
	At       pgtype.Timestamptz
	Reason   pgtype.Text
	IssuerID string
}

// hikyo:reason StorePKICertificatesRevokeLive verifies instance-config authority; compromised global CA revocation must cover all dependent tenant leaves.
// hikyo:instance-scoped
func (q *Queries) PKIRevokeLiveCertificates(ctx context.Context, arg PKIRevokeLiveCertificatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIRevokeLiveCertificates, arg.At, arg.Reason, arg.IssuerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIRevokeParent = `-- name: PKIRevokeParent :exec
UPDATE pki_issuers SET revocation_seq=revocation_seq+1 WHERE id=(SELECT child.parent_id FROM pki_issuers child WHERE child.id=$1 AND child.certificate_der IS NOT NULL) AND state IN ('active','retiring')
`

// hikyo:reason Called only after successful StorePKIIssuersDestroyKey revocation CAS in the same transaction; the global parent CA revocation sequence covers the revoked child.
// hikyo:instance-scoped
func (q *Queries) PKIRevokeParent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, pKIRevokeParent, id)
	return err
}

const pKIRevokedChildren = `-- name: PKIRevokedChildren :many
SELECT certificate_der,updated_at FROM pki_issuers WHERE parent_id=$1 AND state='revoked' AND certificate_der IS NOT NULL AND not_after>$2 ORDER BY id
`

type PKIRevokedChildrenParams struct {
	IssuerID pgtype.Text
	Now      pgtype.Timestamptz
}

type PKIRevokedChildrenRow struct {
	CertificateDer []byte
	UpdatedAt      pgtype.Timestamptz
}

// hikyo:reason Same verified instance-config or closed PKIRuntime CRL assembly authority; a global parent CRL must include revoked child CA certificates.
// hikyo:instance-scoped
func (q *Queries) PKIRevokedChildren(ctx context.Context, arg PKIRevokedChildrenParams) ([]PKIRevokedChildrenRow, error) {
	rows, err := q.db.Query(ctx, pKIRevokedChildren, arg.IssuerID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PKIRevokedChildrenRow
	for rows.Next() {
		var i PKIRevokedChildrenRow
		if err := rows.Scan(&i.CertificateDer, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKIRevokedEntries = `-- name: PKIRevokedEntries :many
SELECT serial,COALESCE(revoked_at,updated_at) AS revoked_at,COALESCE(revocation_reason,'unspecified') AS reason FROM pki_certificates WHERE issuer_id=$1 AND state IN ('revoked','unknown') AND not_after>$2 ORDER BY serial
`

type PKIRevokedEntriesParams struct {
	IssuerID string
	Now      pgtype.Timestamptz
}

type PKIRevokedEntriesRow struct {
	Serial    string
	RevokedAt pgtype.Timestamptz
	Reason    string
}

// hikyo:reason StorePKICertificatesRevokedEntries verifies instance-config, or closed PKIRuntime CRL assembly reads all unexpired revoked/unknown leaves for one global CA.
// hikyo:instance-scoped
func (q *Queries) PKIRevokedEntries(ctx context.Context, arg PKIRevokedEntriesParams) ([]PKIRevokedEntriesRow, error) {
	rows, err := q.db.Query(ctx, pKIRevokedEntries, arg.IssuerID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PKIRevokedEntriesRow
	for rows.Next() {
		var i PKIRevokedEntriesRow
		if err := rows.Scan(&i.Serial, &i.RevokedAt, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pKISetIssuerHold = `-- name: PKISetIssuerHold :execrows
UPDATE pki_issuers SET restore_hold=$1,row_version=row_version+1,updated_at=$2 WHERE id=$3 AND row_version=$4
`

type PKISetIssuerHoldParams struct {
	Hold       int32
	At         pgtype.Timestamptz
	ID         string
	RowVersion int64
}

// hikyo:reason StorePKIIssuersHold verifies instance-config authority; global CA restore hold requires the original row-version CAS.
// hikyo:instance-scoped
func (q *Queries) PKISetIssuerHold(ctx context.Context, arg PKISetIssuerHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKISetIssuerHold,
		arg.Hold,
		arg.At,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKISigningIssuer = `-- name: PKISigningIssuer :one
SELECT id,name,version,kind,origin,COALESCE(parent_id,'') AS parent_id,state,key_algorithm,key_fingerprint,CAST(CASE WHEN encrypted_private_key IS NULL THEN 0 ELSE 1 END AS INTEGER) AS key_present,certificate_der,csr_der,chain_pem,subject_cn,subject_org,not_before,not_after,crl_distribution_url,restore_hold,issued_count,crl_der,crl_number,revocation_seq,crl_this_update,crl_next_update,row_version,created_by,created_at,updated_at FROM pki_issuers WHERE id=$1 AND state='active'
`

type PKISigningIssuerRow struct {
	ID                 string
	Name               string
	Version            int32
	Kind               string
	Origin             string
	ParentID           string
	State              string
	KeyAlgorithm       string
	KeyFingerprint     string
	KeyPresent         int32
	CertificateDer     []byte
	CsrDer             []byte
	ChainPem           string
	SubjectCn          string
	SubjectOrg         string
	NotBefore          pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	CrlDistributionUrl string
	RestoreHold        int32
	IssuedCount        int64
	CrlDer             []byte
	CrlNumber          int64
	RevocationSeq      int64
	CrlThisUpdate      pgtype.Timestamptz
	CrlNextUpdate      pgtype.Timestamptz
	RowVersion         int64
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// hikyo:reason StorePKIIssuersSigning verifies signing authority before reading the active global CA public row; issuer fencing remains required before issuance.
// hikyo:instance-scoped
func (q *Queries) PKISigningIssuer(ctx context.Context, id string) (PKISigningIssuerRow, error) {
	row := q.db.QueryRow(ctx, pKISigningIssuer, id)
	var i PKISigningIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Kind,
		&i.Origin,
		&i.ParentID,
		&i.State,
		&i.KeyAlgorithm,
		&i.KeyFingerprint,
		&i.KeyPresent,
		&i.CertificateDer,
		&i.CsrDer,
		&i.ChainPem,
		&i.SubjectCn,
		&i.SubjectOrg,
		&i.NotBefore,
		&i.NotAfter,
		&i.CrlDistributionUrl,
		&i.RestoreHold,
		&i.IssuedCount,
		&i.CrlDer,
		&i.CrlNumber,
		&i.RevocationSeq,
		&i.CrlThisUpdate,
		&i.CrlNextUpdate,
		&i.RowVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pKITransitionIssuer = `-- name: PKITransitionIssuer :execrows
UPDATE pki_issuers SET state=$1,row_version=row_version+1,updated_at=$2 WHERE id=$3 AND state=$4 AND row_version=$5
`

type PKITransitionIssuerParams struct {
	NextState  string
	At         pgtype.Timestamptz
	ID         string
	PriorState string
	RowVersion int64
}

// hikyo:reason StorePKIIssuersTransition verifies instance-config authority; global CA transition requires prior state and row-version CAS.
// hikyo:instance-scoped
func (q *Queries) PKITransitionIssuer(ctx context.Context, arg PKITransitionIssuerParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKITransitionIssuer,
		arg.NextState,
		arg.At,
		arg.ID,
		arg.PriorState,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pKIUpdateProfile = `-- name: PKIUpdateProfile :execrows
UPDATE pki_profiles SET policy=$1,row_version=row_version+1,updated_at=$2 WHERE id=$3 AND row_version=$4
`

type PKIUpdateProfileParams struct {
	Policy     string
	At         pgtype.Timestamptz
	ID         string
	RowVersion int64
}

// hikyo:reason StorePKIProfilesUpdate verifies instance-config authority; global policy update retains its row-version CAS and service narrowing checks.
// hikyo:instance-scoped
func (q *Queries) PKIUpdateProfile(ctx context.Context, arg PKIUpdateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, pKIUpdateProfile,
		arg.Policy,
		arg.At,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
