// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountProfile = `-- name: GetAccountProfile :one
SELECT username, display_name, email, EXISTS(SELECT 1 FROM scim_users WHERE scim_users.account_id = accounts.id) AS managed, EXISTS(SELECT 1 FROM password_credentials WHERE password_credentials.account_id = accounts.id) AS has_password, EXISTS(SELECT 1 FROM totp_credentials WHERE totp_credentials.account_id = accounts.id AND confirmed_at IS NOT NULL) AS has_totp FROM accounts WHERE accounts.id = $1
`

type GetAccountProfileRow struct {
	Username    string
	DisplayName string
	Email       pgtype.Text
	Managed     bool
	HasPassword bool
	HasTotp     bool
}

// The authenticated account owns these fields. SCIM ownership is only a boolean
// projection, never disclosure of another organisation's provisioning data.
// hikyo:authn-resolution
func (q *Queries) GetAccountProfile(ctx context.Context, accountID string) (GetAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, accountID)
	var i GetAccountProfileRow
	err := row.Scan(
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Managed,
		&i.HasPassword,
		&i.HasTotp,
	)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :exec
UPDATE accounts SET username = $1, display_name = $2 WHERE id = $3
`

type UpdateAccountProfileParams struct {
	Username    string
	DisplayName string
	AccountID   string
}

// hikyo:authn-resolution
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) error {
	_, err := q.db.Exec(ctx, updateAccountProfile, arg.Username, arg.DisplayName, arg.AccountID)
	return err
}
