// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec

INSERT INTO projects (id, org_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateProjectParams struct {
	ID         string
	ChainOrgID string
	Name       string
	CreatedAt  pgtype.Timestamptz
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.ChainOrgID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE org_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	ChainOrgID     string
	ChainProjectID string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, created_at,
       retention_revision_count, retention_age_seconds, definitions_source,
       machine_reveal, machine_reveal_generation
FROM projects
WHERE org_id = $1 AND id = $2
`

type GetProjectParams struct {
	ChainOrgID     string
	ChainProjectID string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ChainOrgID, arg.ChainProjectID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionRevisionCount,
		&i.RetentionAgeSeconds,
		&i.DefinitionsSource,
		&i.MachineReveal,
		&i.MachineRevealGeneration,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT org_id, name FROM projects WHERE NOT EXISTS (SELECT 1 FROM self_config_binding b WHERE b.org_id=projects.org_id) ORDER BY org_id, name
`

type ListAllProjectsRow struct {
	OrgID string
	Name  string
}

// ListAllProjects is the multi-instance directory's cross-org enumeration
// (#71): the served listing is org/project names and counts across the whole
// instance, so it addresses no tenant and carries no chain conjunct. It is
// annotated instance-scoped for exactly the reason ListOrgs is - the read is
// cross-tenant by definition, not by omission. Only (org_id, name) is
// selected: the directory needs names and counts, and a row shape carrying
// created_at would be foreign structure nobody asked for.
// hikyo:instance-scoped
func (q *Queries) ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProjectsRow
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(&i.OrgID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, created_at,
       retention_revision_count, retention_age_seconds, definitions_source,
       machine_reveal, machine_reveal_generation
FROM projects
WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, chainOrgID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, chainOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
			&i.RetentionRevisionCount,
			&i.RetentionAgeSeconds,
			&i.DefinitionsSource,
			&i.MachineReveal,
			&i.MachineRevealGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProject = `-- name: LockProject :one
SELECT id FROM projects WHERE org_id = $1 AND id = $2 FOR UPDATE
`

type LockProjectParams struct {
	ChainOrgID     string
	ChainProjectID string
}

// LockProject takes the project row for the length of the transaction, so
// every environment-set mutation on one project serializes. It is what makes
// the environment cap and the append position race-free: two creates at cap-1
// would otherwise both read the same count and both insert. Postgres needs the
// explicit row lock; sqlite serializes writes by construction (see its copy).
func (q *Queries) LockProject(ctx context.Context, arg LockProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, lockProject, arg.ChainOrgID, arg.ChainProjectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const renameProject = `-- name: RenameProject :execrows
UPDATE projects SET name = $1
WHERE org_id = $2 AND id = $3
`

type RenameProjectParams struct {
	Name           string
	ChainOrgID     string
	ChainProjectID string
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameProject, arg.Name, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProjectDefinitionsSource = `-- name: SetProjectDefinitionsSource :execrows
UPDATE projects SET definitions_source = $1
WHERE org_id = $2 AND id = $3
`

type SetProjectDefinitionsSourceParams struct {
	DefinitionsSource string
	ChainOrgID        string
	ChainProjectID    string
}

// SetProjectDefinitionsSource flips a project between db- and git-managed
// definitions (#70). It is a project-settings write, deliberately off the
// definitions-edit path so a blocked editor cannot disable its own guard.
func (q *Queries) SetProjectDefinitionsSource(ctx context.Context, arg SetProjectDefinitionsSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectDefinitionsSource, arg.DefinitionsSource, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProjectMachineReveal = `-- name: SetProjectMachineReveal :execrows
UPDATE projects SET machine_reveal = $1, machine_reveal_generation = machine_reveal_generation + 1
WHERE org_id = $2 AND id = $3
`

type SetProjectMachineRevealParams struct {
	MachineReveal  bool
	ChainOrgID     string
	ChainProjectID string
}

// SetProjectMachineReveal flips the per-project machine-reveal opt-in (see the
// sqlite statement).
func (q *Queries) SetProjectMachineReveal(ctx context.Context, arg SetProjectMachineRevealParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectMachineReveal, arg.MachineReveal, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProjectRetention = `-- name: SetProjectRetention :execrows
UPDATE projects
SET retention_age_seconds = $1,
    retention_revision_count = $2
WHERE org_id = $3 AND id = $4
`

type SetProjectRetentionParams struct {
	RetentionAgeSeconds    pgtype.Int8
	RetentionRevisionCount pgtype.Int8
	ChainOrgID             string
	ChainProjectID         string
}

func (q *Queries) SetProjectRetention(ctx context.Context, arg SetProjectRetentionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectRetention,
		arg.RetentionAgeSeconds,
		arg.RetentionRevisionCount,
		arg.ChainOrgID,
		arg.ChainProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
