// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCProvider = `-- name: CreateOIDCProvider :exec

INSERT INTO oidc_providers
    (id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
     redirect_uri, assurance_policy, enabled, dek_version, row_version,
     created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1, $13, $14)
`

type CreateOIDCProviderParams struct {
	ID              string
	Slug            string
	DisplayName     string
	Kind            string
	Issuer          string
	ClientID        string
	ClientSecret    []byte
	Scopes          string
	RedirectUri     string
	AssurancePolicy pgtype.Text
	Enabled         int64
	DekVersion      int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// OIDC provider administration (#54, human-auth ADR - Login methods). The
// provider table is class=authn: it decides how a caller may authenticate, and
// login resolves it proof-free, so every statement touching it lives on the
// resolution surface. Provider mutations are still authorized at the chokepoint
// (OpProviderPut/Delete under instance-config) before these run; the write
// itself rides the resolution surface, like the session lifecycle.
// hikyo:authn-resolution
func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) error {
	_, err := q.db.Exec(ctx, createOIDCProvider,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Kind,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.RedirectUri,
		arg.AssurancePolicy,
		arg.Enabled,
		arg.DekVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeleteOIDCProvider(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOIDCProvider, id)
	return err
}

const getOIDCProviderBySlug = `-- name: GetOIDCProviderBySlug :one
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers WHERE slug = $1
`

// hikyo:authn-resolution
func (q *Queries) GetOIDCProviderBySlug(ctx context.Context, slug string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProviderBySlug, slug)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.RedirectUri,
		&i.AssurancePolicy,
		&i.Enabled,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const guardOIDCProviderForMint = `-- name: GuardOIDCProviderForMint :execrows
UPDATE oidc_providers SET row_version = row_version
WHERE id = $1 AND row_version = $2 AND issuer = $3 AND enabled = 1
`

type GuardOIDCProviderForMintParams struct {
	ID         string
	RowVersion int64
	Issuer     string
}

// A phase-C mint (login/link/reauth) guards the pinned provider row against a
// concurrent reconfigure: a no-op CAS that takes the row lock. 0 rows affected
// means the provider was disabled, deleted, re-issued or row_version-bumped
// since Phase A, so the mint must refuse (the A4 sweep always wins the TOCTOU).
// A matching row takes the lock, so a concurrent provider-change UPDATE
// serializes behind it (and vice-versa: whichever commits first, the other's
// guard sees the bumped row_version and fails). The no-op never bumps
// row_version, so it never spuriously fails an administrator's reconfigure CAS.
// hikyo:authn-resolution
func (q *Queries) GuardOIDCProviderForMint(ctx context.Context, arg GuardOIDCProviderForMintParams) (int64, error) {
	result, err := q.db.Exec(ctx, guardOIDCProviderForMint, arg.ID, arg.RowVersion, arg.Issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers ORDER BY slug
`

// hikyo:authn-resolution
func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcProvider
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Kind,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.RedirectUri,
			&i.AssurancePolicy,
			&i.Enabled,
			&i.DekVersion,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOIDCProviderForDelete = `-- name: LockOIDCProviderForDelete :one
SELECT id FROM oidc_providers WHERE id = $1 FOR UPDATE
`

// Locks the provider row inside the delete tx so a concurrent Phase-C mint
// guard serializes behind it. Taken BEFORE the session sweep so the sweep runs
// with the row held: a mint that already committed is caught by the sweep, and
// a mint blocked on this lock finds the row gone once the delete commits. FOR
// UPDATE, so it is a lock, not just a read.
// hikyo:authn-resolution
func (q *Queries) LockOIDCProviderForDelete(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockOIDCProviderForDelete, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateOIDCProviderCAS = `-- name: UpdateOIDCProviderCAS :execrows
UPDATE oidc_providers
SET display_name = $1, client_id = $2, client_secret = $3, scopes = $4,
    redirect_uri = $5, assurance_policy = $6, enabled = $7,
    dek_version = $8, row_version = row_version + 1, updated_at = $9
WHERE id = $10 AND row_version = $11
`

type UpdateOIDCProviderCASParams struct {
	DisplayName     string
	ClientID        string
	ClientSecret    []byte
	Scopes          string
	RedirectUri     string
	AssurancePolicy pgtype.Text
	Enabled         int64
	DekVersion      int64
	UpdatedAt       pgtype.Timestamptz
	ID              string
	RowVersion      int64
}

// The issuer is never in the SET list: it is immutable after create (A3), so a
// reconfiguration cannot silently move the identity space to a new authority.
// CAS on row_version so a concurrent reconfigure fails closed.
// hikyo:authn-resolution
func (q *Queries) UpdateOIDCProviderCAS(ctx context.Context, arg UpdateOIDCProviderCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOIDCProviderCAS,
		arg.DisplayName,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.RedirectUri,
		arg.AssurancePolicy,
		arg.Enabled,
		arg.DekVersion,
		arg.UpdatedAt,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
