// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_runtime.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const admissionSerializedLock = `-- name: AdmissionSerializedLock :exec
SELECT pg_advisory_lock($1::integer, $2::integer)
`

type AdmissionSerializedLockParams struct {
	Namespace int32
	Key       int32
}

// hikyo:reason Runtime admission takes the caller-selected installation session lock on one held connection before its serializable transaction; no tenant data is read.
// hikyo:instance-scoped
func (q *Queries) AdmissionSerializedLock(ctx context.Context, arg AdmissionSerializedLockParams) error {
	_, err := q.db.Exec(ctx, admissionSerializedLock, arg.Namespace, arg.Key)
	return err
}

const admissionSerializedUnlock = `-- name: AdmissionSerializedUnlock :one
SELECT pg_advisory_unlock($1::integer, $2::integer)::boolean
`

type AdmissionSerializedUnlockParams struct {
	Namespace int32
	Key       int32
}

// hikyo:reason Runtime admission releases that exact connection's session lock once; an unconfirmed unlock discards the owner rather than returning it to the pool.
// hikyo:instance-scoped
func (q *Queries) AdmissionSerializedUnlock(ctx context.Context, arg AdmissionSerializedUnlockParams) (bool, error) {
	row := q.db.QueryRow(ctx, admissionSerializedUnlock, arg.Namespace, arg.Key)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const auditExportSnapshotClock = `-- name: AuditExportSnapshotClock :one
SELECT clock_timestamp()::timestamptz
`

// hikyo:reason Admitted audit-export transaction captures the live database event clock under the writer gate; clock_timestamp intentionally differs from coordination now().
// hikyo:instance-scoped
func (q *Queries) AuditExportSnapshotClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, auditExportSnapshotClock)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const auditExportWriterBarrier = `-- name: AuditExportWriterBarrier :exec

SELECT pg_advisory_xact_lock(1464159830, 85)
`

// Recovery and audit-export runtime guards. Catalog-driven archive protocols
// remain separate because historical schemas do not have the current shape.
// hikyo:reason Admitted audit-export transaction takes the exclusive installation writer/pruner gate through cutoff capture or final-page completion; no tenant payload is read.
// hikyo:instance-scoped
func (q *Queries) AuditExportWriterBarrier(ctx context.Context) error {
	_, err := q.db.Exec(ctx, auditExportWriterBarrier)
	return err
}

const restoreDiagnosticsSeedOccupied = `-- name: RestoreDiagnosticsSeedOccupied :one
SELECT EXISTS (SELECT 1 FROM ops_diagnostics WHERE escrow_verified_at IS NOT NULL OR escrow_instance_id<>'' OR escrow_incarnation<>'' OR escrow_root_epoch<>0 OR last_reencrypt_success IS NOT NULL)
`

// hikyo:reason Recovery-authorized restore transaction checks only installation diagnostics against migration seed defaults under target table locks, refusing non-seed metadata before replacement.
// hikyo:instance-scoped
func (q *Queries) RestoreDiagnosticsSeedOccupied(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, restoreDiagnosticsSeedOccupied)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
