// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCollectedSnapshotEntries = `-- name: DeleteCollectedSnapshotEntries :execrows
DELETE FROM snapshot_entries
WHERE snapshot_id = $1
  AND EXISTS (
      SELECT 1 FROM snapshots
      WHERE snapshots.id = snapshot_entries.snapshot_id
        AND NOT snapshots.payload_present
  )
`

// hikyo:instance-scoped
func (q *Queries) DeleteCollectedSnapshotEntries(ctx context.Context, snapshotID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollectedSnapshotEntries, snapshotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLastPruneSuccess = `-- name: GetLastPruneSuccess :one
SELECT last_prune_success FROM retention_runtime WHERE id = 1
`

// hikyo:instance-scoped
func (q *Queries) GetLastPruneSuccess(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastPruneSuccess)
	var last_prune_success pgtype.Timestamptz
	err := row.Scan(&last_prune_success)
	return last_prune_success, err
}

const listEligibleSnapshotPayloads = `-- name: ListEligibleSnapshotPayloads :many
WITH ranked AS (
    SELECT s.id, s.org_id, s.project_id, s.environment_id, s.revision,
           s.published_at, s.payload_present,
           COALESCE(p.retention_age_seconds, o.retention_age_seconds) AS age_seconds,
           COALESCE(p.retention_revision_count, o.retention_revision_count) AS revision_count,
           CASE
               WHEN p.retention_age_seconds IS NOT NULL THEN FALSE
               ELSE o.retention_mode = 'unlimited'
           END AS is_unlimited,
           s.published_at < $1::timestamptz -
               COALESCE(p.retention_age_seconds, o.retention_age_seconds) * INTERVAL '1 second' AS age_expired,
           ROW_NUMBER() OVER (
               PARTITION BY s.org_id, s.project_id, s.environment_id
               ORDER BY s.revision DESC
           ) AS newest_rank
    FROM snapshots AS s
    JOIN projects AS p ON p.org_id = s.org_id AND p.id = s.project_id
    JOIN orgs AS o ON o.id = s.org_id
)
SELECT ranked.id, ranked.org_id, ranked.project_id, ranked.environment_id,
       ranked.revision, ranked.age_seconds, ranked.revision_count
FROM ranked
WHERE NOT ranked.is_unlimited
  AND ranked.payload_present
  AND NOT EXISTS (SELECT 1 FROM self_config_retention r WHERE r.snapshot_id = ranked.id)
  AND ranked.age_expired
  AND ranked.newest_rank > ranked.revision_count
  AND NOT EXISTS (
      SELECT 1 FROM revision_pins
      WHERE revision_pins.snapshot_id = ranked.id
        AND revision_pins.expires_at > $1::timestamptz
  )
ORDER BY ranked.org_id, ranked.project_id, ranked.environment_id, ranked.revision
LIMIT $2
`

type ListEligibleSnapshotPayloadsParams struct {
	Now        pgtype.Timestamptz
	BatchLimit int32
}

type ListEligibleSnapshotPayloadsRow struct {
	ID            string
	OrgID         string
	ProjectID     string
	EnvironmentID string
	Revision      int64
	AgeSeconds    int64
	RevisionCount int64
}

// hikyo:instance-scoped
func (q *Queries) ListEligibleSnapshotPayloads(ctx context.Context, arg ListEligibleSnapshotPayloadsParams) ([]ListEligibleSnapshotPayloadsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleSnapshotPayloads, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleSnapshotPayloadsRow
	for rows.Next() {
		var i ListEligibleSnapshotPayloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Revision,
			&i.AgeSeconds,
			&i.RevisionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSnapshotForRetentionConsequence = `-- name: LockSnapshotForRetentionConsequence :one

SELECT id FROM snapshots
WHERE org_id = $1
  AND project_id = $2
  AND environment_id = $3
  AND id = $4
FOR UPDATE
`

type LockSnapshotForRetentionConsequenceParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	SnapshotID     string
}

// Retention/GC (#53). Scheduler statements are cross-tenant by definition and
// run only under the scheduler system-proof site. Tenant policy and pin reads
// carry the ordinary proof-bound chain conjuncts.
func (q *Queries) LockSnapshotForRetentionConsequence(ctx context.Context, arg LockSnapshotForRetentionConsequenceParams) (string, error) {
	row := q.db.QueryRow(ctx, lockSnapshotForRetentionConsequence,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.SnapshotID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markSnapshotCollected = `-- name: MarkSnapshotCollected :execrows
UPDATE snapshots
SET payload_present = FALSE,
    collected_at = $1,
    collected_policy = $2
WHERE snapshots.id = $3 AND snapshots.payload_present
  AND NOT EXISTS (SELECT 1 FROM self_config_retention r WHERE r.snapshot_id = snapshots.id)
  AND NOT EXISTS (
      SELECT 1 FROM revision_pins
      WHERE revision_pins.snapshot_id = snapshots.id
        AND revision_pins.expires_at > $4::timestamptz
  )
`

type MarkSnapshotCollectedParams struct {
	CollectedAt     pgtype.Timestamptz
	CollectedPolicy string
	SnapshotID      string
	Now             pgtype.Timestamptz
}

// hikyo:instance-scoped
func (q *Queries) MarkSnapshotCollected(ctx context.Context, arg MarkSnapshotCollectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSnapshotCollected,
		arg.CollectedAt,
		arg.CollectedPolicy,
		arg.SnapshotID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLastPruneSuccess = `-- name: SetLastPruneSuccess :exec
INSERT INTO retention_runtime (id, last_prune_success)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE
SET last_prune_success = EXCLUDED.last_prune_success
`

// hikyo:instance-scoped
func (q *Queries) SetLastPruneSuccess(ctx context.Context, lastPruneSuccess pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, setLastPruneSuccess, lastPruneSuccess)
	return err
}
