// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: self_config.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitSelfConfigTarget = `-- name: CommitSelfConfigTarget :execrows
UPDATE self_config_binding SET desired_snapshot_id=$1,desired_revision=$2,generation=generation+1,suspended=FALSE,updated_at=$3
WHERE id=1 AND generation=$4
`

type CommitSelfConfigTargetParams struct {
	SnapshotID         string
	Revision           int64
	UpdatedAt          pgtype.Timestamptz
	ExpectedGeneration int64
}

// hikyo:instance-scoped
func (q *Queries) CommitSelfConfigTarget(ctx context.Context, arg CommitSelfConfigTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitSelfConfigTarget,
		arg.SnapshotID,
		arg.Revision,
		arg.UpdatedAt,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentSelfConfigJobs = `-- name: CountRecentSelfConfigJobs :one
SELECT COUNT(*) FROM self_config_jobs WHERE created_at >= $1
`

// hikyo:instance-scoped
func (q *Queries) CountRecentSelfConfigJobs(ctx context.Context, sinceAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSelfConfigJobs, sinceAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSelfConfigOpenJobs = `-- name: CountSelfConfigOpenJobs :one
SELECT COUNT(*) FROM self_config_jobs WHERE status IN ('preparing','applying','partial')
`

// hikyo:instance-scoped
func (q *Queries) CountSelfConfigOpenJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSelfConfigOpenJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSelfConfigSeedDisagreement = `-- name: CountSelfConfigSeedDisagreement :one
SELECT COUNT(*) FROM ha_nodes n LEFT JOIN self_config_seed_attestations s ON s.node_id=n.node_id
WHERE n.heartbeat_at >= $1 AND (s.node_id IS NULL OR s.heartbeat_at < $1 OR s.schema_version <> $2 OR s.fingerprint <> $3)
`

type CountSelfConfigSeedDisagreementParams struct {
	SinceAt       pgtype.Timestamptz
	SchemaVersion int64
	Fingerprint   string
}

// hikyo:instance-scoped
func (q *Queries) CountSelfConfigSeedDisagreement(ctx context.Context, arg CountSelfConfigSeedDisagreementParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSelfConfigSeedDisagreement, arg.SinceAt, arg.SchemaVersion, arg.Fingerprint)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSelfConfigBinding = `-- name: CreateSelfConfigBinding :execrows
INSERT INTO self_config_binding(id,owner_instance_id,adoption_key,adopted_by,org_id,project_id,environment_id,schema_version,generation,desired_revision,desired_snapshot_id,incarnation,suspended,created_at,updated_at)
SELECT 1,i.identity,$1,$2,s.org_id,s.project_id,s.environment_id,$3,1,s.revision,s.id,$4,FALSE,$5,$5
FROM snapshots s JOIN instance_identity i ON i.id=1
WHERE s.id=$6 AND s.org_id=$7 AND s.project_id=$8 AND s.environment_id=$9 AND i.identity=$10 AND s.payload_present
`

type CreateSelfConfigBindingParams struct {
	AdoptionKey     string
	AdoptedBy       string
	SchemaVersion   int64
	Incarnation     string
	CreatedAt       pgtype.Timestamptz
	SnapshotID      string
	OrgID           string
	ProjectID       string
	EnvironmentID   string
	OwnerInstanceID string
}

// hikyo:instance-scoped
func (q *Queries) CreateSelfConfigBinding(ctx context.Context, arg CreateSelfConfigBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSelfConfigBinding,
		arg.AdoptionKey,
		arg.AdoptedBy,
		arg.SchemaVersion,
		arg.Incarnation,
		arg.CreatedAt,
		arg.SnapshotID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.OwnerInstanceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSelfConfigNodes = `-- name: DeleteSelfConfigNodes :exec
DELETE FROM self_config_nodes
`

// hikyo:instance-scoped
func (q *Queries) DeleteSelfConfigNodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSelfConfigNodes)
	return err
}

const deleteSelfConfigRetention = `-- name: DeleteSelfConfigRetention :exec
DELETE FROM self_config_retention WHERE slot=$1
`

// hikyo:instance-scoped
func (q *Queries) DeleteSelfConfigRetention(ctx context.Context, slot string) error {
	_, err := q.db.Exec(ctx, deleteSelfConfigRetention, slot)
	return err
}

const fenceSelfConfigRestored = `-- name: FenceSelfConfigRestored :execrows
UPDATE self_config_binding SET incarnation=$1,suspended=TRUE,updated_at=$2 WHERE id=1 AND incarnation<>$1
`

type FenceSelfConfigRestoredParams struct {
	Incarnation string
	UpdatedAt   pgtype.Timestamptz
}

// hikyo:instance-scoped
func (q *Queries) FenceSelfConfigRestored(ctx context.Context, arg FenceSelfConfigRestoredParams) (int64, error) {
	result, err := q.db.Exec(ctx, fenceSelfConfigRestored, arg.Incarnation, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSelfConfigBinding = `-- name: GetSelfConfigBinding :one
SELECT id, owner_instance_id, adoption_key, adopted_by, org_id, project_id, environment_id, schema_version, generation, desired_revision, desired_snapshot_id, previous_snapshot_id, incarnation, suspended, created_at, updated_at FROM self_config_binding WHERE id = 1
`

// Every query is singleton owner-local metadata; no secret material lives here.
// hikyo:instance-scoped
func (q *Queries) GetSelfConfigBinding(ctx context.Context) (SelfConfigBinding, error) {
	row := q.db.QueryRow(ctx, getSelfConfigBinding)
	var i SelfConfigBinding
	err := row.Scan(
		&i.ID,
		&i.OwnerInstanceID,
		&i.AdoptionKey,
		&i.AdoptedBy,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SchemaVersion,
		&i.Generation,
		&i.DesiredRevision,
		&i.DesiredSnapshotID,
		&i.PreviousSnapshotID,
		&i.Incarnation,
		&i.Suspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelfConfigJob = `-- name: GetSelfConfigJob :one
SELECT id, idempotency_key, confirm_restored_credentials, principal_id, snapshot_id, revision, schema_version, expected_generation, generation, status, error_code, created_at, updated_at FROM self_config_jobs WHERE id=$1
`

// hikyo:instance-scoped
func (q *Queries) GetSelfConfigJob(ctx context.Context, id string) (SelfConfigJob, error) {
	row := q.db.QueryRow(ctx, getSelfConfigJob, id)
	var i SelfConfigJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ConfirmRestoredCredentials,
		&i.PrincipalID,
		&i.SnapshotID,
		&i.Revision,
		&i.SchemaVersion,
		&i.ExpectedGeneration,
		&i.Generation,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelfConfigJobByKey = `-- name: GetSelfConfigJobByKey :one
SELECT id, idempotency_key, confirm_restored_credentials, principal_id, snapshot_id, revision, schema_version, expected_generation, generation, status, error_code, created_at, updated_at FROM self_config_jobs WHERE idempotency_key=$1
`

// hikyo:instance-scoped
func (q *Queries) GetSelfConfigJobByKey(ctx context.Context, idempotencyKey string) (SelfConfigJob, error) {
	row := q.db.QueryRow(ctx, getSelfConfigJobByKey, idempotencyKey)
	var i SelfConfigJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ConfirmRestoredCredentials,
		&i.PrincipalID,
		&i.SnapshotID,
		&i.Revision,
		&i.SchemaVersion,
		&i.ExpectedGeneration,
		&i.Generation,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelfConfigRetentionSlot = `-- name: GetSelfConfigRetentionSlot :one
SELECT snapshot_id FROM self_config_retention WHERE slot=$1
`

// hikyo:instance-scoped
func (q *Queries) GetSelfConfigRetentionSlot(ctx context.Context, slot string) (string, error) {
	row := q.db.QueryRow(ctx, getSelfConfigRetentionSlot, slot)
	var snapshot_id string
	err := row.Scan(&snapshot_id)
	return snapshot_id, err
}

const insertSelfConfigJob = `-- name: InsertSelfConfigJob :execrows
INSERT INTO self_config_jobs(id,idempotency_key,confirm_restored_credentials,principal_id,snapshot_id,revision,schema_version,expected_generation,generation,status,created_at,updated_at)
SELECT $1,$2,$3,$4,s.id,s.revision,$5,b.generation,b.generation+1,'preparing',$6,$6
FROM self_config_binding b JOIN snapshots s ON s.org_id=b.org_id AND s.project_id=b.project_id AND s.environment_id=b.environment_id
WHERE b.id=1 AND s.id=$7 AND s.revision=$8 AND s.payload_present AND b.generation=$9 AND b.schema_version=$5
`

type InsertSelfConfigJobParams struct {
	ID                         string
	IdempotencyKey             string
	ConfirmRestoredCredentials bool
	PrincipalID                string
	SchemaVersion              int64
	CreatedAt                  pgtype.Timestamptz
	SnapshotID                 string
	Revision                   int64
	ExpectedGeneration         int64
}

// hikyo:instance-scoped
func (q *Queries) InsertSelfConfigJob(ctx context.Context, arg InsertSelfConfigJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSelfConfigJob,
		arg.ID,
		arg.IdempotencyKey,
		arg.ConfirmRestoredCredentials,
		arg.PrincipalID,
		arg.SchemaVersion,
		arg.CreatedAt,
		arg.SnapshotID,
		arg.Revision,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSelfConfigJobs = `-- name: ListSelfConfigJobs :many
SELECT id, idempotency_key, confirm_restored_credentials, principal_id, snapshot_id, revision, schema_version, expected_generation, generation, status, error_code, created_at, updated_at FROM self_config_jobs ORDER BY created_at DESC,id DESC LIMIT 100
`

// hikyo:instance-scoped
func (q *Queries) ListSelfConfigJobs(ctx context.Context) ([]SelfConfigJob, error) {
	rows, err := q.db.Query(ctx, listSelfConfigJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelfConfigJob
	for rows.Next() {
		var i SelfConfigJob
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.ConfirmRestoredCredentials,
			&i.PrincipalID,
			&i.SnapshotID,
			&i.Revision,
			&i.SchemaVersion,
			&i.ExpectedGeneration,
			&i.Generation,
			&i.Status,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelfConfigNodes = `-- name: ListSelfConfigNodes :many
SELECT node_id, job_id, schema_version, prepared, active_generation, active_revision, incarnation, error_code, updated_at FROM self_config_nodes ORDER BY node_id
`

// hikyo:instance-scoped
func (q *Queries) ListSelfConfigNodes(ctx context.Context) ([]SelfConfigNode, error) {
	rows, err := q.db.Query(ctx, listSelfConfigNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelfConfigNode
	for rows.Next() {
		var i SelfConfigNode
		if err := rows.Scan(
			&i.NodeID,
			&i.JobID,
			&i.SchemaVersion,
			&i.Prepared,
			&i.ActiveGeneration,
			&i.ActiveRevision,
			&i.Incarnation,
			&i.ErrorCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelfConfigParticipants = `-- name: ListSelfConfigParticipants :many
SELECT node_id FROM ha_nodes WHERE heartbeat_at >= $1 ORDER BY node_id
`

// hikyo:instance-scoped
func (q *Queries) ListSelfConfigParticipants(ctx context.Context, sinceAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listSelfConfigParticipants, sinceAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelfConfigRetained = `-- name: ListSelfConfigRetained :many
SELECT snapshot_id FROM self_config_retention ORDER BY slot
`

// hikyo:instance-scoped
func (q *Queries) ListSelfConfigRetained(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSelfConfigRetained)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var snapshot_id string
		if err := rows.Scan(&snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, snapshot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSelfConfigBinding = `-- name: LockSelfConfigBinding :one
SELECT id, owner_instance_id, adoption_key, adopted_by, org_id, project_id, environment_id, schema_version, generation, desired_revision, desired_snapshot_id, previous_snapshot_id, incarnation, suspended, created_at, updated_at FROM self_config_binding WHERE id = 1 FOR UPDATE
`

// hikyo:instance-scoped
func (q *Queries) LockSelfConfigBinding(ctx context.Context) (SelfConfigBinding, error) {
	row := q.db.QueryRow(ctx, lockSelfConfigBinding)
	var i SelfConfigBinding
	err := row.Scan(
		&i.ID,
		&i.OwnerInstanceID,
		&i.AdoptionKey,
		&i.AdoptedBy,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SchemaVersion,
		&i.Generation,
		&i.DesiredRevision,
		&i.DesiredSnapshotID,
		&i.PreviousSnapshotID,
		&i.Incarnation,
		&i.Suspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSelfConfigMembership = `-- name: LockSelfConfigMembership :exec
SELECT pg_advisory_xact_lock(1464159830,87)
`

// hikyo:instance-scoped
func (q *Queries) LockSelfConfigMembership(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSelfConfigMembership)
	return err
}

const putSelfConfigNode = `-- name: PutSelfConfigNode :exec
INSERT INTO self_config_nodes(node_id,job_id,schema_version,prepared,active_generation,active_revision,incarnation,error_code,updated_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT(node_id) DO UPDATE SET job_id=excluded.job_id,schema_version=excluded.schema_version,prepared=excluded.prepared,active_generation=excluded.active_generation,active_revision=excluded.active_revision,incarnation=excluded.incarnation,error_code=excluded.error_code,updated_at=excluded.updated_at
`

type PutSelfConfigNodeParams struct {
	NodeID           string
	JobID            string
	SchemaVersion    int64
	Prepared         bool
	ActiveGeneration int64
	ActiveRevision   int64
	Incarnation      string
	ErrorCode        string
	UpdatedAt        pgtype.Timestamptz
}

// hikyo:instance-scoped
func (q *Queries) PutSelfConfigNode(ctx context.Context, arg PutSelfConfigNodeParams) error {
	_, err := q.db.Exec(ctx, putSelfConfigNode,
		arg.NodeID,
		arg.JobID,
		arg.SchemaVersion,
		arg.Prepared,
		arg.ActiveGeneration,
		arg.ActiveRevision,
		arg.Incarnation,
		arg.ErrorCode,
		arg.UpdatedAt,
	)
	return err
}

const recoverSelfConfigTarget = `-- name: RecoverSelfConfigTarget :execrows
UPDATE self_config_binding SET desired_snapshot_id=$1,desired_revision=$2,generation=generation+1,updated_at=$3
WHERE id=1 AND generation=$4
AND EXISTS(SELECT 1 FROM snapshots s WHERE s.id=$1 AND s.org_id=self_config_binding.org_id AND s.project_id=self_config_binding.project_id AND s.environment_id=self_config_binding.environment_id AND s.revision=$2 AND s.payload_present)
`

type RecoverSelfConfigTargetParams struct {
	SnapshotID         string
	Revision           int64
	UpdatedAt          pgtype.Timestamptz
	ExpectedGeneration int64
}

// hikyo:instance-scoped
func (q *Queries) RecoverSelfConfigTarget(ctx context.Context, arg RecoverSelfConfigTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, recoverSelfConfigTarget,
		arg.SnapshotID,
		arg.Revision,
		arg.UpdatedAt,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSelfConfigPrevious = `-- name: SetSelfConfigPrevious :exec
UPDATE self_config_binding SET previous_snapshot_id=$1 WHERE id=1
`

// hikyo:instance-scoped
func (q *Queries) SetSelfConfigPrevious(ctx context.Context, snapshotID string) error {
	_, err := q.db.Exec(ctx, setSelfConfigPrevious, snapshotID)
	return err
}

const setSelfConfigRetention = `-- name: SetSelfConfigRetention :exec
INSERT INTO self_config_retention(slot,snapshot_id) VALUES($1,$2) ON CONFLICT(slot) DO UPDATE SET snapshot_id=excluded.snapshot_id
`

type SetSelfConfigRetentionParams struct {
	Slot       string
	SnapshotID string
}

// hikyo:instance-scoped
func (q *Queries) SetSelfConfigRetention(ctx context.Context, arg SetSelfConfigRetentionParams) error {
	_, err := q.db.Exec(ctx, setSelfConfigRetention, arg.Slot, arg.SnapshotID)
	return err
}

const updateSelfConfigJob = `-- name: UpdateSelfConfigJob :execrows
UPDATE self_config_jobs SET status=$1,error_code=$2,updated_at=$3 WHERE id=$4 AND status=$5
`

type UpdateSelfConfigJobParams struct {
	Status         string
	ErrorCode      string
	UpdatedAt      pgtype.Timestamptz
	ID             string
	PreviousStatus string
}

// hikyo:instance-scoped
func (q *Queries) UpdateSelfConfigJob(ctx context.Context, arg UpdateSelfConfigJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSelfConfigJob,
		arg.Status,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.ID,
		arg.PreviousStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
