// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sSHActiveCAKey = `-- name: SSHActiveCAKey :one
SELECT k.id,k.algorithm,k.public_key,k.private_key_ciphertext FROM ssh_ca_keys k JOIN ssh_cas c ON c.id=k.ca_id AND c.org_id=k.org_id AND c.project_id=k.project_id AND c.environment_id=k.environment_id
WHERE k.ca_id=$1 AND k.org_id=$2 AND k.project_id=$3 AND k.environment_id=$4 AND k.state='active' AND c.state='active'
`

type SSHActiveCAKeyParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHActiveCAKeyRow struct {
	ID                   string
	Algorithm            string
	PublicKey            string
	PrivateKeyCiphertext []byte
}

func (q *Queries) SSHActiveCAKey(ctx context.Context, arg SSHActiveCAKeyParams) (SSHActiveCAKeyRow, error) {
	row := q.db.QueryRow(ctx, sSHActiveCAKey,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i SSHActiveCAKeyRow
	err := row.Scan(
		&i.ID,
		&i.Algorithm,
		&i.PublicKey,
		&i.PrivateKeyCiphertext,
	)
	return i, err
}

const sSHActiveCAKeyID = `-- name: SSHActiveCAKeyID :one
SELECT id FROM ssh_ca_keys WHERE ca_id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state='active'
`

type SSHActiveCAKeyIDParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHActiveCAKeyID(ctx context.Context, arg SSHActiveCAKeyIDParams) (string, error) {
	row := q.db.QueryRow(ctx, sSHActiveCAKeyID,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const sSHActiveKeyLastExpiry = `-- name: SSHActiveKeyLastExpiry :one
SELECT c.valid_before AS last_expiry FROM ssh_certificates c
JOIN ssh_ca_keys k ON k.id=c.ca_key_id AND k.org_id=c.org_id AND k.project_id=c.project_id AND k.environment_id=c.environment_id
WHERE c.ca_id=$1 AND c.org_id=$2 AND c.project_id=$3 AND c.environment_id=$4 AND k.state='active' AND c.state='issued' AND c.valid_before>$5 ORDER BY c.valid_before DESC LIMIT 1
`

type SSHActiveKeyLastExpiryParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
	Now          pgtype.Timestamptz
}

func (q *Queries) SSHActiveKeyLastExpiry(ctx context.Context, arg SSHActiveKeyLastExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, sSHActiveKeyLastExpiry,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.Now,
	)
	var last_expiry pgtype.Timestamptz
	err := row.Scan(&last_expiry)
	return last_expiry, err
}

const sSHCAKeyExists = `-- name: SSHCAKeyExists :one
SELECT COUNT(*) FROM ssh_ca_keys WHERE id=$1 AND ca_id=$2 AND org_id=$3 AND project_id=$4 AND environment_id=$5
`

type SSHCAKeyExistsParams struct {
	KeyID        string
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHCAKeyExists(ctx context.Context, arg SSHCAKeyExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sSHCAKeyExists,
		arg.KeyID,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sSHCAKeys = `-- name: SSHCAKeys :many
SELECT id,ca_id,algorithm,public_key,fingerprint,origin,state,created_at,retiring_at,retire_after,retired_at FROM ssh_ca_keys WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY created_at DESC, id DESC
`

type SSHCAKeysParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHCAKeysRow struct {
	ID          string
	CaID        string
	Algorithm   string
	PublicKey   string
	Fingerprint string
	Origin      string
	State       string
	CreatedAt   pgtype.Timestamptz
	RetiringAt  pgtype.Timestamptz
	RetireAfter pgtype.Timestamptz
	RetiredAt   pgtype.Timestamptz
}

func (q *Queries) SSHCAKeys(ctx context.Context, arg SSHCAKeysParams) ([]SSHCAKeysRow, error) {
	rows, err := q.db.Query(ctx, sSHCAKeys, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHCAKeysRow
	for rows.Next() {
		var i SSHCAKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.CaID,
			&i.Algorithm,
			&i.PublicKey,
			&i.Fingerprint,
			&i.Origin,
			&i.State,
			&i.CreatedAt,
			&i.RetiringAt,
			&i.RetireAfter,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHCountLiveCAs = `-- name: SSHCountLiveCAs :one
SELECT COUNT(*) FROM ssh_cas WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 AND state='active'
`

type SSHCountLiveCAsParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHCountLiveCAs(ctx context.Context, arg SSHCountLiveCAsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sSHCountLiveCAs, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sSHCountLiveProfiles = `-- name: SSHCountLiveProfiles :one
SELECT COUNT(*) FROM ssh_profiles WHERE ca_id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state<>'tombstoned'
`

type SSHCountLiveProfilesParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHCountLiveProfiles(ctx context.Context, arg SSHCountLiveProfilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, sSHCountLiveProfiles,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sSHCreateCA = `-- name: SSHCreateCA :execrows
INSERT INTO ssh_cas (id,org_id,project_id,environment_id,name,state,authority_principal_id,created_at) VALUES ($1,$2,$3,$4,$5, 'active', $6, $7)
`

type SSHCreateCAParams struct {
	ID                   string
	ChainOrg             string
	ChainProject         string
	ChainEnv             string
	Name                 string
	AuthorityPrincipalID string
	At                   pgtype.Timestamptz
}

func (q *Queries) SSHCreateCA(ctx context.Context, arg SSHCreateCAParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHCreateCA,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.Name,
		arg.AuthorityPrincipalID,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHCreateProfile = `-- name: SSHCreateProfile :execrows
INSERT INTO ssh_profiles (id,org_id,project_id,environment_id,ca_id,name,principals,force_command,source_addresses,extensions,key_algorithms,default_ttl_seconds,max_ttl_seconds,state,created_at,updated_at)
SELECT $1,ca.org_id,ca.project_id,ca.environment_id,ca.id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11 FROM ssh_cas ca WHERE ca.id=$12 AND ca.org_id=$13 AND ca.project_id=$14 AND ca.environment_id=$15 AND ca.state='active'
`

type SSHCreateProfileParams struct {
	ID                string
	Name              string
	Principals        string
	ForceCommand      string
	SourceAddresses   string
	Extensions        string
	KeyAlgorithms     string
	DefaultTtlSeconds int64
	MaxTtlSeconds     int64
	State             string
	At                pgtype.Timestamptz
	CaID              string
	ChainOrg          string
	ChainProject      string
	ChainEnv          string
}

func (q *Queries) SSHCreateProfile(ctx context.Context, arg SSHCreateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHCreateProfile,
		arg.ID,
		arg.Name,
		arg.Principals,
		arg.ForceCommand,
		arg.SourceAddresses,
		arg.Extensions,
		arg.KeyAlgorithms,
		arg.DefaultTtlSeconds,
		arg.MaxTtlSeconds,
		arg.State,
		arg.At,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHDeleteCA = `-- name: SSHDeleteCA :execrows
UPDATE ssh_cas SET state='tombstoned' WHERE id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state='active'
`

type SSHDeleteCAParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHDeleteCA(ctx context.Context, arg SSHDeleteCAParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHDeleteCA,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHDeleteProfile = `-- name: SSHDeleteProfile :execrows
UPDATE ssh_profiles SET state='tombstoned',updated_at=$1 WHERE id=$2 AND org_id=$3 AND project_id=$4 AND environment_id=$5 AND state<>'tombstoned'
`

type SSHDeleteProfileParams struct {
	At           pgtype.Timestamptz
	ProfileID    string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHDeleteProfile(ctx context.Context, arg SSHDeleteProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHDeleteProfile,
		arg.At,
		arg.ProfileID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHDeleteRequesters = `-- name: SSHDeleteRequesters :execrows
DELETE FROM ssh_profile_requesters WHERE profile_id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4
`

type SSHDeleteRequestersParams struct {
	ProfileID    string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHDeleteRequesters(ctx context.Context, arg SSHDeleteRequestersParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHDeleteRequesters,
		arg.ProfileID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHGetCA = `-- name: SSHGetCA :one
SELECT id,name,state,authority_principal_id,created_at FROM ssh_cas WHERE id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state='active'
`

type SSHGetCAParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHGetCARow struct {
	ID                   string
	Name                 string
	State                string
	AuthorityPrincipalID string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) SSHGetCA(ctx context.Context, arg SSHGetCAParams) (SSHGetCARow, error) {
	row := q.db.QueryRow(ctx, sSHGetCA,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i SSHGetCARow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.AuthorityPrincipalID,
		&i.CreatedAt,
	)
	return i, err
}

const sSHGetCertificate = `-- name: SSHGetCertificate :one
SELECT c.id,c.ca_id,c.ca_key_id,c.profile_id,c.serial,c.key_id,c.principals,c.public_key_fingerprint,c.key_algorithm,c.key_origin,c.valid_after,c.valid_before,c.requester_principal_id,c.requester_class,c.state,c.revoked_at,c.revocation_reason,c.created_at,k.state AS ca_key_state,k.retire_after AS ca_key_retire_after,a.state AS ca_state FROM ssh_certificates c
JOIN ssh_ca_keys k ON k.id=c.ca_key_id AND k.org_id=c.org_id AND k.project_id=c.project_id AND k.environment_id=c.environment_id
JOIN ssh_cas a ON a.id=c.ca_id AND a.org_id=c.org_id AND a.project_id=c.project_id AND a.environment_id=c.environment_id WHERE c.id=$1 AND c.org_id=$2 AND c.project_id=$3 AND c.environment_id=$4
`

type SSHGetCertificateParams struct {
	CertificateID string
	ChainOrg      string
	ChainProject  string
	ChainEnv      string
}

type SSHGetCertificateRow struct {
	ID                   string
	CaID                 string
	CaKeyID              string
	ProfileID            string
	Serial               int64
	KeyID                string
	Principals           string
	PublicKeyFingerprint string
	KeyAlgorithm         string
	KeyOrigin            string
	ValidAfter           pgtype.Timestamptz
	ValidBefore          pgtype.Timestamptz
	RequesterPrincipalID string
	RequesterClass       string
	State                string
	RevokedAt            pgtype.Timestamptz
	RevocationReason     pgtype.Text
	CreatedAt            pgtype.Timestamptz
	CaKeyState           string
	CaKeyRetireAfter     pgtype.Timestamptz
	CaState              string
}

func (q *Queries) SSHGetCertificate(ctx context.Context, arg SSHGetCertificateParams) (SSHGetCertificateRow, error) {
	row := q.db.QueryRow(ctx, sSHGetCertificate,
		arg.CertificateID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i SSHGetCertificateRow
	err := row.Scan(
		&i.ID,
		&i.CaID,
		&i.CaKeyID,
		&i.ProfileID,
		&i.Serial,
		&i.KeyID,
		&i.Principals,
		&i.PublicKeyFingerprint,
		&i.KeyAlgorithm,
		&i.KeyOrigin,
		&i.ValidAfter,
		&i.ValidBefore,
		&i.RequesterPrincipalID,
		&i.RequesterClass,
		&i.State,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.CaKeyState,
		&i.CaKeyRetireAfter,
		&i.CaState,
	)
	return i, err
}

const sSHGetProfile = `-- name: SSHGetProfile :one
SELECT id,ca_id,name,principals,force_command,source_addresses,extensions,key_algorithms,default_ttl_seconds,max_ttl_seconds,state,created_at,updated_at FROM ssh_profiles WHERE id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state<>'tombstoned'
`

type SSHGetProfileParams struct {
	ProfileID    string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHGetProfileRow struct {
	ID                string
	CaID              string
	Name              string
	Principals        string
	ForceCommand      string
	SourceAddresses   string
	Extensions        string
	KeyAlgorithms     string
	DefaultTtlSeconds int64
	MaxTtlSeconds     int64
	State             string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) SSHGetProfile(ctx context.Context, arg SSHGetProfileParams) (SSHGetProfileRow, error) {
	row := q.db.QueryRow(ctx, sSHGetProfile,
		arg.ProfileID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var i SSHGetProfileRow
	err := row.Scan(
		&i.ID,
		&i.CaID,
		&i.Name,
		&i.Principals,
		&i.ForceCommand,
		&i.SourceAddresses,
		&i.Extensions,
		&i.KeyAlgorithms,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sSHInsertCAKey = `-- name: SSHInsertCAKey :execrows
INSERT INTO ssh_ca_keys (id,org_id,project_id,environment_id,ca_id,algorithm,public_key,fingerprint,origin,private_key_ciphertext,state,created_at)
SELECT $1,ca.org_id,ca.project_id,ca.environment_id,ca.id,$2,$3,$4,$5,$6, 'active', $7 FROM ssh_cas ca WHERE ca.id=$8 AND ca.org_id=$9 AND ca.project_id=$10 AND ca.environment_id=$11 AND ca.state='active'
`

type SSHInsertCAKeyParams struct {
	ID           string
	Algorithm    string
	PublicKey    string
	Fingerprint  string
	Origin       string
	Ciphertext   []byte
	At           pgtype.Timestamptz
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHInsertCAKey(ctx context.Context, arg SSHInsertCAKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHInsertCAKey,
		arg.ID,
		arg.Algorithm,
		arg.PublicKey,
		arg.Fingerprint,
		arg.Origin,
		arg.Ciphertext,
		arg.At,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHInsertCertificate = `-- name: SSHInsertCertificate :execrows
INSERT INTO ssh_certificates (id,org_id,project_id,environment_id,ca_id,ca_key_id,profile_id,serial,key_id,principals,public_key_fingerprint,key_algorithm,key_origin,valid_after,valid_before,requester_principal_id,requester_class,state,created_at)
SELECT $1,k.org_id,k.project_id,k.environment_id,k.ca_id,k.id,pr.id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, 'issued', $12
FROM ssh_ca_keys k JOIN ssh_profiles pr ON pr.ca_id=k.ca_id AND pr.org_id=k.org_id AND pr.project_id=k.project_id AND pr.environment_id=k.environment_id
WHERE k.id=$13 AND k.ca_id=$14 AND k.state='active' AND pr.id=$15 AND pr.state='enabled' AND k.org_id=$16 AND k.project_id=$17 AND k.environment_id=$18
`

type SSHInsertCertificateParams struct {
	ID                   string
	Serial               int64
	KeyID                string
	Principals           string
	PublicKeyFingerprint string
	KeyAlgorithm         string
	KeyOrigin            string
	ValidAfter           pgtype.Timestamptz
	ValidBefore          pgtype.Timestamptz
	RequesterPrincipalID string
	RequesterClass       string
	At                   pgtype.Timestamptz
	CaKeyID              string
	CaID                 string
	ProfileID            string
	ChainOrg             string
	ChainProject         string
	ChainEnv             string
}

func (q *Queries) SSHInsertCertificate(ctx context.Context, arg SSHInsertCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHInsertCertificate,
		arg.ID,
		arg.Serial,
		arg.KeyID,
		arg.Principals,
		arg.PublicKeyFingerprint,
		arg.KeyAlgorithm,
		arg.KeyOrigin,
		arg.ValidAfter,
		arg.ValidBefore,
		arg.RequesterPrincipalID,
		arg.RequesterClass,
		arg.At,
		arg.CaKeyID,
		arg.CaID,
		arg.ProfileID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHInsertRequester = `-- name: SSHInsertRequester :execrows
INSERT INTO ssh_profile_requesters (org_id,project_id,environment_id,profile_id,principal_id,created_at) VALUES ($1,$2,$3,$4,$5,$6)
`

type SSHInsertRequesterParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
	ProfileID    string
	Principal    string
	At           pgtype.Timestamptz
}

func (q *Queries) SSHInsertRequester(ctx context.Context, arg SSHInsertRequesterParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHInsertRequester,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.ProfileID,
		arg.Principal,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHIsRequester = `-- name: SSHIsRequester :one
SELECT COUNT(*) FROM ssh_profile_requesters WHERE profile_id=$1 AND principal_id=$2 AND org_id=$3 AND project_id=$4 AND environment_id=$5
`

type SSHIsRequesterParams struct {
	ProfileID    string
	PrincipalID  string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHIsRequester(ctx context.Context, arg SSHIsRequesterParams) (int64, error) {
	row := q.db.QueryRow(ctx, sSHIsRequester,
		arg.ProfileID,
		arg.PrincipalID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sSHListCAs = `-- name: SSHListCAs :many
SELECT id,name,state,authority_principal_id,created_at FROM ssh_cas WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 AND state='active' ORDER BY name, id
`

type SSHListCAsParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHListCAsRow struct {
	ID                   string
	Name                 string
	State                string
	AuthorityPrincipalID string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) SSHListCAs(ctx context.Context, arg SSHListCAsParams) ([]SSHListCAsRow, error) {
	rows, err := q.db.Query(ctx, sSHListCAs, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHListCAsRow
	for rows.Next() {
		var i SSHListCAsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.AuthorityPrincipalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHListCertificates = `-- name: SSHListCertificates :many
SELECT c.id,c.ca_id,c.ca_key_id,c.profile_id,c.serial,c.key_id,c.principals,c.public_key_fingerprint,c.key_algorithm,c.key_origin,c.valid_after,c.valid_before,c.requester_principal_id,c.requester_class,c.state,c.revoked_at,c.revocation_reason,c.created_at,k.state AS ca_key_state,k.retire_after AS ca_key_retire_after,a.state AS ca_state FROM ssh_certificates c
JOIN ssh_ca_keys k ON k.id=c.ca_key_id AND k.org_id=c.org_id AND k.project_id=c.project_id AND k.environment_id=c.environment_id
JOIN ssh_cas a ON a.id=c.ca_id AND a.org_id=c.org_id AND a.project_id=c.project_id AND a.environment_id=c.environment_id WHERE c.org_id=$1 AND c.project_id=$2 AND c.environment_id=$3 ORDER BY c.created_at DESC, c.id DESC LIMIT CAST($4 AS BIGINT)
`

type SSHListCertificatesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
	PageLimit    int64
}

type SSHListCertificatesRow struct {
	ID                   string
	CaID                 string
	CaKeyID              string
	ProfileID            string
	Serial               int64
	KeyID                string
	Principals           string
	PublicKeyFingerprint string
	KeyAlgorithm         string
	KeyOrigin            string
	ValidAfter           pgtype.Timestamptz
	ValidBefore          pgtype.Timestamptz
	RequesterPrincipalID string
	RequesterClass       string
	State                string
	RevokedAt            pgtype.Timestamptz
	RevocationReason     pgtype.Text
	CreatedAt            pgtype.Timestamptz
	CaKeyState           string
	CaKeyRetireAfter     pgtype.Timestamptz
	CaState              string
}

func (q *Queries) SSHListCertificates(ctx context.Context, arg SSHListCertificatesParams) ([]SSHListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, sSHListCertificates,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHListCertificatesRow
	for rows.Next() {
		var i SSHListCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaID,
			&i.CaKeyID,
			&i.ProfileID,
			&i.Serial,
			&i.KeyID,
			&i.Principals,
			&i.PublicKeyFingerprint,
			&i.KeyAlgorithm,
			&i.KeyOrigin,
			&i.ValidAfter,
			&i.ValidBefore,
			&i.RequesterPrincipalID,
			&i.RequesterClass,
			&i.State,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.CreatedAt,
			&i.CaKeyState,
			&i.CaKeyRetireAfter,
			&i.CaState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHListKeysForReencrypt = `-- name: SSHListKeysForReencrypt :many
SELECT id, private_key_ciphertext FROM ssh_ca_keys WHERE org_id=$1 AND project_id=$2 AND id>$3 AND private_key_ciphertext IS NOT NULL ORDER BY id LIMIT CAST($4 AS BIGINT)
`

type SSHListKeysForReencryptParams struct {
	ChainOrg     string
	ChainProject string
	Cursor       string
	PageLimit    int64
}

type SSHListKeysForReencryptRow struct {
	ID                   string
	PrivateKeyCiphertext []byte
}

func (q *Queries) SSHListKeysForReencrypt(ctx context.Context, arg SSHListKeysForReencryptParams) ([]SSHListKeysForReencryptRow, error) {
	rows, err := q.db.Query(ctx, sSHListKeysForReencrypt,
		arg.ChainOrg,
		arg.ChainProject,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHListKeysForReencryptRow
	for rows.Next() {
		var i SSHListKeysForReencryptRow
		if err := rows.Scan(&i.ID, &i.PrivateKeyCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHListProfiles = `-- name: SSHListProfiles :many
SELECT id,ca_id,name,principals,force_command,source_addresses,extensions,key_algorithms,default_ttl_seconds,max_ttl_seconds,state,created_at,updated_at FROM ssh_profiles WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 AND state<>'tombstoned' ORDER BY name, id
`

type SSHListProfilesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHListProfilesRow struct {
	ID                string
	CaID              string
	Name              string
	Principals        string
	ForceCommand      string
	SourceAddresses   string
	Extensions        string
	KeyAlgorithms     string
	DefaultTtlSeconds int64
	MaxTtlSeconds     int64
	State             string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) SSHListProfiles(ctx context.Context, arg SSHListProfilesParams) ([]SSHListProfilesRow, error) {
	rows, err := q.db.Query(ctx, sSHListProfiles, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHListProfilesRow
	for rows.Next() {
		var i SSHListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaID,
			&i.Name,
			&i.Principals,
			&i.ForceCommand,
			&i.SourceAddresses,
			&i.Extensions,
			&i.KeyAlgorithms,
			&i.DefaultTtlSeconds,
			&i.MaxTtlSeconds,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHProfileRevocationCandidates = `-- name: SSHProfileRevocationCandidates :many
SELECT id,serial,requester_principal_id FROM ssh_certificates WHERE profile_id=$1 AND org_id=$2 AND project_id=$3 AND environment_id=$4 AND state='issued' AND valid_before>$5 ORDER BY id
`

type SSHProfileRevocationCandidatesParams struct {
	ProfileID    string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
	At           pgtype.Timestamptz
}

type SSHProfileRevocationCandidatesRow struct {
	ID                   string
	Serial               int64
	RequesterPrincipalID string
}

func (q *Queries) SSHProfileRevocationCandidates(ctx context.Context, arg SSHProfileRevocationCandidatesParams) ([]SSHProfileRevocationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, sSHProfileRevocationCandidates,
		arg.ProfileID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.At,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHProfileRevocationCandidatesRow
	for rows.Next() {
		var i SSHProfileRevocationCandidatesRow
		if err := rows.Scan(&i.ID, &i.Serial, &i.RequesterPrincipalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHPurgeCAKeys = `-- name: SSHPurgeCAKeys :exec
DELETE FROM ssh_ca_keys WHERE org_id=$1 AND project_id=$2 AND environment_id=$3
`

type SSHPurgeCAKeysParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHPurgeCAKeys(ctx context.Context, arg SSHPurgeCAKeysParams) error {
	_, err := q.db.Exec(ctx, sSHPurgeCAKeys, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	return err
}

const sSHPurgeCAs = `-- name: SSHPurgeCAs :exec
DELETE FROM ssh_cas WHERE org_id=$1 AND project_id=$2 AND environment_id=$3
`

type SSHPurgeCAsParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHPurgeCAs(ctx context.Context, arg SSHPurgeCAsParams) error {
	_, err := q.db.Exec(ctx, sSHPurgeCAs, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	return err
}

const sSHPurgeCertificates = `-- name: SSHPurgeCertificates :exec
DELETE FROM ssh_certificates WHERE org_id=$1 AND project_id=$2 AND environment_id=$3
`

type SSHPurgeCertificatesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHPurgeCertificates(ctx context.Context, arg SSHPurgeCertificatesParams) error {
	_, err := q.db.Exec(ctx, sSHPurgeCertificates, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	return err
}

const sSHPurgeProfiles = `-- name: SSHPurgeProfiles :exec
DELETE FROM ssh_profiles WHERE org_id=$1 AND project_id=$2 AND environment_id=$3
`

type SSHPurgeProfilesParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHPurgeProfiles(ctx context.Context, arg SSHPurgeProfilesParams) error {
	_, err := q.db.Exec(ctx, sSHPurgeProfiles, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	return err
}

const sSHPurgeRequesters = `-- name: SSHPurgeRequesters :exec
DELETE FROM ssh_profile_requesters WHERE org_id=$1 AND project_id=$2 AND environment_id=$3
`

type SSHPurgeRequestersParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHPurgeRequesters(ctx context.Context, arg SSHPurgeRequestersParams) error {
	_, err := q.db.Exec(ctx, sSHPurgeRequesters, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	return err
}

const sSHReencryptCAKey = `-- name: SSHReencryptCAKey :execrows
UPDATE ssh_ca_keys SET private_key_ciphertext=$1 WHERE org_id=$2 AND project_id=$3 AND id=$4 AND private_key_ciphertext=$5
`

type SSHReencryptCAKeyParams struct {
	NewCiphertext []byte
	ChainOrg      string
	ChainProject  string
	ID            string
	OldCiphertext []byte
}

func (q *Queries) SSHReencryptCAKey(ctx context.Context, arg SSHReencryptCAKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHReencryptCAKey,
		arg.NewCiphertext,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ID,
		arg.OldCiphertext,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHRequesters = `-- name: SSHRequesters :many
SELECT profile_id,principal_id FROM ssh_profile_requesters WHERE org_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY profile_id, principal_id
`

type SSHRequestersParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type SSHRequestersRow struct {
	ProfileID   string
	PrincipalID string
}

func (q *Queries) SSHRequesters(ctx context.Context, arg SSHRequestersParams) ([]SSHRequestersRow, error) {
	rows, err := q.db.Query(ctx, sSHRequesters, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHRequestersRow
	for rows.Next() {
		var i SSHRequestersRow
		if err := rows.Scan(&i.ProfileID, &i.PrincipalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHRetireActiveCAKey = `-- name: SSHRetireActiveCAKey :execrows
UPDATE ssh_ca_keys SET state='retiring',private_key_ciphertext=NULL,retiring_at=$1,retire_after=$2 WHERE id=$3 AND org_id=$4 AND project_id=$5 AND environment_id=$6 AND state='active'
`

type SSHRetireActiveCAKeyParams struct {
	At           pgtype.Timestamptz
	RetireAfter  pgtype.Timestamptz
	KeyID        string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHRetireActiveCAKey(ctx context.Context, arg SSHRetireActiveCAKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHRetireActiveCAKey,
		arg.At,
		arg.RetireAfter,
		arg.KeyID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHRetireAllCAKeys = `-- name: SSHRetireAllCAKeys :execrows
UPDATE ssh_ca_keys SET state='retired',private_key_ciphertext=NULL,retired_at=$1 WHERE ca_id=$2 AND org_id=$3 AND project_id=$4 AND environment_id=$5 AND state<>'retired'
`

type SSHRetireAllCAKeysParams struct {
	At           pgtype.Timestamptz
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHRetireAllCAKeys(ctx context.Context, arg SSHRetireAllCAKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHRetireAllCAKeys,
		arg.At,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHRetireCAKey = `-- name: SSHRetireCAKey :execrows
UPDATE ssh_ca_keys SET state='retired',retired_at=$1 WHERE id=$2 AND ca_id=$3 AND org_id=$4 AND project_id=$5 AND environment_id=$6 AND state='retiring'
`

type SSHRetireCAKeyParams struct {
	At           pgtype.Timestamptz
	KeyID        string
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) SSHRetireCAKey(ctx context.Context, arg SSHRetireCAKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHRetireCAKey,
		arg.At,
		arg.KeyID,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHRevokeCertificate = `-- name: SSHRevokeCertificate :execrows
UPDATE ssh_certificates SET state='revoked',revoked_at=$1,revocation_reason=$2 WHERE id=$3 AND org_id=$4 AND project_id=$5 AND environment_id=$6 AND state='issued'
`

type SSHRevokeCertificateParams struct {
	At            pgtype.Timestamptz
	Reason        pgtype.Text
	CertificateID string
	ChainOrg      string
	ChainProject  string
	ChainEnv      string
}

func (q *Queries) SSHRevokeCertificate(ctx context.Context, arg SSHRevokeCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHRevokeCertificate,
		arg.At,
		arg.Reason,
		arg.CertificateID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sSHRevokedSerials = `-- name: SSHRevokedSerials :many
SELECT k.public_key,c.serial FROM ssh_certificates c
JOIN ssh_ca_keys k ON k.id=c.ca_key_id AND k.org_id=c.org_id AND k.project_id=c.project_id AND k.environment_id=c.environment_id
WHERE c.ca_id=$1 AND c.org_id=$2 AND c.project_id=$3 AND c.environment_id=$4 AND c.state='revoked' AND c.valid_before>$5
AND (k.state='active' OR (k.state='retiring' AND k.retire_after>$5))
ORDER BY k.id, c.serial LIMIT CAST($6 AS BIGINT)
`

type SSHRevokedSerialsParams struct {
	CaID         string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
	Now          pgtype.Timestamptz
	PageLimit    int64
}

type SSHRevokedSerialsRow struct {
	PublicKey string
	Serial    int64
}

func (q *Queries) SSHRevokedSerials(ctx context.Context, arg SSHRevokedSerialsParams) ([]SSHRevokedSerialsRow, error) {
	rows, err := q.db.Query(ctx, sSHRevokedSerials,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.Now,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SSHRevokedSerialsRow
	for rows.Next() {
		var i SSHRevokedSerialsRow
		if err := rows.Scan(&i.PublicKey, &i.Serial); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHUpdateProfile = `-- name: SSHUpdateProfile :execrows
UPDATE ssh_profiles SET name=$1,principals=$2,force_command=$3,source_addresses=$4,extensions=$5,key_algorithms=$6,default_ttl_seconds=$7,max_ttl_seconds=$8,state=$9,updated_at=$10
WHERE id=$11 AND ca_id=$12 AND org_id=$13 AND project_id=$14 AND environment_id=$15 AND state<>'tombstoned'
`

type SSHUpdateProfileParams struct {
	Name              string
	Principals        string
	ForceCommand      string
	SourceAddresses   string
	Extensions        string
	KeyAlgorithms     string
	DefaultTtlSeconds int64
	MaxTtlSeconds     int64
	State             string
	At                pgtype.Timestamptz
	ID                string
	CaID              string
	ChainOrg          string
	ChainProject      string
	ChainEnv          string
}

func (q *Queries) SSHUpdateProfile(ctx context.Context, arg SSHUpdateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, sSHUpdateProfile,
		arg.Name,
		arg.Principals,
		arg.ForceCommand,
		arg.SourceAddresses,
		arg.Extensions,
		arg.KeyAlgorithms,
		arg.DefaultTtlSeconds,
		arg.MaxTtlSeconds,
		arg.State,
		arg.At,
		arg.ID,
		arg.CaID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
