// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_runtime.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const runtimeSSHCountActive = `-- name: RuntimeSSHCountActive :one
SELECT COUNT(*) FROM ssh_certificates WHERE state='issued' AND valid_before>$1
`

// hikyo:reason SSHRuntime metrics scrape returns only the instance-wide count of issued unexpired certificates through the closed runtime boundary.
// hikyo:instance-scoped
func (q *Queries) RuntimeSSHCountActive(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, runtimeSSHCountActive, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const runtimeSSHCountKRLEntries = `-- name: RuntimeSSHCountKRLEntries :one
SELECT COUNT(*) FROM ssh_certificates c JOIN ssh_ca_keys k ON k.id=c.ca_key_id
WHERE c.state='revoked' AND c.valid_before>$1 AND (k.state='active' OR (k.state='retiring' AND k.retire_after>$1))
`

// hikyo:reason SSHRuntime metrics scrape returns only the instance-wide count of revoked unexpired certificates under still-trusted CA keys through the closed runtime boundary.
// hikyo:instance-scoped
func (q *Queries) RuntimeSSHCountKRLEntries(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, runtimeSSHCountKRLEntries, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const runtimeSSHInsertAuthorityRevocationAudit = `-- name: RuntimeSSHInsertAuthorityRevocationAudit :exec
INSERT INTO audit_tenant_events (id,type,schema_version,occurred_at,occurred_asserted,recorded_at,actor_id,actor_class,authority_id,scope_class,org_id,project_id,env_id,object_type,object_id,outcome,correlation_id,origin,payload)
VALUES ($1,'ssh.certificate_revoked',1,$2,false,$2,NULL,'system',$3,'env',$4,$5,$6,'ssh-certificate',$7,'success',$7,'system',$8)
`

type RuntimeSSHInsertAuthorityRevocationAuditParams struct {
	ID            string
	At            pgtype.Timestamptz
	AuthorityID   pgtype.Text
	ChainOrg      string
	ChainProject  pgtype.Text
	ChainEnv      pgtype.Text
	CertificateID pgtype.Text
	Payload       string
}

func (q *Queries) RuntimeSSHInsertAuthorityRevocationAudit(ctx context.Context, arg RuntimeSSHInsertAuthorityRevocationAuditParams) error {
	_, err := q.db.Exec(ctx, runtimeSSHInsertAuthorityRevocationAudit,
		arg.ID,
		arg.At,
		arg.AuthorityID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
		arg.CertificateID,
		arg.Payload,
	)
	return err
}

const runtimeSSHListLiveCertificates = `-- name: RuntimeSSHListLiveCertificates :many
SELECT c.id,c.org_id,c.project_id,c.environment_id,c.profile_id,c.serial,c.requester_principal_id,c.requester_class,
CAST(CASE WHEN q.principal_id IS NULL THEN 0 ELSE 1 END AS INTEGER) AS requester_listed
FROM ssh_certificates c
LEFT JOIN ssh_profile_requesters q ON q.profile_id=c.profile_id AND q.principal_id=c.requester_principal_id AND q.org_id=c.org_id AND q.project_id=c.project_id AND q.environment_id=c.environment_id
WHERE c.state='issued' AND c.valid_before>$1 AND c.id>$2 ORDER BY c.id LIMIT CAST($3 AS BIGINT)
`

type RuntimeSSHListLiveCertificatesParams struct {
	Now       pgtype.Timestamptz
	AfterID   string
	PageLimit int64
}

type RuntimeSSHListLiveCertificatesRow struct {
	ID                   string
	OrgID                string
	ProjectID            string
	EnvironmentID        string
	ProfileID            string
	Serial               int64
	RequesterPrincipalID string
	RequesterClass       string
	RequesterListed      int32
}

// hikyo:reason SSHRuntime closed sweeper pages live certificate authority facts across tenants; each candidate is reauthorized before its immutable chain can be revoked.
// hikyo:instance-scoped
func (q *Queries) RuntimeSSHListLiveCertificates(ctx context.Context, arg RuntimeSSHListLiveCertificatesParams) ([]RuntimeSSHListLiveCertificatesRow, error) {
	rows, err := q.db.Query(ctx, runtimeSSHListLiveCertificates, arg.Now, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeSSHListLiveCertificatesRow
	for rows.Next() {
		var i RuntimeSSHListLiveCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ProfileID,
			&i.Serial,
			&i.RequesterPrincipalID,
			&i.RequesterClass,
			&i.RequesterListed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runtimeSSHRevokeForAuthority = `-- name: RuntimeSSHRevokeForAuthority :execrows
UPDATE ssh_certificates SET state='revoked',revoked_at=$1,revocation_reason='authority-withdrawn' WHERE id=$2 AND org_id=$3 AND project_id=$4 AND environment_id=$5 AND state='issued'
`

type RuntimeSSHRevokeForAuthorityParams struct {
	At           pgtype.Timestamptz
	ID           string
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

func (q *Queries) RuntimeSSHRevokeForAuthority(ctx context.Context, arg RuntimeSSHRevokeForAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, runtimeSSHRevokeForAuthority,
		arg.At,
		arg.ID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ChainEnv,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
