// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const countActiveAccessGrants = `-- name: CountActiveAccessGrants :one
SELECT COUNT(*) FROM access_requests WHERE state = 'granted' AND expires_at > ?
`

// hikyo:instance-scoped
func (q *Queries) CountActiveAccessGrants(ctx context.Context, expiresAt sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAccessGrants, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenAccessRequests = `-- name: CountOpenAccessRequests :one
SELECT COUNT(*) FROM access_requests WHERE state = 'open'
`

// hikyo:instance-scoped
func (q *Queries) CountOpenAccessRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenAccessRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccessPolicy = `-- name: DeleteAccessPolicy :execrows
DELETE FROM access_policies
WHERE org_id = ? AND project_id = ? AND id = ?
`

type DeleteAccessPolicyParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) DeleteAccessPolicy(ctx context.Context, arg DeleteAccessPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessPolicy, arg.OrgID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAccessPolicyApprovers = `-- name: DeleteAccessPolicyApprovers :execrows
DELETE FROM access_policy_approvers
WHERE org_id = ? AND project_id = ? AND policy_id = ?
`

type DeleteAccessPolicyApproversParams struct {
	OrgID     string
	ProjectID string
	PolicyID  string
}

func (q *Queries) DeleteAccessPolicyApprovers(ctx context.Context, arg DeleteAccessPolicyApproversParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessPolicyApprovers, arg.OrgID, arg.ProjectID, arg.PolicyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAccessPolicyBypassers = `-- name: DeleteAccessPolicyBypassers :execrows
DELETE FROM access_policy_bypassers
WHERE org_id = ? AND project_id = ? AND policy_id = ?
`

type DeleteAccessPolicyBypassersParams struct {
	OrgID     string
	ProjectID string
	PolicyID  string
}

func (q *Queries) DeleteAccessPolicyBypassers(ctx context.Context, arg DeleteAccessPolicyBypassersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessPolicyBypassers, arg.OrgID, arg.ProjectID, arg.PolicyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccessPolicy = `-- name: GetAccessPolicy :one
SELECT id, org_id, project_id, environment_id, capabilities, max_duration_seconds,
    min_approvals, allow_self_approval, request_ttl_seconds, enabled, version,
    created_by, created_at, updated_at
FROM access_policies
WHERE org_id = ? AND project_id = ? AND id = ?
`

type GetAccessPolicyParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) GetAccessPolicy(ctx context.Context, arg GetAccessPolicyParams) (AccessPolicy, error) {
	row := q.db.QueryRowContext(ctx, getAccessPolicy, arg.OrgID, arg.ProjectID, arg.ID)
	var i AccessPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Capabilities,
		&i.MaxDurationSeconds,
		&i.MinApprovals,
		&i.AllowSelfApproval,
		&i.RequestTtlSeconds,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessPolicyBypasser = `-- name: GetAccessPolicyBypasser :one
SELECT id FROM access_policy_bypassers
WHERE org_id = ? AND project_id = ? AND policy_id = ? AND principal_id = ?
`

type GetAccessPolicyBypasserParams struct {
	OrgID       string
	ProjectID   string
	PolicyID    string
	PrincipalID string
}

func (q *Queries) GetAccessPolicyBypasser(ctx context.Context, arg GetAccessPolicyBypasserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccessPolicyBypasser,
		arg.OrgID,
		arg.ProjectID,
		arg.PolicyID,
		arg.PrincipalID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAccessPolicyForEnvironment = `-- name: GetAccessPolicyForEnvironment :one
SELECT id, org_id, project_id, environment_id, capabilities, max_duration_seconds,
    min_approvals, allow_self_approval, request_ttl_seconds, enabled, version,
    created_by, created_at, updated_at
FROM access_policies
WHERE org_id = ? AND project_id = ? AND environment_id = ?
`

type GetAccessPolicyForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

// GetAccessPolicyForEnvironment is the coverage lookup: the service asks for
// the concrete environment first, then ” for the project-wide policy.
// Disabled policies are returned too; the service refuses on them by name.
func (q *Queries) GetAccessPolicyForEnvironment(ctx context.Context, arg GetAccessPolicyForEnvironmentParams) (AccessPolicy, error) {
	row := q.db.QueryRowContext(ctx, getAccessPolicyForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	var i AccessPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Capabilities,
		&i.MaxDurationSeconds,
		&i.MinApprovals,
		&i.AllowSelfApproval,
		&i.RequestTtlSeconds,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessRequest = `-- name: GetAccessRequest :one
SELECT id, org_id, project_id, environment_id, policy_id, policy_version,
    requester_principal_id, capabilities, duration_seconds, reason, bypassed,
    state, invalidated_cause, resolved_by, created_at, review_expires_at,
    granted_at, expires_at, resolved_at
FROM access_requests
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND id = ?
`

type GetAccessRequestParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	ID            string
}

func (q *Queries) GetAccessRequest(ctx context.Context, arg GetAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRowContext(ctx, getAccessRequest,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.PolicyID,
		&i.PolicyVersion,
		&i.RequesterPrincipalID,
		&i.Capabilities,
		&i.DurationSeconds,
		&i.Reason,
		&i.Bypassed,
		&i.State,
		&i.InvalidatedCause,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ReviewExpiresAt,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAccessVote = `-- name: GetAccessVote :one
SELECT id, org_id, project_id, environment_id, request_id, principal_id, decision, created_at
FROM access_votes
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND request_id = ? AND principal_id = ?
`

type GetAccessVoteParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	RequestID     string
	PrincipalID   string
}

func (q *Queries) GetAccessVote(ctx context.Context, arg GetAccessVoteParams) (AccessVote, error) {
	row := q.db.QueryRowContext(ctx, getAccessVote,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RequestID,
		arg.PrincipalID,
	)
	var i AccessVote
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RequestID,
		&i.PrincipalID,
		&i.Decision,
		&i.CreatedAt,
	)
	return i, err
}

const grantAccessRequest = `-- name: GrantAccessRequest :execrows
UPDATE access_requests
SET state = 'granted', granted_at = ?, expires_at = ?
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND id = ? AND state = ?
`

type GrantAccessRequestParams struct {
	GrantedAt     sql.NullString
	ExpiresAt     sql.NullString
	OrgID         string
	ProjectID     string
	EnvironmentID string
	ID            string
	State         string
}

// GrantAccessRequest moves an OPEN request to granted with its absolute
// expiry. The state guard (always 'open', bound as a parameter so the
// predicate analyzer sees a column-OP-param shape) makes a racing decision
// lose rather than grant twice.
func (q *Queries) GrantAccessRequest(ctx context.Context, arg GrantAccessRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, grantAccessRequest,
		arg.GrantedAt,
		arg.ExpiresAt,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
		arg.State,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAccessPolicy = `-- name: InsertAccessPolicy :exec

INSERT INTO access_policies (
    id, org_id, project_id, environment_id, capabilities, max_duration_seconds,
    min_approvals, allow_self_approval, request_ttl_seconds, enabled, version,
    created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccessPolicyParams struct {
	ID                 string
	OrgID              string
	ProjectID          string
	EnvironmentID      string
	Capabilities       string
	MaxDurationSeconds int64
	MinApprovals       int64
	AllowSelfApproval  int64
	RequestTtlSeconds  int64
	Enabled            int64
	Version            int64
	CreatedBy          string
	CreatedAt          string
	UpdatedAt          string
}

// Approval-mediated temporary access (#152). ASCII ONLY: sqlc's sqlite path
// silently mis-slices statements containing non-ASCII.
//
// Tenant-scoped statements bind org_id and project_id from the proof's
// resolved chain, never from caller arguments; environment_id is bound from
// the proof on the environment-addressed statements. Every statement is
// single-table so the predicate analyzer can prove tenant scoping; the
// installation-wide sweep and metric statements carry the instance-scoped
// annotation and are content-pinned instead.
//
// No statement here updates a request's capabilities, duration, reason or
// pinned policy version: a request cannot expand once written.
func (q *Queries) InsertAccessPolicy(ctx context.Context, arg InsertAccessPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessPolicy,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Capabilities,
		arg.MaxDurationSeconds,
		arg.MinApprovals,
		arg.AllowSelfApproval,
		arg.RequestTtlSeconds,
		arg.Enabled,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertAccessPolicyApprover = `-- name: InsertAccessPolicyApprover :exec
INSERT INTO access_policy_approvers (
    id, org_id, project_id, policy_id, kind, subject_id, scope_binding_id
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAccessPolicyApproverParams struct {
	ID             string
	OrgID          string
	ProjectID      string
	PolicyID       string
	Kind           string
	SubjectID      string
	ScopeBindingID string
}

func (q *Queries) InsertAccessPolicyApprover(ctx context.Context, arg InsertAccessPolicyApproverParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessPolicyApprover,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.PolicyID,
		arg.Kind,
		arg.SubjectID,
		arg.ScopeBindingID,
	)
	return err
}

const insertAccessPolicyBypasser = `-- name: InsertAccessPolicyBypasser :exec
INSERT INTO access_policy_bypassers (
    id, org_id, project_id, policy_id, principal_id
) VALUES (?, ?, ?, ?, ?)
`

type InsertAccessPolicyBypasserParams struct {
	ID          string
	OrgID       string
	ProjectID   string
	PolicyID    string
	PrincipalID string
}

func (q *Queries) InsertAccessPolicyBypasser(ctx context.Context, arg InsertAccessPolicyBypasserParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessPolicyBypasser,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.PolicyID,
		arg.PrincipalID,
	)
	return err
}

const insertAccessRequest = `-- name: InsertAccessRequest :exec
INSERT INTO access_requests (
    id, org_id, project_id, environment_id, policy_id, policy_version,
    requester_principal_id, capabilities, duration_seconds, reason, bypassed,
    state, resolved_by, created_at, review_expires_at, granted_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccessRequestParams struct {
	ID                   string
	OrgID                string
	ProjectID            string
	EnvironmentID        string
	PolicyID             string
	PolicyVersion        int64
	RequesterPrincipalID string
	Capabilities         string
	DurationSeconds      int64
	Reason               string
	Bypassed             int64
	State                string
	ResolvedBy           string
	CreatedAt            string
	ReviewExpiresAt      string
	GrantedAt            sql.NullString
	ExpiresAt            sql.NullString
}

func (q *Queries) InsertAccessRequest(ctx context.Context, arg InsertAccessRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessRequest,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.PolicyID,
		arg.PolicyVersion,
		arg.RequesterPrincipalID,
		arg.Capabilities,
		arg.DurationSeconds,
		arg.Reason,
		arg.Bypassed,
		arg.State,
		arg.ResolvedBy,
		arg.CreatedAt,
		arg.ReviewExpiresAt,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertAccessVote = `-- name: InsertAccessVote :exec
INSERT INTO access_votes (
    id, org_id, project_id, environment_id, request_id, principal_id, decision, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccessVoteParams struct {
	ID            string
	OrgID         string
	ProjectID     string
	EnvironmentID string
	RequestID     string
	PrincipalID   string
	Decision      string
	CreatedAt     string
}

func (q *Queries) InsertAccessVote(ctx context.Context, arg InsertAccessVoteParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessVote,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RequestID,
		arg.PrincipalID,
		arg.Decision,
		arg.CreatedAt,
	)
	return err
}

const listAccessPolicies = `-- name: ListAccessPolicies :many
SELECT id, org_id, project_id, environment_id, capabilities, max_duration_seconds,
    min_approvals, allow_self_approval, request_ttl_seconds, enabled, version,
    created_by, created_at, updated_at
FROM access_policies
WHERE org_id = ? AND project_id = ?
ORDER BY environment_id, id
`

type ListAccessPoliciesParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) ListAccessPolicies(ctx context.Context, arg ListAccessPoliciesParams) ([]AccessPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listAccessPolicies, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessPolicy
	for rows.Next() {
		var i AccessPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Capabilities,
			&i.MaxDurationSeconds,
			&i.MinApprovals,
			&i.AllowSelfApproval,
			&i.RequestTtlSeconds,
			&i.Enabled,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessPolicyApprovers = `-- name: ListAccessPolicyApprovers :many
SELECT id, org_id, project_id, policy_id, kind, subject_id, scope_binding_id
FROM access_policy_approvers
WHERE org_id = ? AND project_id = ? AND policy_id = ?
ORDER BY kind, subject_id
`

type ListAccessPolicyApproversParams struct {
	OrgID     string
	ProjectID string
	PolicyID  string
}

func (q *Queries) ListAccessPolicyApprovers(ctx context.Context, arg ListAccessPolicyApproversParams) ([]AccessPolicyApprover, error) {
	rows, err := q.db.QueryContext(ctx, listAccessPolicyApprovers, arg.OrgID, arg.ProjectID, arg.PolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessPolicyApprover
	for rows.Next() {
		var i AccessPolicyApprover
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.PolicyID,
			&i.Kind,
			&i.SubjectID,
			&i.ScopeBindingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessPolicyBypassers = `-- name: ListAccessPolicyBypassers :many
SELECT id, org_id, project_id, policy_id, principal_id
FROM access_policy_bypassers
WHERE org_id = ? AND project_id = ? AND policy_id = ?
ORDER BY principal_id
`

type ListAccessPolicyBypassersParams struct {
	OrgID     string
	ProjectID string
	PolicyID  string
}

func (q *Queries) ListAccessPolicyBypassers(ctx context.Context, arg ListAccessPolicyBypassersParams) ([]AccessPolicyBypasser, error) {
	rows, err := q.db.QueryContext(ctx, listAccessPolicyBypassers, arg.OrgID, arg.ProjectID, arg.PolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessPolicyBypasser
	for rows.Next() {
		var i AccessPolicyBypasser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.PolicyID,
			&i.PrincipalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessRequestsForEnvironment = `-- name: ListAccessRequestsForEnvironment :many
SELECT id, org_id, project_id, environment_id, policy_id, policy_version,
    requester_principal_id, capabilities, duration_seconds, reason, bypassed,
    state, invalidated_cause, resolved_by, created_at, review_expires_at,
    granted_at, expires_at, resolved_at
FROM access_requests
WHERE org_id = ? AND project_id = ? AND environment_id = ?
ORDER BY created_at DESC, id
LIMIT 200
`

type ListAccessRequestsForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) ListAccessRequestsForEnvironment(ctx context.Context, arg ListAccessRequestsForEnvironmentParams) ([]AccessRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAccessRequestsForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.PolicyID,
			&i.PolicyVersion,
			&i.RequesterPrincipalID,
			&i.Capabilities,
			&i.DurationSeconds,
			&i.Reason,
			&i.Bypassed,
			&i.State,
			&i.InvalidatedCause,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ReviewExpiresAt,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessVotes = `-- name: ListAccessVotes :many
SELECT id, org_id, project_id, environment_id, request_id, principal_id, decision, created_at
FROM access_votes
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND request_id = ?
ORDER BY created_at, id
`

type ListAccessVotesParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	RequestID     string
}

func (q *Queries) ListAccessVotes(ctx context.Context, arg ListAccessVotesParams) ([]AccessVote, error) {
	rows, err := q.db.QueryContext(ctx, listAccessVotes,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RequestID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessVote
	for rows.Next() {
		var i AccessVote
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RequestID,
			&i.PrincipalID,
			&i.Decision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccessRequestExpired = `-- name: MarkAccessRequestExpired :execrows
UPDATE access_requests
SET state = 'expired', resolved_at = ?1
WHERE id = ?2 AND state = ?3
`

type MarkAccessRequestExpiredParams struct {
	ResolvedAt sql.NullString
	ID         string
	FromState  string
}

// MarkAccessRequestExpired resolves one active request as expired, guarded by
// the state it was selected in so a concurrent decision or revoke wins.
// hikyo:instance-scoped
func (q *Queries) MarkAccessRequestExpired(ctx context.Context, arg MarkAccessRequestExpiredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAccessRequestExpired, arg.ResolvedAt, arg.ID, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveAccessRequest = `-- name: ResolveAccessRequest :execrows
UPDATE access_requests
SET state = ?1, invalidated_cause = ?2,
    resolved_by = ?3, resolved_at = ?4
WHERE org_id = ?5 AND project_id = ?6
  AND environment_id = ?7 AND id = ?8
  AND state = ?9
`

type ResolveAccessRequestParams struct {
	ToState       string
	Cause         string
	ResolvedBy    string
	ResolvedAt    sql.NullString
	OrgID         string
	ProjectID     string
	EnvironmentID string
	ID            string
	FromState     string
}

// ResolveAccessRequest moves an ACTIVE request to a terminal state. from_state
// is the state the caller read, so a concurrent resolution makes this a no-op
// the caller can detect.
func (q *Queries) ResolveAccessRequest(ctx context.Context, arg ResolveAccessRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveAccessRequest,
		arg.ToState,
		arg.Cause,
		arg.ResolvedBy,
		arg.ResolvedAt,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectDueAccessRequests = `-- name: SelectDueAccessRequests :many
SELECT id, org_id, project_id, environment_id, policy_id, requester_principal_id, state
FROM access_requests
WHERE (state = 'open' AND review_expires_at <= ?1)
   OR (state = 'granted' AND expires_at <= ?1)
ORDER BY id
LIMIT 100
`

type SelectDueAccessRequestsRow struct {
	ID                   string
	OrgID                string
	ProjectID            string
	EnvironmentID        string
	PolicyID             string
	RequesterPrincipalID string
	State                string
}

// SelectDueAccessRequests is one bounded installation-wide sweep batch: open
// requests whose review window lapsed and granted requests whose absolute
// expiry passed. Expiry is already enforced by the chokepoint's row filter;
// the sweep is bookkeeping, session rotation and the audit event.
// hikyo:instance-scoped
func (q *Queries) SelectDueAccessRequests(ctx context.Context, now string) ([]SelectDueAccessRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectDueAccessRequests, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectDueAccessRequestsRow
	for rows.Next() {
		var i SelectDueAccessRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.PolicyID,
			&i.RequesterPrincipalID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessPolicy = `-- name: UpdateAccessPolicy :execrows
UPDATE access_policies
SET capabilities = ?, max_duration_seconds = ?, min_approvals = ?,
    allow_self_approval = ?, request_ttl_seconds = ?, enabled = ?,
    version = version + 1, updated_at = ?
WHERE org_id = ? AND project_id = ? AND id = ?
`

type UpdateAccessPolicyParams struct {
	Capabilities       string
	MaxDurationSeconds int64
	MinApprovals       int64
	AllowSelfApproval  int64
	RequestTtlSeconds  int64
	Enabled            int64
	UpdatedAt          string
	OrgID              string
	ProjectID          string
	ID                 string
}

// UpdateAccessPolicy bumps version so every open request pinned to the older
// version fails closed at its next decision.
func (q *Queries) UpdateAccessPolicy(ctx context.Context, arg UpdateAccessPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccessPolicy,
		arg.Capabilities,
		arg.MaxDurationSeconds,
		arg.MinApprovals,
		arg.AllowSelfApproval,
		arg.RequestTtlSeconds,
		arg.Enabled,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
