// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adapter_manifest.sql

package sqlitegen

import (
	"context"
	"strings"
)

const listAdapterManifestKeys = `-- name: ListAdapterManifestKeys :many
SELECT id,name,classification FROM keys
WHERE org_id=?1 AND project_id=?2 AND id IN (/*SLICE:key_ids*/?) ORDER BY id
`

type ListAdapterManifestKeysParams struct {
	ChainOrg     string
	ChainProject string
	KeyIds       []string
}

type ListAdapterManifestKeysRow struct {
	ID             string
	Name           string
	Classification string
}

func (q *Queries) ListAdapterManifestKeys(ctx context.Context, arg ListAdapterManifestKeysParams) ([]ListAdapterManifestKeysRow, error) {
	query := listAdapterManifestKeys
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ChainOrg)
	queryParams = append(queryParams, arg.ChainProject)
	if len(arg.KeyIds) > 0 {
		for _, v := range arg.KeyIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:key_ids*/?", strings.Repeat(",?", len(arg.KeyIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:key_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterManifestKeysRow
	for rows.Next() {
		var i ListAdapterManifestKeysRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Classification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
