// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adapter_repository.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const adapterAdoptionConflictCount = `-- name: AdapterAdoptionConflictCount :one
SELECT COUNT(*) FROM adapter_conflicts WHERE artifact_id=?1 AND target_id=?2 AND org_id=?3 AND project_id=?4 AND environment_id=?5 AND repository_id=?6 AND destination_id=?7 AND target_generation=?8 AND surface=?9 AND effective_name=?10 AND adopted_at IS NULL
`

type AdapterAdoptionConflictCountParams struct {
	ArtifactID    string
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
	RepositoryID  int64
	DestinationID int64
	Generation    int64
	Surface       string
	EffectiveName string
}

func (q *Queries) AdapterAdoptionConflictCount(ctx context.Context, arg AdapterAdoptionConflictCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adapterAdoptionConflictCount,
		arg.ArtifactID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.DestinationID,
		arg.Generation,
		arg.Surface,
		arg.EffectiveName,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adapterAdoptionInsertJob = `-- name: AdapterAdoptionInsertJob :execrows
INSERT INTO adapter_outbox (id,org_id,project_id,environment_id,target_id,kind,authority_principal_id,generation,dedup_key,attempt_count,next_attempt_at,state,created_at) VALUES (?1,?2,?3,?4,?5,'converge',?6,?7,?8,0,?9,'queued',?10)
`

type AdapterAdoptionInsertJobParams struct {
	JobID                string
	ChainOrg             string
	ChainProject         string
	EnvironmentID        string
	TargetID             string
	AuthorityPrincipalID string
	Generation           int64
	DedupKey             string
	NextAttemptAt        string
	CreatedAt            string
}

func (q *Queries) AdapterAdoptionInsertJob(ctx context.Context, arg AdapterAdoptionInsertJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionInsertJob,
		arg.JobID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.TargetID,
		arg.AuthorityPrincipalID,
		arg.Generation,
		arg.DedupKey,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterAdoptionInsertLedger = `-- name: AdapterAdoptionInsertLedger :execrows
INSERT INTO adapter_ledger (id,org_id,project_id,environment_id,target_id,provider_origin,destination_kind,repository_id,destination_id,surface,effective_name,normalized_name,state,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,'owned',?13)
`

type AdapterAdoptionInsertLedgerParams struct {
	LedgerID        string
	ChainOrg        string
	ChainProject    string
	EnvironmentID   string
	TargetID        string
	ProviderOrigin  string
	DestinationKind string
	RepositoryID    int64
	DestinationID   int64
	Surface         string
	EffectiveName   string
	NormalizedName  string
	UpdatedAt       string
}

func (q *Queries) AdapterAdoptionInsertLedger(ctx context.Context, arg AdapterAdoptionInsertLedgerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionInsertLedger,
		arg.LedgerID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.TargetID,
		arg.ProviderOrigin,
		arg.DestinationKind,
		arg.RepositoryID,
		arg.DestinationID,
		arg.Surface,
		arg.EffectiveName,
		arg.NormalizedName,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterAdoptionMarkConflict = `-- name: AdapterAdoptionMarkConflict :execrows
UPDATE adapter_conflicts SET adopted_at=?1 WHERE artifact_id=?2 AND target_id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND surface=?7 AND effective_name=?8 AND adopted_at IS NULL
`

type AdapterAdoptionMarkConflictParams struct {
	AdoptedAt     sql.NullString
	ArtifactID    string
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
	Surface       string
	EffectiveName string
}

func (q *Queries) AdapterAdoptionMarkConflict(ctx context.Context, arg AdapterAdoptionMarkConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionMarkConflict,
		arg.AdoptedAt,
		arg.ArtifactID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.Surface,
		arg.EffectiveName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterAdoptionSupersedeJob = `-- name: AdapterAdoptionSupersedeJob :execrows
UPDATE adapter_outbox SET state='superseded',finished_at=?1,lease_owner=NULL,lease_expires_at=NULL WHERE id=?2 AND target_id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND state IN ('queued','running')
`

type AdapterAdoptionSupersedeJobParams struct {
	FinishedAt    sql.NullString
	JobID         string
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

func (q *Queries) AdapterAdoptionSupersedeJob(ctx context.Context, arg AdapterAdoptionSupersedeJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionSupersedeJob,
		arg.FinishedAt,
		arg.JobID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterAdoptionTarget = `-- name: AdapterAdoptionTarget :one
SELECT t.adapter_id,t.environment_id,a.origin,t.destination_kind,t.repository_id,t.destination_id,t.generation,CAST(CASE WHEN t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1 THEN 1 ELSE 0 END AS INTEGER) AS provider_busy,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS prior_job FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id WHERE t.id=?2 AND t.org_id=?3 AND t.project_id=?4 AND t.state='active'
`

type AdapterAdoptionTargetParams struct {
	At           sql.NullString
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterAdoptionTargetRow struct {
	AdapterID       string
	EnvironmentID   string
	Origin          string
	DestinationKind string
	RepositoryID    int64
	DestinationID   int64
	Generation      int64
	ProviderBusy    int64
	PriorJob        string
}

func (q *Queries) AdapterAdoptionTarget(ctx context.Context, arg AdapterAdoptionTargetParams) (AdapterAdoptionTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterAdoptionTarget,
		arg.At,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	var i AdapterAdoptionTargetRow
	err := row.Scan(
		&i.AdapterID,
		&i.EnvironmentID,
		&i.Origin,
		&i.DestinationKind,
		&i.RepositoryID,
		&i.DestinationID,
		&i.Generation,
		&i.ProviderBusy,
		&i.PriorJob,
	)
	return i, err
}

const adapterAdoptionUpdateAuthority = `-- name: AdapterAdoptionUpdateAuthority :execrows
UPDATE adapters SET authority_principal_id=?1 WHERE id=?2 AND org_id=?3 AND project_id=?4
`

type AdapterAdoptionUpdateAuthorityParams struct {
	AuthorityPrincipalID string
	AdapterID            string
	ChainOrg             string
	ChainProject         string
}

func (q *Queries) AdapterAdoptionUpdateAuthority(ctx context.Context, arg AdapterAdoptionUpdateAuthorityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionUpdateAuthority,
		arg.AuthorityPrincipalID,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterAdoptionUpdateTarget = `-- name: AdapterAdoptionUpdateTarget :execrows
UPDATE adapter_targets SET generation=?1,sync_status='converging',failure_names='[]',active_job_id=?2,provider_lease_job_id=NULL,provider_lease_effect_id=NULL,provider_lease_expires_at=NULL WHERE id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND generation=?7 AND (provider_lease_job_id IS NULL OR provider_lease_expires_at<=?8)
`

type AdapterAdoptionUpdateTargetParams struct {
	NextGeneration     int64
	JobID              sql.NullString
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
	At                 sql.NullString
}

func (q *Queries) AdapterAdoptionUpdateTarget(ctx context.Context, arg AdapterAdoptionUpdateTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterAdoptionUpdateTarget,
		arg.NextGeneration,
		arg.JobID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterBeginConfigureEffect = `-- name: AdapterBeginConfigureEffect :exec
INSERT INTO adapter_configure_fences (target_id,org_id,project_id,environment_id,destination_kind,destination_owner,destination_name,destination_environment,generation,effect_id,lease_expires_at,state,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,'leased',?12)
`

type AdapterBeginConfigureEffectParams struct {
	TargetID               string
	ChainOrg               string
	ChainProject           string
	EnvironmentID          string
	DestinationKind        string
	DestinationOwner       string
	DestinationName        string
	DestinationEnvironment string
	Generation             int64
	EffectID               string
	LeaseExpiresAt         string
	CreatedAt              string
}

func (q *Queries) AdapterBeginConfigureEffect(ctx context.Context, arg AdapterBeginConfigureEffectParams) error {
	_, err := q.db.ExecContext(ctx, adapterBeginConfigureEffect,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.DestinationKind,
		arg.DestinationOwner,
		arg.DestinationName,
		arg.DestinationEnvironment,
		arg.Generation,
		arg.EffectID,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const adapterConfiguration = `-- name: AdapterConfiguration :one
SELECT id,provider,origin,CAST(CASE WHEN credential_ciphertext IS NULL THEN 0 ELSE 1 END AS INTEGER) AS credential_present,credential_set_at,credential_expires_at,authority_principal_id,state,created_at,spki_pin,ca_bundle_pem,CAST(CASE WHEN allow_personal_token THEN 1 ELSE 0 END AS INTEGER) AS allow_personal_token,credential_ciphertext FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state<>'tombstoned'
`

type AdapterConfigurationParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterConfigurationRow struct {
	ID                   string
	Provider             string
	Origin               string
	CredentialPresent    int64
	CredentialSetAt      sql.NullString
	CredentialExpiresAt  sql.NullString
	AuthorityPrincipalID string
	State                string
	CreatedAt            string
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
	CredentialCiphertext []byte
}

func (q *Queries) AdapterConfiguration(ctx context.Context, arg AdapterConfigurationParams) (AdapterConfigurationRow, error) {
	row := q.db.QueryRowContext(ctx, adapterConfiguration, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var i AdapterConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Origin,
		&i.CredentialPresent,
		&i.CredentialSetAt,
		&i.CredentialExpiresAt,
		&i.AuthorityPrincipalID,
		&i.State,
		&i.CreatedAt,
		&i.SpkiPin,
		&i.CaBundlePem,
		&i.AllowPersonalToken,
		&i.CredentialCiphertext,
	)
	return i, err
}

const adapterConflicts = `-- name: AdapterConflicts :many
SELECT c.artifact_id,c.target_id,c.job_id,c.destination_id,c.repository_id,c.target_generation,c.surface,c.effective_name,c.created_at FROM adapter_conflicts c JOIN adapter_targets t ON t.id=c.target_id AND t.org_id=c.org_id AND t.project_id=c.project_id WHERE c.target_id=?1 AND c.org_id=?2 AND c.project_id=?3 AND c.adopted_at IS NULL AND c.target_generation=t.generation ORDER BY c.created_at,c.artifact_id,c.surface,c.effective_name
`

type AdapterConflictsParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterConflictsRow struct {
	ArtifactID       string
	TargetID         string
	JobID            sql.NullString
	DestinationID    int64
	RepositoryID     int64
	TargetGeneration int64
	Surface          string
	EffectiveName    string
	CreatedAt        string
}

func (q *Queries) AdapterConflicts(ctx context.Context, arg AdapterConflictsParams) ([]AdapterConflictsRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterConflicts, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterConflictsRow
	for rows.Next() {
		var i AdapterConflictsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.TargetID,
			&i.JobID,
			&i.DestinationID,
			&i.RepositoryID,
			&i.TargetGeneration,
			&i.Surface,
			&i.EffectiveName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterCreate = `-- name: AdapterCreate :exec
INSERT INTO adapters (id,org_id,project_id,provider,origin,credential_ciphertext,credential_set_at,credential_expires_at,authority_principal_id,state,created_at,spki_pin,ca_bundle_pem,allow_personal_token) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,'active',?10,?11,?12,?13)
`

type AdapterCreateParams struct {
	AdapterID            string
	ChainOrg             string
	ChainProject         string
	Provider             string
	Origin               string
	CredentialCiphertext []byte
	CredentialSetAt      sql.NullString
	CredentialExpiresAt  sql.NullString
	AuthorityPrincipalID string
	CreatedAt            string
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
}

func (q *Queries) AdapterCreate(ctx context.Context, arg AdapterCreateParams) error {
	_, err := q.db.ExecContext(ctx, adapterCreate,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.Provider,
		arg.Origin,
		arg.CredentialCiphertext,
		arg.CredentialSetAt,
		arg.CredentialExpiresAt,
		arg.AuthorityPrincipalID,
		arg.CreatedAt,
		arg.SpkiPin,
		arg.CaBundlePem,
		arg.AllowPersonalToken,
	)
	return err
}

const adapterDeleteTargetKeys = `-- name: AdapterDeleteTargetKeys :exec
DELETE FROM adapter_target_keys WHERE target_id=?1 AND org_id=?2 AND project_id=?3 AND environment_id=?4
`

type AdapterDeleteTargetKeysParams struct {
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

func (q *Queries) AdapterDeleteTargetKeys(ctx context.Context, arg AdapterDeleteTargetKeysParams) error {
	_, err := q.db.ExecContext(ctx, adapterDeleteTargetKeys,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	return err
}

const adapterEnqueueTarget = `-- name: AdapterEnqueueTarget :execrows
UPDATE adapter_targets SET generation=?1,sync_status='converging',failure_names='[]',active_job_id=?2 WHERE id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND generation=?7
`

type AdapterEnqueueTargetParams struct {
	NextGeneration     int64
	JobID              sql.NullString
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
}

func (q *Queries) AdapterEnqueueTarget(ctx context.Context, arg AdapterEnqueueTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterEnqueueTarget,
		arg.NextGeneration,
		arg.JobID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterEnvironments = `-- name: AdapterEnvironments :many
SELECT DISTINCT environment_id FROM adapter_targets WHERE adapter_id=?1 AND org_id=?2 AND project_id=?3 AND state='active' ORDER BY environment_id
`

type AdapterEnvironmentsParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterEnvironments(ctx context.Context, arg AdapterEnvironmentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, adapterEnvironments, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var environment_id string
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterEraseUnusedCredential = `-- name: AdapterEraseUnusedCredential :exec
UPDATE adapters SET credential_ciphertext=NULL,credential_set_at=NULL,credential_expires_at=NULL WHERE adapters.id=?1 AND adapters.org_id=?2 AND adapters.project_id=?3 AND NOT EXISTS (SELECT 1 FROM adapter_targets WHERE adapter_id=?1 AND state<>'tombstoned') AND NOT EXISTS (SELECT 1 FROM adapter_outbox j JOIN adapter_targets t ON t.id=j.target_id AND t.org_id=j.org_id AND t.project_id=j.project_id AND t.environment_id=j.environment_id WHERE t.adapter_id=?1 AND j.kind='scrub' AND j.state IN ('queued','running'))
`

type AdapterEraseUnusedCredentialParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterEraseUnusedCredential(ctx context.Context, arg AdapterEraseUnusedCredentialParams) error {
	_, err := q.db.ExecContext(ctx, adapterEraseUnusedCredential, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	return err
}

const adapterFinishConfigureEffect = `-- name: AdapterFinishConfigureEffect :execrows
UPDATE adapter_configure_fences SET state=?1,completed_at=?2 WHERE target_id=?3 AND effect_id=?4 AND org_id=?5 AND project_id=?6 AND state='leased'
`

type AdapterFinishConfigureEffectParams struct {
	Outcome      string
	CompletedAt  sql.NullString
	TargetID     string
	EffectID     string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterFinishConfigureEffect(ctx context.Context, arg AdapterFinishConfigureEffectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterFinishConfigureEffect,
		arg.Outcome,
		arg.CompletedAt,
		arg.TargetID,
		arg.EffectID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterGet = `-- name: AdapterGet :one
SELECT id,provider,origin,CAST(CASE WHEN credential_ciphertext IS NULL THEN 0 ELSE 1 END AS INTEGER) AS credential_present,credential_set_at,credential_expires_at,authority_principal_id,state,created_at,spki_pin,ca_bundle_pem,CAST(CASE WHEN allow_personal_token THEN 1 ELSE 0 END AS INTEGER) AS allow_personal_token FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state<>'tombstoned'
`

type AdapterGetParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterGetRow struct {
	ID                   string
	Provider             string
	Origin               string
	CredentialPresent    int64
	CredentialSetAt      sql.NullString
	CredentialExpiresAt  sql.NullString
	AuthorityPrincipalID string
	State                string
	CreatedAt            string
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
}

func (q *Queries) AdapterGet(ctx context.Context, arg AdapterGetParams) (AdapterGetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterGet, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var i AdapterGetRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Origin,
		&i.CredentialPresent,
		&i.CredentialSetAt,
		&i.CredentialExpiresAt,
		&i.AuthorityPrincipalID,
		&i.State,
		&i.CreatedAt,
		&i.SpkiPin,
		&i.CaBundlePem,
		&i.AllowPersonalToken,
	)
	return i, err
}

const adapterGetActiveForUpdate = `-- name: AdapterGetActiveForUpdate :one
SELECT id,provider,origin,CAST(CASE WHEN credential_ciphertext IS NULL THEN 0 ELSE 1 END AS INTEGER) AS credential_present,credential_set_at,credential_expires_at,authority_principal_id,state,created_at,spki_pin,ca_bundle_pem,CAST(CASE WHEN allow_personal_token THEN 1 ELSE 0 END AS INTEGER) AS allow_personal_token FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterGetActiveForUpdateParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterGetActiveForUpdateRow struct {
	ID                   string
	Provider             string
	Origin               string
	CredentialPresent    int64
	CredentialSetAt      sql.NullString
	CredentialExpiresAt  sql.NullString
	AuthorityPrincipalID string
	State                string
	CreatedAt            string
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
}

func (q *Queries) AdapterGetActiveForUpdate(ctx context.Context, arg AdapterGetActiveForUpdateParams) (AdapterGetActiveForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, adapterGetActiveForUpdate, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var i AdapterGetActiveForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Origin,
		&i.CredentialPresent,
		&i.CredentialSetAt,
		&i.CredentialExpiresAt,
		&i.AuthorityPrincipalID,
		&i.State,
		&i.CreatedAt,
		&i.SpkiPin,
		&i.CaBundlePem,
		&i.AllowPersonalToken,
	)
	return i, err
}

const adapterGetActiveTargetForUpdate = `-- name: AdapterGetActiveTargetForUpdate :one
SELECT t.id,t.adapter_id,t.environment_id,a.provider,a.origin,t.destination_kind,t.destination_owner,t.destination_name,t.destination_environment,t.destination_id,t.repository_id,t.visibility,t.selected_repository_ids,t.name_prefix,t.generation,t.state,t.sync_status,t.converged_revision,t.failure_names,t.warnings,a.authority_principal_id,t.paused_at,t.last_attempted_revision,t.last_attempted_at,t.last_error_class,CAST(CASE WHEN t.drift_attention THEN 1 ELSE 0 END AS INTEGER) AS drift_attention,CAST(COALESCE(j.state,'') AS TEXT) AS active_job_state,j.next_attempt_at,CAST(COALESCE(j.attempt_count,0) AS INTEGER) AS attempt_count,t.destination_scope,CAST(CASE WHEN t.variable_protected THEN 1 ELSE 0 END AS INTEGER) AS variable_protected,CAST(CASE WHEN t.variable_hidden THEN 1 ELSE 0 END AS INTEGER) AS variable_hidden,CAST(CASE WHEN t.variable_expand THEN 1 ELSE 0 END AS INTEGER) AS variable_expand FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id LEFT JOIN adapter_outbox j ON j.id=t.active_job_id AND j.org_id=t.org_id AND j.project_id=t.project_id AND j.environment_id=t.environment_id WHERE t.id=?1 AND t.org_id=?2 AND t.project_id=?3 AND t.state='active'
`

type AdapterGetActiveTargetForUpdateParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterGetActiveTargetForUpdateRow struct {
	ID                     string
	AdapterID              string
	EnvironmentID          string
	Provider               string
	Origin                 string
	DestinationKind        string
	DestinationOwner       string
	DestinationName        string
	DestinationEnvironment string
	DestinationID          int64
	RepositoryID           int64
	Visibility             string
	SelectedRepositoryIds  string
	NamePrefix             string
	Generation             int64
	State                  string
	SyncStatus             string
	ConvergedRevision      sql.NullInt64
	FailureNames           string
	Warnings               string
	AuthorityPrincipalID   string
	PausedAt               sql.NullString
	LastAttemptedRevision  sql.NullInt64
	LastAttemptedAt        sql.NullString
	LastErrorClass         sql.NullString
	DriftAttention         int64
	ActiveJobState         string
	NextAttemptAt          sql.NullString
	AttemptCount           int64
	DestinationScope       string
	VariableProtected      int64
	VariableHidden         int64
	VariableExpand         int64
}

func (q *Queries) AdapterGetActiveTargetForUpdate(ctx context.Context, arg AdapterGetActiveTargetForUpdateParams) (AdapterGetActiveTargetForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, adapterGetActiveTargetForUpdate, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	var i AdapterGetActiveTargetForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.EnvironmentID,
		&i.Provider,
		&i.Origin,
		&i.DestinationKind,
		&i.DestinationOwner,
		&i.DestinationName,
		&i.DestinationEnvironment,
		&i.DestinationID,
		&i.RepositoryID,
		&i.Visibility,
		&i.SelectedRepositoryIds,
		&i.NamePrefix,
		&i.Generation,
		&i.State,
		&i.SyncStatus,
		&i.ConvergedRevision,
		&i.FailureNames,
		&i.Warnings,
		&i.AuthorityPrincipalID,
		&i.PausedAt,
		&i.LastAttemptedRevision,
		&i.LastAttemptedAt,
		&i.LastErrorClass,
		&i.DriftAttention,
		&i.ActiveJobState,
		&i.NextAttemptAt,
		&i.AttemptCount,
		&i.DestinationScope,
		&i.VariableProtected,
		&i.VariableHidden,
		&i.VariableExpand,
	)
	return i, err
}

const adapterGetTarget = `-- name: AdapterGetTarget :one
SELECT t.id,t.adapter_id,t.environment_id,a.provider,a.origin,t.destination_kind,t.destination_owner,t.destination_name,t.destination_environment,t.destination_id,t.repository_id,t.visibility,t.selected_repository_ids,t.name_prefix,t.generation,t.state,t.sync_status,t.converged_revision,t.failure_names,t.warnings,a.authority_principal_id,t.paused_at,t.last_attempted_revision,t.last_attempted_at,t.last_error_class,CAST(CASE WHEN t.drift_attention THEN 1 ELSE 0 END AS INTEGER) AS drift_attention,CAST(COALESCE(j.state,'') AS TEXT) AS active_job_state,j.next_attempt_at,CAST(COALESCE(j.attempt_count,0) AS INTEGER) AS attempt_count,t.destination_scope,CAST(CASE WHEN t.variable_protected THEN 1 ELSE 0 END AS INTEGER) AS variable_protected,CAST(CASE WHEN t.variable_hidden THEN 1 ELSE 0 END AS INTEGER) AS variable_hidden,CAST(CASE WHEN t.variable_expand THEN 1 ELSE 0 END AS INTEGER) AS variable_expand FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id LEFT JOIN adapter_outbox j ON j.id=t.active_job_id AND j.org_id=t.org_id AND j.project_id=t.project_id AND j.environment_id=t.environment_id WHERE t.id=?1 AND t.org_id=?2 AND t.project_id=?3
`

type AdapterGetTargetParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterGetTargetRow struct {
	ID                     string
	AdapterID              string
	EnvironmentID          string
	Provider               string
	Origin                 string
	DestinationKind        string
	DestinationOwner       string
	DestinationName        string
	DestinationEnvironment string
	DestinationID          int64
	RepositoryID           int64
	Visibility             string
	SelectedRepositoryIds  string
	NamePrefix             string
	Generation             int64
	State                  string
	SyncStatus             string
	ConvergedRevision      sql.NullInt64
	FailureNames           string
	Warnings               string
	AuthorityPrincipalID   string
	PausedAt               sql.NullString
	LastAttemptedRevision  sql.NullInt64
	LastAttemptedAt        sql.NullString
	LastErrorClass         sql.NullString
	DriftAttention         int64
	ActiveJobState         string
	NextAttemptAt          sql.NullString
	AttemptCount           int64
	DestinationScope       string
	VariableProtected      int64
	VariableHidden         int64
	VariableExpand         int64
}

func (q *Queries) AdapterGetTarget(ctx context.Context, arg AdapterGetTargetParams) (AdapterGetTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterGetTarget, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	var i AdapterGetTargetRow
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.EnvironmentID,
		&i.Provider,
		&i.Origin,
		&i.DestinationKind,
		&i.DestinationOwner,
		&i.DestinationName,
		&i.DestinationEnvironment,
		&i.DestinationID,
		&i.RepositoryID,
		&i.Visibility,
		&i.SelectedRepositoryIds,
		&i.NamePrefix,
		&i.Generation,
		&i.State,
		&i.SyncStatus,
		&i.ConvergedRevision,
		&i.FailureNames,
		&i.Warnings,
		&i.AuthorityPrincipalID,
		&i.PausedAt,
		&i.LastAttemptedRevision,
		&i.LastAttemptedAt,
		&i.LastErrorClass,
		&i.DriftAttention,
		&i.ActiveJobState,
		&i.NextAttemptAt,
		&i.AttemptCount,
		&i.DestinationScope,
		&i.VariableProtected,
		&i.VariableHidden,
		&i.VariableExpand,
	)
	return i, err
}

const adapterHealthCounts = `-- name: AdapterHealthCounts :one
SELECT CAST((SELECT COUNT(*) FROM adapter_targets WHERE state='active' AND sync_status='failed' AND paused_at IS NULL) AS INTEGER) AS targets_failed,CAST((SELECT COUNT(*) FROM adapter_targets WHERE state='active' AND paused_at IS NOT NULL) AS INTEGER) AS targets_paused,CAST((SELECT COUNT(*) FROM adapter_targets WHERE state='active' AND drift_attention=1) AS INTEGER) AS targets_attention,CAST((SELECT COUNT(*) FROM adapter_outbox WHERE state='queued') AS INTEGER) AS jobs_queued
`

type AdapterHealthCountsRow struct {
	TargetsFailed    int64
	TargetsPaused    int64
	TargetsAttention int64
	JobsQueued       int64
}

// hikyo:reason Verified instance HealthCounts authority reads only aggregate target/outbox counts for operator gauges; no tenant rows or writes are returned.
// hikyo:instance-scoped
func (q *Queries) AdapterHealthCounts(ctx context.Context) (AdapterHealthCountsRow, error) {
	row := q.db.QueryRowContext(ctx, adapterHealthCounts)
	var i AdapterHealthCountsRow
	err := row.Scan(
		&i.TargetsFailed,
		&i.TargetsPaused,
		&i.TargetsAttention,
		&i.JobsQueued,
	)
	return i, err
}

const adapterInsertConflict = `-- name: AdapterInsertConflict :execrows
INSERT INTO adapter_conflicts (id,artifact_id,org_id,project_id,environment_id,target_id,job_id,destination_id,repository_id,target_generation,surface,effective_name,created_at) VALUES (?1,?2,?3,?4,?5,?6,NULL,?7,?8,?9,?10,?11,?12)
`

type AdapterInsertConflictParams struct {
	ID               string
	ArtifactID       string
	ChainOrg         string
	ChainProject     string
	EnvironmentID    string
	TargetID         string
	DestinationID    int64
	RepositoryID     int64
	TargetGeneration int64
	Surface          string
	EffectiveName    string
	CreatedAt        string
}

func (q *Queries) AdapterInsertConflict(ctx context.Context, arg AdapterInsertConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterInsertConflict,
		arg.ID,
		arg.ArtifactID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.TargetID,
		arg.DestinationID,
		arg.RepositoryID,
		arg.TargetGeneration,
		arg.Surface,
		arg.EffectiveName,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterInsertScrubJob = `-- name: AdapterInsertScrubJob :execrows
INSERT INTO adapter_outbox (id,org_id,project_id,environment_id,target_id,kind,authority_principal_id,generation,dedup_key,attempt_count,next_attempt_at,state,created_at) VALUES (?1,?2,?3,?4,?5,'scrub',?6,?7,?8,0,?9,'queued',?10)
`

type AdapterInsertScrubJobParams struct {
	JobID                string
	ChainOrg             string
	ChainProject         string
	EnvironmentID        string
	TargetID             string
	AuthorityPrincipalID string
	Generation           int64
	DedupKey             string
	NextAttemptAt        string
	CreatedAt            string
}

func (q *Queries) AdapterInsertScrubJob(ctx context.Context, arg AdapterInsertScrubJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterInsertScrubJob,
		arg.JobID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.TargetID,
		arg.AuthorityPrincipalID,
		arg.Generation,
		arg.DedupKey,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterInsertTarget = `-- name: AdapterInsertTarget :exec
INSERT INTO adapter_targets (id,org_id,project_id,environment_id,adapter_id,destination_kind,destination_owner,destination_name,destination_environment,destination_id,repository_id,visibility,selected_repository_ids,name_prefix,generation,state,sync_status,created_at,destination_scope,variable_protected,variable_hidden,variable_expand) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,1,'active','never',?15,?16,?17,?18,?19)
`

type AdapterInsertTargetParams struct {
	TargetID               string
	ChainOrg               string
	ChainProject           string
	EnvironmentID          string
	AdapterID              string
	DestinationKind        string
	DestinationOwner       string
	DestinationName        string
	DestinationEnvironment string
	DestinationID          int64
	RepositoryID           int64
	Visibility             string
	SelectedRepositoryIds  string
	NamePrefix             string
	CreatedAt              string
	DestinationScope       string
	VariableProtected      int64
	VariableHidden         int64
	VariableExpand         int64
}

func (q *Queries) AdapterInsertTarget(ctx context.Context, arg AdapterInsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, adapterInsertTarget,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.AdapterID,
		arg.DestinationKind,
		arg.DestinationOwner,
		arg.DestinationName,
		arg.DestinationEnvironment,
		arg.DestinationID,
		arg.RepositoryID,
		arg.Visibility,
		arg.SelectedRepositoryIds,
		arg.NamePrefix,
		arg.CreatedAt,
		arg.DestinationScope,
		arg.VariableProtected,
		arg.VariableHidden,
		arg.VariableExpand,
	)
	return err
}

const adapterInsertTargetKey = `-- name: AdapterInsertTargetKey :exec
INSERT INTO adapter_target_keys (org_id,project_id,environment_id,target_id,adapter_id,key_id) VALUES (?1,?2,?3,?4,?5,?6)
`

type AdapterInsertTargetKeyParams struct {
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
	TargetID      string
	AdapterID     string
	KeyID         string
}

func (q *Queries) AdapterInsertTargetKey(ctx context.Context, arg AdapterInsertTargetKeyParams) error {
	_, err := q.db.ExecContext(ctx, adapterInsertTargetKey,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.TargetID,
		arg.AdapterID,
		arg.KeyID,
	)
	return err
}

const adapterList = `-- name: AdapterList :many
SELECT id,provider,origin,CAST(CASE WHEN credential_ciphertext IS NULL THEN 0 ELSE 1 END AS INTEGER) AS credential_present,credential_set_at,credential_expires_at,authority_principal_id,state,created_at,spki_pin,ca_bundle_pem,CAST(CASE WHEN allow_personal_token THEN 1 ELSE 0 END AS INTEGER) AS allow_personal_token FROM adapters WHERE org_id=?1 AND project_id=?2 AND state<>'tombstoned' ORDER BY id
`

type AdapterListParams struct {
	ChainOrg     string
	ChainProject string
}

type AdapterListRow struct {
	ID                   string
	Provider             string
	Origin               string
	CredentialPresent    int64
	CredentialSetAt      sql.NullString
	CredentialExpiresAt  sql.NullString
	AuthorityPrincipalID string
	State                string
	CreatedAt            string
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
}

func (q *Queries) AdapterList(ctx context.Context, arg AdapterListParams) ([]AdapterListRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterList, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterListRow
	for rows.Next() {
		var i AdapterListRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Origin,
			&i.CredentialPresent,
			&i.CredentialSetAt,
			&i.CredentialExpiresAt,
			&i.AuthorityPrincipalID,
			&i.State,
			&i.CreatedAt,
			&i.SpkiPin,
			&i.CaBundlePem,
			&i.AllowPersonalToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterListForReencrypt = `-- name: AdapterListForReencrypt :many
SELECT id,credential_ciphertext FROM adapters WHERE org_id=?1 AND project_id=?2 AND id>?3 ORDER BY id LIMIT ?4
`

type AdapterListForReencryptParams struct {
	ChainOrg     string
	ChainProject string
	Cursor       string
	PageLimit    int64
}

type AdapterListForReencryptRow struct {
	ID                   string
	CredentialCiphertext []byte
}

func (q *Queries) AdapterListForReencrypt(ctx context.Context, arg AdapterListForReencryptParams) ([]AdapterListForReencryptRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterListForReencrypt,
		arg.ChainOrg,
		arg.ChainProject,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterListForReencryptRow
	for rows.Next() {
		var i AdapterListForReencryptRow
		if err := rows.Scan(&i.ID, &i.CredentialCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterListMovesForReencrypt = `-- name: AdapterListMovesForReencrypt :many
SELECT id,adapter_id,pending_credential_ciphertext FROM adapter_route_moves WHERE org_id=?1 AND project_id=?2 AND id>?3 ORDER BY id LIMIT ?4
`

type AdapterListMovesForReencryptParams struct {
	ChainOrg     string
	ChainProject string
	Cursor       string
	PageLimit    int64
}

type AdapterListMovesForReencryptRow struct {
	ID                          string
	AdapterID                   string
	PendingCredentialCiphertext []byte
}

func (q *Queries) AdapterListMovesForReencrypt(ctx context.Context, arg AdapterListMovesForReencryptParams) ([]AdapterListMovesForReencryptRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterListMovesForReencrypt,
		arg.ChainOrg,
		arg.ChainProject,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterListMovesForReencryptRow
	for rows.Next() {
		var i AdapterListMovesForReencryptRow
		if err := rows.Scan(&i.ID, &i.AdapterID, &i.PendingCredentialCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterListTargets = `-- name: AdapterListTargets :many
SELECT t.id,t.adapter_id,t.environment_id,a.provider,a.origin,t.destination_kind,t.destination_owner,t.destination_name,t.destination_environment,t.destination_id,t.repository_id,t.visibility,t.selected_repository_ids,t.name_prefix,t.generation,t.state,t.sync_status,t.converged_revision,t.failure_names,t.warnings,a.authority_principal_id,t.paused_at,t.last_attempted_revision,t.last_attempted_at,t.last_error_class,CAST(CASE WHEN t.drift_attention THEN 1 ELSE 0 END AS INTEGER) AS drift_attention,CAST(COALESCE(j.state,'') AS TEXT) AS active_job_state,j.next_attempt_at,CAST(COALESCE(j.attempt_count,0) AS INTEGER) AS attempt_count,t.destination_scope,CAST(CASE WHEN t.variable_protected THEN 1 ELSE 0 END AS INTEGER) AS variable_protected,CAST(CASE WHEN t.variable_hidden THEN 1 ELSE 0 END AS INTEGER) AS variable_hidden,CAST(CASE WHEN t.variable_expand THEN 1 ELSE 0 END AS INTEGER) AS variable_expand FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id LEFT JOIN adapter_outbox j ON j.id=t.active_job_id AND j.org_id=t.org_id AND j.project_id=t.project_id AND j.environment_id=t.environment_id WHERE t.adapter_id=?1 AND t.org_id=?2 AND t.project_id=?3 AND t.state='active' ORDER BY t.id
`

type AdapterListTargetsParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterListTargetsRow struct {
	ID                     string
	AdapterID              string
	EnvironmentID          string
	Provider               string
	Origin                 string
	DestinationKind        string
	DestinationOwner       string
	DestinationName        string
	DestinationEnvironment string
	DestinationID          int64
	RepositoryID           int64
	Visibility             string
	SelectedRepositoryIds  string
	NamePrefix             string
	Generation             int64
	State                  string
	SyncStatus             string
	ConvergedRevision      sql.NullInt64
	FailureNames           string
	Warnings               string
	AuthorityPrincipalID   string
	PausedAt               sql.NullString
	LastAttemptedRevision  sql.NullInt64
	LastAttemptedAt        sql.NullString
	LastErrorClass         sql.NullString
	DriftAttention         int64
	ActiveJobState         string
	NextAttemptAt          sql.NullString
	AttemptCount           int64
	DestinationScope       string
	VariableProtected      int64
	VariableHidden         int64
	VariableExpand         int64
}

func (q *Queries) AdapterListTargets(ctx context.Context, arg AdapterListTargetsParams) ([]AdapterListTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterListTargets, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterListTargetsRow
	for rows.Next() {
		var i AdapterListTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdapterID,
			&i.EnvironmentID,
			&i.Provider,
			&i.Origin,
			&i.DestinationKind,
			&i.DestinationOwner,
			&i.DestinationName,
			&i.DestinationEnvironment,
			&i.DestinationID,
			&i.RepositoryID,
			&i.Visibility,
			&i.SelectedRepositoryIds,
			&i.NamePrefix,
			&i.Generation,
			&i.State,
			&i.SyncStatus,
			&i.ConvergedRevision,
			&i.FailureNames,
			&i.Warnings,
			&i.AuthorityPrincipalID,
			&i.PausedAt,
			&i.LastAttemptedRevision,
			&i.LastAttemptedAt,
			&i.LastErrorClass,
			&i.DriftAttention,
			&i.ActiveJobState,
			&i.NextAttemptAt,
			&i.AttemptCount,
			&i.DestinationScope,
			&i.VariableProtected,
			&i.VariableHidden,
			&i.VariableExpand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterManualTarget = `-- name: AdapterManualTarget :one
SELECT t.id,t.environment_id,t.generation,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS active_job_id,CAST(CASE WHEN t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1 THEN 1 ELSE 0 END AS INTEGER) AS provider_busy,CAST(CASE WHEN t.paused_at IS NULL THEN 0 ELSE 1 END AS INTEGER) AS paused FROM adapter_targets t WHERE t.id=?2 AND t.org_id=?3 AND t.project_id=?4 AND t.state='active'
`

type AdapterManualTargetParams struct {
	At           sql.NullString
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterManualTargetRow struct {
	ID            string
	EnvironmentID string
	Generation    int64
	ActiveJobID   string
	ProviderBusy  int64
	Paused        int64
}

func (q *Queries) AdapterManualTarget(ctx context.Context, arg AdapterManualTargetParams) (AdapterManualTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterManualTarget,
		arg.At,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	var i AdapterManualTargetRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Generation,
		&i.ActiveJobID,
		&i.ProviderBusy,
		&i.Paused,
	)
	return i, err
}

const adapterMapping = `-- name: AdapterMapping :many
SELECT e.key_id,e.key_name,e.classification FROM snapshot_entries e JOIN adapter_target_keys k ON k.key_id=e.key_id AND k.target_id=?1 AND k.org_id=e.org_id AND k.project_id=e.project_id AND k.environment_id=e.environment_id JOIN adapter_targets t ON t.id=k.target_id AND t.org_id=k.org_id AND t.project_id=k.project_id AND t.environment_id=k.environment_id WHERE t.org_id=?2 AND t.project_id=?3 AND e.snapshot_id=(SELECT latest.id FROM snapshots latest WHERE latest.org_id=t.org_id AND latest.project_id=t.project_id AND latest.environment_id=t.environment_id AND latest.payload_present=1 ORDER BY latest.revision DESC LIMIT 1) ORDER BY e.key_name
`

type AdapterMappingParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterMappingRow struct {
	KeyID          string
	KeyName        string
	Classification string
}

func (q *Queries) AdapterMapping(ctx context.Context, arg AdapterMappingParams) ([]AdapterMappingRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterMapping, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterMappingRow
	for rows.Next() {
		var i AdapterMappingRow
		if err := rows.Scan(&i.KeyID, &i.KeyName, &i.Classification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterMarkTombstoned = `-- name: AdapterMarkTombstoned :execrows
UPDATE adapters SET state='tombstoned' WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterMarkTombstonedParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterMarkTombstoned(ctx context.Context, arg AdapterMarkTombstonedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterMarkTombstoned, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterOrphans = `-- name: AdapterOrphans :many
SELECT surface,effective_name FROM adapter_ledger WHERE target_id=?1 AND org_id=?2 AND project_id=?3 AND environment_id=?4 AND state IN ('owned','dispatched') ORDER BY surface,effective_name
`

type AdapterOrphansParams struct {
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

type AdapterOrphansRow struct {
	Surface       string
	EffectiveName string
}

func (q *Queries) AdapterOrphans(ctx context.Context, arg AdapterOrphansParams) ([]AdapterOrphansRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterOrphans,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterOrphansRow
	for rows.Next() {
		var i AdapterOrphansRow
		if err := rows.Scan(&i.Surface, &i.EffectiveName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterPauseTarget = `-- name: AdapterPauseTarget :one
SELECT t.adapter_id,t.id,t.environment_id,a.authority_principal_id,t.generation,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS active_job_id,CAST(CASE WHEN t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1 THEN 1 ELSE 0 END AS INTEGER) AS provider_busy,CAST(CASE WHEN t.paused_at IS NULL THEN 0 ELSE 1 END AS INTEGER) AS paused FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id WHERE t.id=?2 AND t.org_id=?3 AND t.project_id=?4 AND t.state='active'
`

type AdapterPauseTargetParams struct {
	At           sql.NullString
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterPauseTargetRow struct {
	AdapterID            string
	ID                   string
	EnvironmentID        string
	AuthorityPrincipalID string
	Generation           int64
	ActiveJobID          string
	ProviderBusy         int64
	Paused               int64
}

func (q *Queries) AdapterPauseTarget(ctx context.Context, arg AdapterPauseTargetParams) (AdapterPauseTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterPauseTarget,
		arg.At,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	var i AdapterPauseTargetRow
	err := row.Scan(
		&i.AdapterID,
		&i.ID,
		&i.EnvironmentID,
		&i.AuthorityPrincipalID,
		&i.Generation,
		&i.ActiveJobID,
		&i.ProviderBusy,
		&i.Paused,
	)
	return i, err
}

const adapterPauseTargetUpdate = `-- name: AdapterPauseTargetUpdate :execrows
UPDATE adapter_targets SET paused_at=?1,generation=?2,active_job_id=NULL,provider_lease_job_id=NULL,provider_lease_effect_id=NULL,provider_lease_expires_at=NULL WHERE id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND generation=?7 AND state='active' AND paused_at IS NULL AND (provider_lease_job_id IS NULL OR provider_lease_expires_at<=?8)
`

type AdapterPauseTargetUpdateParams struct {
	PausedAt           sql.NullString
	NextGeneration     int64
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
	At                 sql.NullString
}

func (q *Queries) AdapterPauseTargetUpdate(ctx context.Context, arg AdapterPauseTargetUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterPauseTargetUpdate,
		arg.PausedAt,
		arg.NextGeneration,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterPlanCredential = `-- name: AdapterPlanCredential :one
SELECT credential_ciphertext,spki_pin,ca_bundle_pem,CAST(CASE WHEN allow_personal_token THEN 1 ELSE 0 END AS INTEGER) AS allow_personal_token FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3
`

type AdapterPlanCredentialParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterPlanCredentialRow struct {
	CredentialCiphertext []byte
	SpkiPin              string
	CaBundlePem          string
	AllowPersonalToken   int64
}

func (q *Queries) AdapterPlanCredential(ctx context.Context, arg AdapterPlanCredentialParams) (AdapterPlanCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, adapterPlanCredential, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var i AdapterPlanCredentialRow
	err := row.Scan(
		&i.CredentialCiphertext,
		&i.SpkiPin,
		&i.CaBundlePem,
		&i.AllowPersonalToken,
	)
	return i, err
}

const adapterPlanLedger = `-- name: AdapterPlanLedger :many
SELECT l.surface,l.effective_name,l.state,l.missing,CAST(CASE WHEN l.state='owned' AND EXISTS (SELECT 1 FROM adapter_conflicts c WHERE c.target_id=l.target_id AND c.org_id=?1 AND c.project_id=?2 AND c.environment_id=?3 AND c.target_generation=t.generation-1 AND c.destination_id=l.destination_id AND c.repository_id=l.repository_id AND c.surface=l.surface AND UPPER(c.effective_name)=l.normalized_name AND c.adopted_at IS NOT NULL AND julianday(c.adopted_at) IS NOT NULL AND NOT EXISTS (SELECT 1 FROM adapter_effects e WHERE e.target_id=l.target_id AND e.org_id=?1 AND e.project_id=?2 AND e.environment_id=?3 AND e.surface=l.surface AND UPPER(e.effective_name)=l.normalized_name AND e.disposition IN ('create','update') AND e.outcome='success' AND (julianday(e.finished_at) IS NULL OR julianday(e.finished_at)>=julianday(c.adopted_at)))) THEN 1 ELSE 0 END AS INTEGER) AS adoption_pending FROM adapter_ledger l JOIN adapter_targets t ON t.id=l.target_id AND t.org_id=?1 AND t.project_id=?2 AND t.environment_id=?3 AND t.generation=?4 WHERE l.target_id=?5 AND l.org_id=?1 AND l.project_id=?2 AND l.environment_id=?3 AND l.state<>'released' ORDER BY l.surface,l.effective_name
`

type AdapterPlanLedgerParams struct {
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
	Generation    int64
	TargetID      string
}

type AdapterPlanLedgerRow struct {
	Surface         string
	EffectiveName   string
	State           string
	Missing         int64
	AdoptionPending int64
}

func (q *Queries) AdapterPlanLedger(ctx context.Context, arg AdapterPlanLedgerParams) ([]AdapterPlanLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterPlanLedger,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.Generation,
		arg.TargetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterPlanLedgerRow
	for rows.Next() {
		var i AdapterPlanLedgerRow
		if err := rows.Scan(
			&i.Surface,
			&i.EffectiveName,
			&i.State,
			&i.Missing,
			&i.AdoptionPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterPlanManifest = `-- name: AdapterPlanManifest :many
SELECT e.key_id,e.key_name,e.classification FROM snapshot_entries e JOIN adapter_target_keys k ON k.key_id=e.key_id AND k.target_id=?1 AND k.org_id=e.org_id AND k.project_id=e.project_id AND k.environment_id=e.environment_id WHERE e.snapshot_id=(SELECT latest.id FROM snapshots latest WHERE latest.org_id=?2 AND latest.project_id=?3 AND latest.environment_id=?4 AND latest.payload_present=1 ORDER BY latest.revision DESC LIMIT 1) AND e.org_id=?2 AND e.project_id=?3 AND e.environment_id=?4 ORDER BY e.key_name
`

type AdapterPlanManifestParams struct {
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

type AdapterPlanManifestRow struct {
	KeyID          string
	KeyName        string
	Classification string
}

func (q *Queries) AdapterPlanManifest(ctx context.Context, arg AdapterPlanManifestParams) ([]AdapterPlanManifestRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterPlanManifest,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterPlanManifestRow
	for rows.Next() {
		var i AdapterPlanManifestRow
		if err := rows.Scan(&i.KeyID, &i.KeyName, &i.Classification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterPlanTarget = `-- name: AdapterPlanTarget :one
SELECT environment_id,destination_id,repository_id,generation FROM adapter_targets WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterPlanTargetParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterPlanTargetRow struct {
	EnvironmentID string
	DestinationID int64
	RepositoryID  int64
	Generation    int64
}

func (q *Queries) AdapterPlanTarget(ctx context.Context, arg AdapterPlanTargetParams) (AdapterPlanTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterPlanTarget, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	var i AdapterPlanTargetRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.DestinationID,
		&i.RepositoryID,
		&i.Generation,
	)
	return i, err
}

const adapterProvider = `-- name: AdapterProvider :many
SELECT provider FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3
`

type AdapterProviderParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterProvider(ctx context.Context, arg AdapterProviderParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, adapterProvider, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterPublishedTargets = `-- name: AdapterPublishedTargets :many
SELECT t.id,t.environment_id,a.authority_principal_id,t.generation,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS active_job_id FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id WHERE t.org_id=?1 AND t.project_id=?2 AND t.environment_id=?3 AND t.state='active' AND t.paused_at IS NULL ORDER BY t.id
`

type AdapterPublishedTargetsParams struct {
	ChainOrg     string
	ChainProject string
	ChainEnv     string
}

type AdapterPublishedTargetsRow struct {
	ID                   string
	EnvironmentID        string
	AuthorityPrincipalID string
	Generation           int64
	ActiveJobID          string
}

func (q *Queries) AdapterPublishedTargets(ctx context.Context, arg AdapterPublishedTargetsParams) ([]AdapterPublishedTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterPublishedTargets, arg.ChainOrg, arg.ChainProject, arg.ChainEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterPublishedTargetsRow
	for rows.Next() {
		var i AdapterPublishedTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.AuthorityPrincipalID,
			&i.Generation,
			&i.ActiveJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterRecordCredentialExpiry = `-- name: AdapterRecordCredentialExpiry :execrows
UPDATE adapters SET credential_expires_at=?1 WHERE id=?2 AND org_id=?3 AND project_id=?4 AND state='active'
`

type AdapterRecordCredentialExpiryParams struct {
	ExpiresAt    sql.NullString
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterRecordCredentialExpiry(ctx context.Context, arg AdapterRecordCredentialExpiryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterRecordCredentialExpiry,
		arg.ExpiresAt,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterReencrypt = `-- name: AdapterReencrypt :execrows
UPDATE adapters SET credential_ciphertext=?1 WHERE org_id=?2 AND project_id=?3 AND id=?4 AND credential_ciphertext=?5
`

type AdapterReencryptParams struct {
	NewCiphertext []byte
	ChainOrg      string
	ChainProject  string
	ID            string
	OldCiphertext []byte
}

func (q *Queries) AdapterReencrypt(ctx context.Context, arg AdapterReencryptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterReencrypt,
		arg.NewCiphertext,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ID,
		arg.OldCiphertext,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterReencryptMove = `-- name: AdapterReencryptMove :execrows
UPDATE adapter_route_moves SET pending_credential_ciphertext=?1 WHERE org_id=?2 AND project_id=?3 AND id=?4 AND pending_credential_ciphertext=?5
`

type AdapterReencryptMoveParams struct {
	NewCiphertext []byte
	ChainOrg      string
	ChainProject  string
	ID            string
	OldCiphertext []byte
}

func (q *Queries) AdapterReencryptMove(ctx context.Context, arg AdapterReencryptMoveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterReencryptMove,
		arg.NewCiphertext,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ID,
		arg.OldCiphertext,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterReleaseLedger = `-- name: AdapterReleaseLedger :exec
UPDATE adapter_ledger SET state='released',missing=0,updated_at=?1 WHERE target_id=?2 AND org_id=?3 AND project_id=?4 AND environment_id=?5 AND state<>'released'
`

type AdapterReleaseLedgerParams struct {
	UpdatedAt     string
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

func (q *Queries) AdapterReleaseLedger(ctx context.Context, arg AdapterReleaseLedgerParams) error {
	_, err := q.db.ExecContext(ctx, adapterReleaseLedger,
		arg.UpdatedAt,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	return err
}

const adapterReplaceCredential = `-- name: AdapterReplaceCredential :execrows
UPDATE adapters SET credential_ciphertext=?1,credential_set_at=?2,credential_expires_at=NULL,authority_principal_id=?3 WHERE id=?4 AND org_id=?5 AND project_id=?6 AND state='active'
`

type AdapterReplaceCredentialParams struct {
	CredentialCiphertext []byte
	At                   sql.NullString
	AuthorityPrincipalID string
	AdapterID            string
	ChainOrg             string
	ChainProject         string
}

func (q *Queries) AdapterReplaceCredential(ctx context.Context, arg AdapterReplaceCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterReplaceCredential,
		arg.CredentialCiphertext,
		arg.At,
		arg.AuthorityPrincipalID,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterReplaceCredentialBump = `-- name: AdapterReplaceCredentialBump :execrows
UPDATE adapter_targets SET generation=generation+1,provider_lease_job_id=NULL,provider_lease_effect_id=NULL,provider_lease_expires_at=NULL WHERE adapter_id=?1 AND org_id=?2 AND project_id=?3 AND state='active' AND (provider_lease_job_id IS NULL OR provider_lease_expires_at<=?4)
`

type AdapterReplaceCredentialBumpParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
	At           sql.NullString
}

func (q *Queries) AdapterReplaceCredentialBump(ctx context.Context, arg AdapterReplaceCredentialBumpParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterReplaceCredentialBump,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterReplaceCredentialTarget = `-- name: AdapterReplaceCredentialTarget :one
SELECT a.authority_principal_id,CAST((SELECT COUNT(*) FROM adapter_targets t WHERE t.adapter_id=a.id AND t.org_id=a.org_id AND t.project_id=a.project_id AND t.state='active') AS INTEGER) AS target_count,CAST((SELECT COUNT(*) FROM adapter_targets t WHERE t.adapter_id=a.id AND t.org_id=a.org_id AND t.project_id=a.project_id AND t.state='active' AND t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1) AS INTEGER) AS provider_busy FROM adapters a WHERE a.id=?2 AND a.org_id=?3 AND a.project_id=?4 AND a.state='active'
`

type AdapterReplaceCredentialTargetParams struct {
	At           sql.NullString
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterReplaceCredentialTargetRow struct {
	AuthorityPrincipalID string
	TargetCount          int64
	ProviderBusy         int64
}

func (q *Queries) AdapterReplaceCredentialTarget(ctx context.Context, arg AdapterReplaceCredentialTargetParams) (AdapterReplaceCredentialTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterReplaceCredentialTarget,
		arg.At,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	var i AdapterReplaceCredentialTargetRow
	err := row.Scan(&i.AuthorityPrincipalID, &i.TargetCount, &i.ProviderBusy)
	return i, err
}

const adapterResumeRevision = `-- name: AdapterResumeRevision :one
SELECT CAST(COALESCE(MAX(revision),0) AS INTEGER) AS revision FROM snapshots WHERE org_id=?1 AND project_id=?2 AND environment_id=?3 AND payload_present=1
`

type AdapterResumeRevisionParams struct {
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

func (q *Queries) AdapterResumeRevision(ctx context.Context, arg AdapterResumeRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adapterResumeRevision, arg.ChainOrg, arg.ChainProject, arg.EnvironmentID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const adapterResumeTarget = `-- name: AdapterResumeTarget :execrows
UPDATE adapter_targets SET paused_at=NULL WHERE id=?1 AND org_id=?2 AND project_id=?3 AND environment_id=?4 AND generation=?5 AND paused_at IS NOT NULL
`

type AdapterResumeTargetParams struct {
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
}

func (q *Queries) AdapterResumeTarget(ctx context.Context, arg AdapterResumeTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterResumeTarget,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterRetainTarget = `-- name: AdapterRetainTarget :execrows
UPDATE adapter_targets SET generation=?1,state='tombstoned',sync_status='converged',failure_names='[]',active_job_id=NULL,provider_lease_job_id=NULL,provider_lease_effect_id=NULL,provider_lease_expires_at=NULL WHERE id=?2 AND org_id=?3 AND project_id=?4 AND environment_id=?5 AND generation=?6 AND state='active' AND (provider_lease_job_id IS NULL OR provider_lease_expires_at<=?7)
`

type AdapterRetainTargetParams struct {
	NextGeneration     int64
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
	At                 sql.NullString
}

func (q *Queries) AdapterRetainTarget(ctx context.Context, arg AdapterRetainTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterRetainTarget,
		arg.NextGeneration,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterRevokeCredential = `-- name: AdapterRevokeCredential :execrows
UPDATE adapters SET credential_ciphertext=NULL,credential_set_at=NULL,credential_expires_at=NULL WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterRevokeCredentialParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterRevokeCredential(ctx context.Context, arg AdapterRevokeCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterRevokeCredential, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterRevokeCredentialBump = `-- name: AdapterRevokeCredentialBump :execrows
UPDATE adapter_targets SET generation=generation+1 WHERE adapter_id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterRevokeCredentialBumpParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterRevokeCredentialBump(ctx context.Context, arg AdapterRevokeCredentialBumpParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterRevokeCredentialBump, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterRevokeCredentialTarget = `-- name: AdapterRevokeCredentialTarget :one
SELECT a.authority_principal_id,CAST((SELECT COUNT(*) FROM adapter_targets t WHERE t.adapter_id=a.id AND t.org_id=a.org_id AND t.project_id=a.project_id AND t.state='active') AS INTEGER) AS target_count FROM adapters a WHERE a.id=?1 AND a.org_id=?2 AND a.project_id=?3 AND a.state='active'
`

type AdapterRevokeCredentialTargetParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterRevokeCredentialTargetRow struct {
	AuthorityPrincipalID string
	TargetCount          int64
}

func (q *Queries) AdapterRevokeCredentialTarget(ctx context.Context, arg AdapterRevokeCredentialTargetParams) (AdapterRevokeCredentialTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterRevokeCredentialTarget, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var i AdapterRevokeCredentialTargetRow
	err := row.Scan(&i.AuthorityPrincipalID, &i.TargetCount)
	return i, err
}

const adapterScrubTarget = `-- name: AdapterScrubTarget :execrows
UPDATE adapter_targets SET generation=?1,state='tombstoned',sync_status='converging',failure_names='[]',active_job_id=?2,provider_lease_job_id=NULL,provider_lease_effect_id=NULL,provider_lease_expires_at=NULL WHERE id=?3 AND org_id=?4 AND project_id=?5 AND environment_id=?6 AND generation=?7 AND state='active' AND (provider_lease_job_id IS NULL OR provider_lease_expires_at<=?8)
`

type AdapterScrubTargetParams struct {
	NextGeneration     int64
	JobID              sql.NullString
	TargetID           string
	ChainOrg           string
	ChainProject       string
	EnvironmentID      string
	ExpectedGeneration int64
	At                 sql.NullString
}

func (q *Queries) AdapterScrubTarget(ctx context.Context, arg AdapterScrubTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterScrubTarget,
		arg.NextGeneration,
		arg.JobID,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
		arg.ExpectedGeneration,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterTargetActiveJob = `-- name: AdapterTargetActiveJob :one
SELECT CAST(COALESCE(active_job_id,'') AS TEXT) AS active_job_id FROM adapter_targets WHERE id=?1 AND org_id=?2 AND project_id=?3 AND environment_id=?4
`

type AdapterTargetActiveJobParams struct {
	TargetID      string
	ChainOrg      string
	ChainProject  string
	EnvironmentID string
}

func (q *Queries) AdapterTargetActiveJob(ctx context.Context, arg AdapterTargetActiveJobParams) (string, error) {
	row := q.db.QueryRowContext(ctx, adapterTargetActiveJob,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.EnvironmentID,
	)
	var active_job_id string
	err := row.Scan(&active_job_id)
	return active_job_id, err
}

const adapterTargetEnvironments = `-- name: AdapterTargetEnvironments :many
SELECT sibling.environment_id FROM adapter_targets target JOIN adapter_targets sibling ON sibling.adapter_id=target.adapter_id AND sibling.org_id=target.org_id AND sibling.project_id=target.project_id WHERE target.id=?1 AND target.org_id=?2 AND target.project_id=?3 AND sibling.state<>'tombstoned' ORDER BY sibling.environment_id
`

type AdapterTargetEnvironmentsParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterTargetEnvironments(ctx context.Context, arg AdapterTargetEnvironmentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, adapterTargetEnvironments, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var environment_id string
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterTargetKeyIDs = `-- name: AdapterTargetKeyIDs :many
SELECT key_id FROM adapter_target_keys WHERE target_id=?1 AND org_id=?2 AND project_id=?3 ORDER BY key_id
`

type AdapterTargetKeyIDsParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterTargetKeyIDs(ctx context.Context, arg AdapterTargetKeyIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, adapterTargetKeyIDs, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_id string
		if err := rows.Scan(&key_id); err != nil {
			return nil, err
		}
		items = append(items, key_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterTargetKeys = `-- name: AdapterTargetKeys :many
SELECT k.id,k.name,k.classification FROM adapter_target_keys tk JOIN keys k ON k.id=tk.key_id AND k.org_id=tk.org_id AND k.project_id=tk.project_id WHERE tk.target_id=?1 AND tk.org_id=?2 AND tk.project_id=?3 ORDER BY k.name
`

type AdapterTargetKeysParams struct {
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterTargetKeysRow struct {
	ID             string
	Name           string
	Classification string
}

func (q *Queries) AdapterTargetKeys(ctx context.Context, arg AdapterTargetKeysParams) ([]AdapterTargetKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterTargetKeys, arg.TargetID, arg.ChainOrg, arg.ChainProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterTargetKeysRow
	for rows.Next() {
		var i AdapterTargetKeysRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Classification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterTeardownAuthority = `-- name: AdapterTeardownAuthority :one
SELECT authority_principal_id FROM adapters WHERE id=?1 AND org_id=?2 AND project_id=?3 AND state='active'
`

type AdapterTeardownAuthorityParams struct {
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

func (q *Queries) AdapterTeardownAuthority(ctx context.Context, arg AdapterTeardownAuthorityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, adapterTeardownAuthority, arg.AdapterID, arg.ChainOrg, arg.ChainProject)
	var authority_principal_id string
	err := row.Scan(&authority_principal_id)
	return authority_principal_id, err
}

const adapterTeardownTarget = `-- name: AdapterTeardownTarget :one
SELECT t.adapter_id,t.id,t.environment_id,a.authority_principal_id,t.generation,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS active_job_id,CAST(CASE WHEN t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1 THEN 1 ELSE 0 END AS INTEGER) AS provider_busy FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id WHERE t.id=?2 AND t.org_id=?3 AND t.project_id=?4 AND t.state='active'
`

type AdapterTeardownTargetParams struct {
	At           sql.NullString
	TargetID     string
	ChainOrg     string
	ChainProject string
}

type AdapterTeardownTargetRow struct {
	AdapterID            string
	ID                   string
	EnvironmentID        string
	AuthorityPrincipalID string
	Generation           int64
	ActiveJobID          string
	ProviderBusy         int64
}

func (q *Queries) AdapterTeardownTarget(ctx context.Context, arg AdapterTeardownTargetParams) (AdapterTeardownTargetRow, error) {
	row := q.db.QueryRowContext(ctx, adapterTeardownTarget,
		arg.At,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	var i AdapterTeardownTargetRow
	err := row.Scan(
		&i.AdapterID,
		&i.ID,
		&i.EnvironmentID,
		&i.AuthorityPrincipalID,
		&i.Generation,
		&i.ActiveJobID,
		&i.ProviderBusy,
	)
	return i, err
}

const adapterTeardownTargets = `-- name: AdapterTeardownTargets :many
SELECT t.adapter_id,t.id,t.environment_id,a.authority_principal_id,t.generation,CAST(COALESCE(t.active_job_id,'') AS TEXT) AS active_job_id,CAST(CASE WHEN t.provider_lease_job_id IS NOT NULL AND t.provider_lease_expires_at>?1 THEN 1 ELSE 0 END AS INTEGER) AS provider_busy FROM adapter_targets t JOIN adapters a ON a.id=t.adapter_id AND a.org_id=t.org_id AND a.project_id=t.project_id WHERE t.adapter_id=?2 AND t.org_id=?3 AND t.project_id=?4 AND t.state='active' ORDER BY t.id
`

type AdapterTeardownTargetsParams struct {
	At           sql.NullString
	AdapterID    string
	ChainOrg     string
	ChainProject string
}

type AdapterTeardownTargetsRow struct {
	AdapterID            string
	ID                   string
	EnvironmentID        string
	AuthorityPrincipalID string
	Generation           int64
	ActiveJobID          string
	ProviderBusy         int64
}

func (q *Queries) AdapterTeardownTargets(ctx context.Context, arg AdapterTeardownTargetsParams) ([]AdapterTeardownTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, adapterTeardownTargets,
		arg.At,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterTeardownTargetsRow
	for rows.Next() {
		var i AdapterTeardownTargetsRow
		if err := rows.Scan(
			&i.AdapterID,
			&i.ID,
			&i.EnvironmentID,
			&i.AuthorityPrincipalID,
			&i.Generation,
			&i.ActiveJobID,
			&i.ProviderBusy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adapterUpdateActiveAuthority = `-- name: AdapterUpdateActiveAuthority :execrows
UPDATE adapters SET authority_principal_id=?1 WHERE id=?2 AND org_id=?3 AND project_id=?4 AND state='active'
`

type AdapterUpdateActiveAuthorityParams struct {
	AuthorityPrincipalID string
	AdapterID            string
	ChainOrg             string
	ChainProject         string
}

func (q *Queries) AdapterUpdateActiveAuthority(ctx context.Context, arg AdapterUpdateActiveAuthorityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterUpdateActiveAuthority,
		arg.AuthorityPrincipalID,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterUpdateAuthorityExpiry = `-- name: AdapterUpdateAuthorityExpiry :execrows
UPDATE adapters SET authority_principal_id=?1,credential_expires_at=COALESCE(?2,credential_expires_at) WHERE id=?3 AND org_id=?4 AND project_id=?5 AND state='active'
`

type AdapterUpdateAuthorityExpiryParams struct {
	AuthorityPrincipalID string
	CredentialExpiresAt  sql.NullString
	AdapterID            string
	ChainOrg             string
	ChainProject         string
}

func (q *Queries) AdapterUpdateAuthorityExpiry(ctx context.Context, arg AdapterUpdateAuthorityExpiryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterUpdateAuthorityExpiry,
		arg.AuthorityPrincipalID,
		arg.CredentialExpiresAt,
		arg.AdapterID,
		arg.ChainOrg,
		arg.ChainProject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adapterUpdateTargetConfig = `-- name: AdapterUpdateTargetConfig :execrows
UPDATE adapter_targets SET visibility=?1,selected_repository_ids=?2,name_prefix=?3,variable_protected=?4,variable_hidden=?5,variable_expand=?6 WHERE id=?7 AND org_id=?8 AND project_id=?9 AND generation=?10 AND state='active' AND provider_lease_job_id IS NULL
`

type AdapterUpdateTargetConfigParams struct {
	Visibility            string
	SelectedRepositoryIds string
	NamePrefix            string
	VariableProtected     int64
	VariableHidden        int64
	VariableExpand        int64
	TargetID              string
	ChainOrg              string
	ChainProject          string
	ExpectedGeneration    int64
}

func (q *Queries) AdapterUpdateTargetConfig(ctx context.Context, arg AdapterUpdateTargetConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adapterUpdateTargetConfig,
		arg.Visibility,
		arg.SelectedRepositoryIds,
		arg.NamePrefix,
		arg.VariableProtected,
		arg.VariableHidden,
		arg.VariableExpand,
		arg.TargetID,
		arg.ChainOrg,
		arg.ChainProject,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
