// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const createOIDCProvider = `-- name: CreateOIDCProvider :exec

INSERT INTO oidc_providers
    (id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
     redirect_uri, assurance_policy, enabled, dek_version, row_version,
     created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
`

type CreateOIDCProviderParams struct {
	ID              string
	Slug            string
	DisplayName     string
	Kind            string
	Issuer          string
	ClientID        string
	ClientSecret    []byte
	Scopes          string
	RedirectUri     string
	AssurancePolicy sql.NullString
	Enabled         int64
	DekVersion      int64
	CreatedAt       string
	UpdatedAt       string
}

// OIDC provider administration (#54, human-auth ADR - Login methods). The
// provider table is class=authn: it decides how a caller may authenticate, and
// login resolves it proof-free, so every statement touching it lives on the
// resolution surface. Provider mutations are still authorized at the chokepoint
// (OpProviderPut/Delete under instance-config) before these run; the write
// itself rides the resolution surface, like the session lifecycle.
// hikyo:authn-resolution
func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) error {
	_, err := q.db.ExecContext(ctx, createOIDCProvider,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Kind,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.RedirectUri,
		arg.AssurancePolicy,
		arg.Enabled,
		arg.DekVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers WHERE id = ?
`

// hikyo:authn-resolution
func (q *Queries) DeleteOIDCProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOIDCProvider, id)
	return err
}

const getOIDCProviderBySlug = `-- name: GetOIDCProviderBySlug :one
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers WHERE slug = ?
`

// hikyo:authn-resolution
func (q *Queries) GetOIDCProviderBySlug(ctx context.Context, slug string) (OidcProvider, error) {
	row := q.db.QueryRowContext(ctx, getOIDCProviderBySlug, slug)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.RedirectUri,
		&i.AssurancePolicy,
		&i.Enabled,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const guardOIDCProviderForMint = `-- name: GuardOIDCProviderForMint :execrows
UPDATE oidc_providers SET row_version = row_version
WHERE id = ? AND row_version = ? AND issuer = ? AND enabled = 1
`

type GuardOIDCProviderForMintParams struct {
	ID         string
	RowVersion int64
	Issuer     string
}

// A phase-C mint (login/link/reauth) guards the pinned provider row against a
// concurrent reconfigure: a no-op CAS that takes the row lock. 0 rows affected
// means the provider was disabled, deleted, re-issued or row_version-bumped
// since Phase A, so the mint must refuse (the A4 sweep always wins the TOCTOU).
// A matching row takes the lock, so a concurrent provider-change UPDATE
// serializes behind it (and vice-versa: whichever commits first, the other's
// guard sees the bumped row_version and fails). The no-op never bumps
// row_version, so it never spuriously fails an administrator's reconfigure CAS.
// hikyo:authn-resolution
func (q *Queries) GuardOIDCProviderForMint(ctx context.Context, arg GuardOIDCProviderForMintParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, guardOIDCProviderForMint, arg.ID, arg.RowVersion, arg.Issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers ORDER BY slug
`

// hikyo:authn-resolution
func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.QueryContext(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcProvider
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Kind,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.RedirectUri,
			&i.AssurancePolicy,
			&i.Enabled,
			&i.DekVersion,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOIDCProviderForDelete = `-- name: LockOIDCProviderForDelete :one
SELECT id FROM oidc_providers WHERE id = ?
`

// Structural twin of the postgres lock: BEGIN IMMEDIATE already holds the
// database write lock for the whole delete tx, so a concurrent mint guard
// cannot interleave; this read confirms the row still exists (no-rows =>
// ErrProviderNotFound) and keeps the delete path identical across engines.
// hikyo:authn-resolution
func (q *Queries) LockOIDCProviderForDelete(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockOIDCProviderForDelete, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateOIDCProviderCAS = `-- name: UpdateOIDCProviderCAS :execrows
UPDATE oidc_providers
SET display_name = ?, client_id = ?, client_secret = ?, scopes = ?,
    redirect_uri = ?, assurance_policy = ?, enabled = ?,
    dek_version = ?, row_version = row_version + 1, updated_at = ?
WHERE id = ? AND row_version = ?
`

type UpdateOIDCProviderCASParams struct {
	DisplayName     string
	ClientID        string
	ClientSecret    []byte
	Scopes          string
	RedirectUri     string
	AssurancePolicy sql.NullString
	Enabled         int64
	DekVersion      int64
	UpdatedAt       string
	ID              string
	RowVersion      int64
}

// The issuer is never in the SET list: it is immutable after create (A3), so a
// reconfiguration cannot silently move the identity space to a new authority.
// CAS on row_version so a concurrent reconfigure fails closed.
// hikyo:authn-resolution
func (q *Queries) UpdateOIDCProviderCAS(ctx context.Context, arg UpdateOIDCProviderCASParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOIDCProviderCAS,
		arg.DisplayName,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.RedirectUri,
		arg.AssurancePolicy,
		arg.Enabled,
		arg.DekVersion,
		arg.UpdatedAt,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
