// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reencrypt.sql

package sqlitegen

import (
	"context"
)

const listSelfConfigSeedInputsForReencrypt = `-- name: ListSelfConfigSeedInputsForReencrypt :many
SELECT node_id, ciphertext, dek_version, row_version FROM self_config_seed_inputs
WHERE node_id > ?1 ORDER BY node_id LIMIT ?2
`

type ListSelfConfigSeedInputsForReencryptParams struct {
	Cursor    string
	PageLimit int64
}

type ListSelfConfigSeedInputsForReencryptRow struct {
	NodeID     string
	Ciphertext []byte
	DekVersion int64
	RowVersion int64
}

// Temporary node bootstrap inputs use the instance DEK, not a project key.
func (q *Queries) ListSelfConfigSeedInputsForReencrypt(ctx context.Context, arg ListSelfConfigSeedInputsForReencryptParams) ([]ListSelfConfigSeedInputsForReencryptRow, error) {
	rows, err := q.db.QueryContext(ctx, listSelfConfigSeedInputsForReencrypt, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSelfConfigSeedInputsForReencryptRow
	for rows.Next() {
		var i ListSelfConfigSeedInputsForReencryptRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Ciphertext,
			&i.DekVersion,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reencryptSelfConfigSeedInput = `-- name: ReencryptSelfConfigSeedInput :execrows
UPDATE self_config_seed_inputs
SET ciphertext=?1, dek_version=?2, row_version=row_version+1
WHERE node_id=?3 AND row_version=?4 AND ciphertext=?5
`

type ReencryptSelfConfigSeedInputParams struct {
	Ct         []byte
	DekVersion int64
	NodeID     string
	RowVersion int64
	OldCt      []byte
}

// The ciphertext guard also rejects delete/reinsert at the same row version.
func (q *Queries) ReencryptSelfConfigSeedInput(ctx context.Context, arg ReencryptSelfConfigSeedInputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reencryptSelfConfigSeedInput,
		arg.Ct,
		arg.DekVersion,
		arg.NodeID,
		arg.RowVersion,
		arg.OldCt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
