// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const addSCIMGroupMember = `-- name: AddSCIMGroupMember :exec
INSERT INTO scim_group_members (id, org_id, binding_id, group_id, user_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddSCIMGroupMemberParams struct {
	ID        string
	OrgID     string
	BindingID string
	GroupID   string
	UserID    string
	CreatedAt string
}

func (q *Queries) AddSCIMGroupMember(ctx context.Context, arg AddSCIMGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addSCIMGroupMember,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.GroupID,
		arg.UserID,
		arg.CreatedAt,
	)
	return err
}

const clearSCIMAttention = `-- name: ClearSCIMAttention :execrows
DELETE FROM scim_attention
WHERE org_id = ? AND binding_id = ? AND state = ? AND subject_ref = ?
`

type ClearSCIMAttentionParams struct {
	OrgID      string
	BindingID  string
	State      string
	SubjectRef string
}

func (q *Queries) ClearSCIMAttention(ctx context.Context, arg ClearSCIMAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearSCIMAttention,
		arg.OrgID,
		arg.BindingID,
		arg.State,
		arg.SubjectRef,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearSCIMGroupMembers = `-- name: ClearSCIMGroupMembers :execrows
DELETE FROM scim_group_members WHERE org_id = ? AND binding_id = ? AND group_id = ?
`

type ClearSCIMGroupMembersParams struct {
	OrgID     string
	BindingID string
	GroupID   string
}

func (q *Queries) ClearSCIMGroupMembers(ctx context.Context, arg ClearSCIMGroupMembersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearSCIMGroupMembers, arg.OrgID, arg.BindingID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countSCIMGroups = `-- name: CountSCIMGroups :one
SELECT COUNT(*) FROM scim_groups WHERE org_id = ? AND binding_id = ?
`

type CountSCIMGroupsParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) CountSCIMGroups(ctx context.Context, arg CountSCIMGroupsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMGroups, arg.OrgID, arg.BindingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSCIMGroupsByDisplayName = `-- name: CountSCIMGroupsByDisplayName :one
SELECT COUNT(*) FROM scim_groups WHERE org_id = ?1 AND binding_id = ?2 AND display_name_lower = ?3
`

type CountSCIMGroupsByDisplayNameParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
}

// Okta and Entra both discover a group by `displayName eq` before creating or
// updating it; displayName is caseExact:false like userName. It is NOT unique
// (RFC 7643 does not make it so), which is why this returns MANY: a directory
// with two same-named groups must answer with two.
func (q *Queries) CountSCIMGroupsByDisplayName(ctx context.Context, arg CountSCIMGroupsByDisplayNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMGroupsByDisplayName, arg.OrgID, arg.BindingID, arg.FilterValue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSCIMGroupsByExternalID = `-- name: CountSCIMGroupsByExternalID :one
SELECT COUNT(*) FROM scim_groups WHERE org_id = ?1 AND binding_id = ?2 AND external_id = ?3
`

type CountSCIMGroupsByExternalIDParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
}

// externalId is not unique on groups either.
func (q *Queries) CountSCIMGroupsByExternalID(ctx context.Context, arg CountSCIMGroupsByExternalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMGroupsByExternalID, arg.OrgID, arg.BindingID, arg.FilterValue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSCIMUsers = `-- name: CountSCIMUsers :one
SELECT COUNT(*) FROM scim_users WHERE org_id = ? AND binding_id = ?
`

type CountSCIMUsersParams struct {
	OrgID     string
	BindingID string
}

// The WIRE's paged reads. Paging in Go over an unbounded read lets a valid
// credential force full-directory work for a 200-item answer, every request;
// LIMIT/OFFSET bounds resource materialization; the matching count query
// keeps `totalResults` truthful (ADR section 8's ListResponse fields).
func (q *Queries) CountSCIMUsers(ctx context.Context, arg CountSCIMUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMUsers, arg.OrgID, arg.BindingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSCIMUsersByExternalID = `-- name: CountSCIMUsersByExternalID :one
SELECT COUNT(*) FROM scim_users WHERE org_id = ?1 AND binding_id = ?2 AND external_id = ?3
`

type CountSCIMUsersByExternalIDParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
}

// externalId compares BYTE-EXACT (ADR section 8). It is NOT unique -- only the
// SUBJECT is -- so this returns MANY: an empty externalId is the default and a
// singular query would answer an arbitrary one of them with totalResults 1.
func (q *Queries) CountSCIMUsersByExternalID(ctx context.Context, arg CountSCIMUsersByExternalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMUsersByExternalID, arg.OrgID, arg.BindingID, arg.FilterValue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSCIMUsersByUserName = `-- name: CountSCIMUsersByUserName :one
SELECT COUNT(*) FROM scim_users WHERE org_id = ?1 AND binding_id = ?2 AND user_name_lower = ?3
`

type CountSCIMUsersByUserNameParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
}

// Filtered pages and counts deliberately use identical equality predicates.
func (q *Queries) CountSCIMUsersByUserName(ctx context.Context, arg CountSCIMUsersByUserNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSCIMUsersByUserName, arg.OrgID, arg.BindingID, arg.FilterValue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSCIMBinding = `-- name: CreateSCIMBinding :exec

INSERT INTO scim_bindings (
    id, org_id, provider_kind, provider_id, provider_slug, provider_issuer, subject_source,
    nameid_format, nameid_qualifier, nameid_qualifier_present,
    nameid_sp_qualifier, nameid_sp_qualifier_present,
    connection_principal_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMBindingParams struct {
	ID                       string
	OrgID                    string
	ProviderKind             string
	ProviderID               string
	ProviderSlug             string
	ProviderIssuer           string
	SubjectSource            string
	NameidFormat             string
	NameidQualifier          string
	NameidQualifierPresent   int64
	NameidSpQualifier        string
	NameidSpQualifierPresent int64
	ConnectionPrincipalID    string
	CreatedAt                string
}

// SCIM provisioning (#73). Tenant-scoped statements: the reserved chain_*
// parameter is bound by the store's binding layer from the verified proof's
// resolved chain, never from a caller argument. Every SCIM wire operation
// authorizes `scim-provision(org)` first, so `org_id` here is always the org
// that proof resolved.
// ASCII only: multibyte characters shift sqlite statement offsets.
func (q *Queries) CreateSCIMBinding(ctx context.Context, arg CreateSCIMBindingParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMBinding,
		arg.ID,
		arg.OrgID,
		arg.ProviderKind,
		arg.ProviderID,
		arg.ProviderSlug,
		arg.ProviderIssuer,
		arg.SubjectSource,
		arg.NameidFormat,
		arg.NameidQualifier,
		arg.NameidQualifierPresent,
		arg.NameidSpQualifier,
		arg.NameidSpQualifierPresent,
		arg.ConnectionPrincipalID,
		arg.CreatedAt,
	)
	return err
}

const createSCIMGroup = `-- name: CreateSCIMGroup :exec
INSERT INTO scim_groups (
    id, org_id, binding_id, display_name, display_name_lower, external_id,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMGroupParams struct {
	ID               string
	OrgID            string
	BindingID        string
	DisplayName      string
	DisplayNameLower string
	ExternalID       string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateSCIMGroup(ctx context.Context, arg CreateSCIMGroupParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMGroup,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.DisplayName,
		arg.DisplayNameLower,
		arg.ExternalID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSCIMMapping = `-- name: CreateSCIMMapping :exec
INSERT INTO scim_mappings (
    id, org_id, binding_id, group_id, template, scope_project_id, scope_env_id,
    inert, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMMappingParams struct {
	ID             string
	OrgID          string
	BindingID      string
	GroupID        string
	Template       string
	ScopeProjectID string
	ScopeEnvID     string
	Inert          int64
	CreatedAt      string
}

func (q *Queries) CreateSCIMMapping(ctx context.Context, arg CreateSCIMMappingParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMMapping,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.GroupID,
		arg.Template,
		arg.ScopeProjectID,
		arg.ScopeEnvID,
		arg.Inert,
		arg.CreatedAt,
	)
	return err
}

const createSCIMUser = `-- name: CreateSCIMUser :exec
INSERT INTO scim_users (
    id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
    subject, active, attributes, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMUserParams struct {
	ID            string
	OrgID         string
	BindingID     string
	AccountID     string
	UserName      string
	UserNameLower string
	ExternalID    string
	Subject       string
	Active        int64
	Attributes    string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateSCIMUser(ctx context.Context, arg CreateSCIMUserParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMUser,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.AccountID,
		arg.UserName,
		arg.UserNameLower,
		arg.ExternalID,
		arg.Subject,
		arg.Active,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSCIMAttentionForBinding = `-- name: DeleteSCIMAttentionForBinding :execrows
DELETE FROM scim_attention WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMAttentionForBindingParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) DeleteSCIMAttentionForBinding(ctx context.Context, arg DeleteSCIMAttentionForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMAttentionForBinding, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMBinding = `-- name: DeleteSCIMBinding :execrows
DELETE FROM scim_bindings WHERE org_id = ? AND id = ?
`

type DeleteSCIMBindingParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteSCIMBinding(ctx context.Context, arg DeleteSCIMBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMBinding, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMGroup = `-- name: DeleteSCIMGroup :execrows
DELETE FROM scim_groups WHERE org_id = ? AND binding_id = ? AND id = ?
`

type DeleteSCIMGroupParams struct {
	OrgID     string
	BindingID string
	ID        string
}

func (q *Queries) DeleteSCIMGroup(ctx context.Context, arg DeleteSCIMGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroup, arg.OrgID, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMGroupMember = `-- name: DeleteSCIMGroupMember :execrows
DELETE FROM scim_group_members WHERE org_id = ? AND binding_id = ? AND group_id = ? AND user_id = ?
`

type DeleteSCIMGroupMemberParams struct {
	OrgID     string
	BindingID string
	GroupID   string
	UserID    string
}

func (q *Queries) DeleteSCIMGroupMember(ctx context.Context, arg DeleteSCIMGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroupMember,
		arg.OrgID,
		arg.BindingID,
		arg.GroupID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMGroupMembersForBinding = `-- name: DeleteSCIMGroupMembersForBinding :execrows
DELETE FROM scim_group_members WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMGroupMembersForBindingParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) DeleteSCIMGroupMembersForBinding(ctx context.Context, arg DeleteSCIMGroupMembersForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroupMembersForBinding, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMGroupMembershipsForUser = `-- name: DeleteSCIMGroupMembershipsForUser :execrows
DELETE FROM scim_group_members WHERE org_id = ? AND binding_id = ? AND user_id = ?
`

type DeleteSCIMGroupMembershipsForUserParams struct {
	OrgID     string
	BindingID string
	UserID    string
}

// DELETE removes every member reference to the user IN THE SAME TRANSACTION
// (ADR section 5.3), so a stale reference cannot exist after it.
func (q *Queries) DeleteSCIMGroupMembershipsForUser(ctx context.Context, arg DeleteSCIMGroupMembershipsForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroupMembershipsForUser, arg.OrgID, arg.BindingID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMGroupsForBinding = `-- name: DeleteSCIMGroupsForBinding :execrows
DELETE FROM scim_groups WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMGroupsForBindingParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) DeleteSCIMGroupsForBinding(ctx context.Context, arg DeleteSCIMGroupsForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroupsForBinding, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMMapping = `-- name: DeleteSCIMMapping :execrows
DELETE FROM scim_mappings WHERE org_id = ? AND id = ?
`

type DeleteSCIMMappingParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteSCIMMapping(ctx context.Context, arg DeleteSCIMMappingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMMapping, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMMappingsForBinding = `-- name: DeleteSCIMMappingsForBinding :execrows
DELETE FROM scim_mappings WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMMappingsForBindingParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) DeleteSCIMMappingsForBinding(ctx context.Context, arg DeleteSCIMMappingsForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMMappingsForBinding, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMUser = `-- name: DeleteSCIMUser :execrows
DELETE FROM scim_users WHERE org_id = ? AND binding_id = ? AND id = ?
`

type DeleteSCIMUserParams struct {
	OrgID     string
	BindingID string
	ID        string
}

func (q *Queries) DeleteSCIMUser(ctx context.Context, arg DeleteSCIMUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMUser, arg.OrgID, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMUsersForBinding = `-- name: DeleteSCIMUsersForBinding :execrows
DELETE FROM scim_users WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMUsersForBindingParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) DeleteSCIMUsersForBinding(ctx context.Context, arg DeleteSCIMUsersForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMUsersForBinding, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enterSCIMAttention = `-- name: EnterSCIMAttention :exec
INSERT INTO scim_attention (id, org_id, binding_id, state, subject_ref, cause, entered_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type EnterSCIMAttentionParams struct {
	ID         string
	OrgID      string
	BindingID  string
	State      string
	SubjectRef string
	Cause      string
	EnteredAt  string
}

func (q *Queries) EnterSCIMAttention(ctx context.Context, arg EnterSCIMAttentionParams) error {
	_, err := q.db.ExecContext(ctx, enterSCIMAttention,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.State,
		arg.SubjectRef,
		arg.Cause,
		arg.EnteredAt,
	)
	return err
}

const getSCIMBinding = `-- name: GetSCIMBinding :one
SELECT id, org_id, provider_kind, provider_id, provider_slug, provider_issuer, subject_source,
       nameid_format, nameid_qualifier, nameid_qualifier_present,
       nameid_sp_qualifier, nameid_sp_qualifier_present,
       connection_principal_id, last_contact_at, created_at
FROM scim_bindings WHERE org_id = ? AND id = ?
`

type GetSCIMBindingParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetSCIMBinding(ctx context.Context, arg GetSCIMBindingParams) (ScimBinding, error) {
	row := q.db.QueryRowContext(ctx, getSCIMBinding, arg.OrgID, arg.ID)
	var i ScimBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderKind,
		&i.ProviderID,
		&i.ProviderSlug,
		&i.ProviderIssuer,
		&i.SubjectSource,
		&i.NameidFormat,
		&i.NameidQualifier,
		&i.NameidQualifierPresent,
		&i.NameidSpQualifier,
		&i.NameidSpQualifierPresent,
		&i.ConnectionPrincipalID,
		&i.LastContactAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSCIMGroup = `-- name: GetSCIMGroup :one
SELECT id, org_id, binding_id, display_name, display_name_lower, external_id,
       created_at, updated_at
FROM scim_groups WHERE org_id = ? AND binding_id = ? AND id = ?
`

type GetSCIMGroupParams struct {
	OrgID     string
	BindingID string
	ID        string
}

func (q *Queries) GetSCIMGroup(ctx context.Context, arg GetSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRowContext(ctx, getSCIMGroup, arg.OrgID, arg.BindingID, arg.ID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.DisplayName,
		&i.DisplayNameLower,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMMapping = `-- name: GetSCIMMapping :one
SELECT id, org_id, binding_id, group_id, template, scope_project_id, scope_env_id,
       inert, created_at
FROM scim_mappings WHERE org_id = ? AND id = ?
`

type GetSCIMMappingParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetSCIMMapping(ctx context.Context, arg GetSCIMMappingParams) (ScimMapping, error) {
	row := q.db.QueryRowContext(ctx, getSCIMMapping, arg.OrgID, arg.ID)
	var i ScimMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.GroupID,
		&i.Template,
		&i.ScopeProjectID,
		&i.ScopeEnvID,
		&i.Inert,
		&i.CreatedAt,
	)
	return i, err
}

const getSCIMUser = `-- name: GetSCIMUser :one
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ? AND id = ?
`

type GetSCIMUserParams struct {
	OrgID     string
	BindingID string
	ID        string
}

func (q *Queries) GetSCIMUser(ctx context.Context, arg GetSCIMUserParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUser, arg.OrgID, arg.BindingID, arg.ID)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.AccountID,
		&i.UserName,
		&i.UserNameLower,
		&i.ExternalID,
		&i.Subject,
		&i.Active,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserByAccount = `-- name: GetSCIMUserByAccount :one
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ? AND account_id = ?
`

type GetSCIMUserByAccountParams struct {
	OrgID     string
	BindingID string
	AccountID string
}

func (q *Queries) GetSCIMUserByAccount(ctx context.Context, arg GetSCIMUserByAccountParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUserByAccount, arg.OrgID, arg.BindingID, arg.AccountID)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.AccountID,
		&i.UserName,
		&i.UserNameLower,
		&i.ExternalID,
		&i.Subject,
		&i.Active,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserBySubject = `-- name: GetSCIMUserBySubject :one
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ? AND subject = ?
`

type GetSCIMUserBySubjectParams struct {
	OrgID     string
	BindingID string
	Subject   string
}

func (q *Queries) GetSCIMUserBySubject(ctx context.Context, arg GetSCIMUserBySubjectParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUserBySubject, arg.OrgID, arg.BindingID, arg.Subject)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.AccountID,
		&i.UserName,
		&i.UserNameLower,
		&i.ExternalID,
		&i.Subject,
		&i.Active,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserByUserName = `-- name: GetSCIMUserByUserName :one
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ? AND user_name_lower = ?
`

type GetSCIMUserByUserNameParams struct {
	OrgID         string
	BindingID     string
	UserNameLower string
}

// The RFC 7643 caseExact:false lookup: userName compares case-insensitively,
// which is why the folded column exists rather than a LOWER() in the predicate.
func (q *Queries) GetSCIMUserByUserName(ctx context.Context, arg GetSCIMUserByUserNameParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUserByUserName, arg.OrgID, arg.BindingID, arg.UserNameLower)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.AccountID,
		&i.UserName,
		&i.UserNameLower,
		&i.ExternalID,
		&i.Subject,
		&i.Active,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCIMAttention = `-- name: ListSCIMAttention :many
SELECT id, org_id, binding_id, state, subject_ref, cause, entered_at
FROM scim_attention WHERE org_id = ? AND binding_id = ? ORDER BY state, subject_ref
`

type ListSCIMAttentionParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) ListSCIMAttention(ctx context.Context, arg ListSCIMAttentionParams) ([]ScimAttention, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMAttention, arg.OrgID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimAttention
	for rows.Next() {
		var i ScimAttention
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.State,
			&i.SubjectRef,
			&i.Cause,
			&i.EnteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMBindings = `-- name: ListSCIMBindings :many
SELECT id, org_id, provider_kind, provider_id, provider_slug, provider_issuer, subject_source,
       nameid_format, nameid_qualifier, nameid_qualifier_present,
       nameid_sp_qualifier, nameid_sp_qualifier_present,
       connection_principal_id, last_contact_at, created_at
FROM scim_bindings WHERE org_id = ? ORDER BY id
`

func (q *Queries) ListSCIMBindings(ctx context.Context, orgID string) ([]ScimBinding, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMBindings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimBinding
	for rows.Next() {
		var i ScimBinding
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderKind,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.ProviderIssuer,
			&i.SubjectSource,
			&i.NameidFormat,
			&i.NameidQualifier,
			&i.NameidQualifierPresent,
			&i.NameidSpQualifier,
			&i.NameidSpQualifierPresent,
			&i.ConnectionPrincipalID,
			&i.LastContactAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroupMembers = `-- name: ListSCIMGroupMembers :many
SELECT id, org_id, binding_id, group_id, user_id, created_at
FROM scim_group_members WHERE org_id = ? AND binding_id = ? AND group_id = ? ORDER BY user_id
`

type ListSCIMGroupMembersParams struct {
	OrgID     string
	BindingID string
	GroupID   string
}

func (q *Queries) ListSCIMGroupMembers(ctx context.Context, arg ListSCIMGroupMembersParams) ([]ScimGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroupMembers, arg.OrgID, arg.BindingID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroupMember
	for rows.Next() {
		var i ScimGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.GroupID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroupMembershipsForUser = `-- name: ListSCIMGroupMembershipsForUser :many
SELECT id, org_id, binding_id, group_id, user_id, created_at
FROM scim_group_members WHERE org_id = ? AND binding_id = ? AND user_id = ? ORDER BY group_id
`

type ListSCIMGroupMembershipsForUserParams struct {
	OrgID     string
	BindingID string
	UserID    string
}

// Which groups a user belongs to: the `groups` attribute is response-only per
// RFC 7643, and this is the read that fills it.
func (q *Queries) ListSCIMGroupMembershipsForUser(ctx context.Context, arg ListSCIMGroupMembershipsForUserParams) ([]ScimGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroupMembershipsForUser, arg.OrgID, arg.BindingID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroupMember
	for rows.Next() {
		var i ScimGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.GroupID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroups = `-- name: ListSCIMGroups :many
SELECT id, org_id, binding_id, display_name, display_name_lower, external_id,
       created_at, updated_at
FROM scim_groups WHERE org_id = ? AND binding_id = ? ORDER BY id
`

type ListSCIMGroupsParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) ListSCIMGroups(ctx context.Context, arg ListSCIMGroupsParams) ([]ScimGroup, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroups, arg.OrgID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.DisplayName,
			&i.DisplayNameLower,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMMappings = `-- name: ListSCIMMappings :many
SELECT id, org_id, binding_id, group_id, template, scope_project_id, scope_env_id,
       inert, created_at
FROM scim_mappings WHERE org_id = ? AND binding_id = ? ORDER BY group_id, template, id
`

type ListSCIMMappingsParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) ListSCIMMappings(ctx context.Context, arg ListSCIMMappingsParams) ([]ScimMapping, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMMappings, arg.OrgID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimMapping
	for rows.Next() {
		var i ScimMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.GroupID,
			&i.Template,
			&i.ScopeProjectID,
			&i.ScopeEnvID,
			&i.Inert,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMMappingsForGroup = `-- name: ListSCIMMappingsForGroup :many
SELECT id, org_id, binding_id, group_id, template, scope_project_id, scope_env_id,
       inert, created_at
FROM scim_mappings
WHERE org_id = ? AND binding_id = ? AND group_id = ? ORDER BY template, id
`

type ListSCIMMappingsForGroupParams struct {
	OrgID     string
	BindingID string
	GroupID   string
}

func (q *Queries) ListSCIMMappingsForGroup(ctx context.Context, arg ListSCIMMappingsForGroupParams) ([]ScimMapping, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMMappingsForGroup, arg.OrgID, arg.BindingID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimMapping
	for rows.Next() {
		var i ScimMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.GroupID,
			&i.Template,
			&i.ScopeProjectID,
			&i.ScopeEnvID,
			&i.Inert,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ? ORDER BY id
`

type ListSCIMUsersParams struct {
	OrgID     string
	BindingID string
}

func (q *Queries) ListSCIMUsers(ctx context.Context, arg ListSCIMUsersParams) ([]ScimUser, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMUsers, arg.OrgID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.AccountID,
			&i.UserName,
			&i.UserNameLower,
			&i.ExternalID,
			&i.Subject,
			&i.Active,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSCIMBinding = `-- name: LockSCIMBinding :execrows
UPDATE scim_bindings SET last_contact_at = last_contact_at
WHERE org_id = ? AND id = ?
`

type LockSCIMBindingParams struct {
	OrgID string
	ID    string
}

// Every mutation on a binding's subtree takes this lock FIRST. It is a no-op
// write, not a read: a SELECT takes no row lock, so two reconciliations for one
// binding would interleave. `last_contact_at` is deliberately untouched -- an
// administrator editing the mapping table is not the identity provider making
// contact (ADR section 9).
func (q *Queries) LockSCIMBinding(ctx context.Context, arg LockSCIMBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockSCIMBinding, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pageSCIMGroups = `-- name: PageSCIMGroups :many
SELECT id, org_id, binding_id, display_name, display_name_lower, external_id,
       created_at, updated_at
FROM scim_groups WHERE org_id = ? AND binding_id = ?
ORDER BY id LIMIT ? OFFSET ?
`

type PageSCIMGroupsParams struct {
	OrgID     string
	BindingID string
	Limit     int64
	Offset    int64
}

func (q *Queries) PageSCIMGroups(ctx context.Context, arg PageSCIMGroupsParams) ([]ScimGroup, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMGroups,
		arg.OrgID,
		arg.BindingID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.DisplayName,
			&i.DisplayNameLower,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSCIMGroupsByDisplayName = `-- name: PageSCIMGroupsByDisplayName :many
SELECT id, org_id, binding_id, display_name, display_name_lower, external_id,
       created_at, updated_at
FROM scim_groups WHERE org_id = ?1 AND binding_id = ?2 AND display_name_lower = ?3
ORDER BY id LIMIT ?5 OFFSET ?4
`

type PageSCIMGroupsByDisplayNameParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) PageSCIMGroupsByDisplayName(ctx context.Context, arg PageSCIMGroupsByDisplayNameParams) ([]ScimGroup, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMGroupsByDisplayName,
		arg.OrgID,
		arg.BindingID,
		arg.FilterValue,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.DisplayName,
			&i.DisplayNameLower,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSCIMGroupsByExternalID = `-- name: PageSCIMGroupsByExternalID :many
SELECT id, org_id, binding_id, display_name, display_name_lower, external_id,
       created_at, updated_at
FROM scim_groups WHERE org_id = ?1 AND binding_id = ?2 AND external_id = ?3
ORDER BY id LIMIT ?5 OFFSET ?4
`

type PageSCIMGroupsByExternalIDParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) PageSCIMGroupsByExternalID(ctx context.Context, arg PageSCIMGroupsByExternalIDParams) ([]ScimGroup, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMGroupsByExternalID,
		arg.OrgID,
		arg.BindingID,
		arg.FilterValue,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.DisplayName,
			&i.DisplayNameLower,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSCIMUsers = `-- name: PageSCIMUsers :many
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ? AND binding_id = ?
ORDER BY id LIMIT ? OFFSET ?
`

type PageSCIMUsersParams struct {
	OrgID     string
	BindingID string
	Limit     int64
	Offset    int64
}

func (q *Queries) PageSCIMUsers(ctx context.Context, arg PageSCIMUsersParams) ([]ScimUser, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMUsers,
		arg.OrgID,
		arg.BindingID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.AccountID,
			&i.UserName,
			&i.UserNameLower,
			&i.ExternalID,
			&i.Subject,
			&i.Active,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSCIMUsersByExternalID = `-- name: PageSCIMUsersByExternalID :many
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ?1 AND binding_id = ?2 AND external_id = ?3
ORDER BY id LIMIT ?5 OFFSET ?4
`

type PageSCIMUsersByExternalIDParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) PageSCIMUsersByExternalID(ctx context.Context, arg PageSCIMUsersByExternalIDParams) ([]ScimUser, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMUsersByExternalID,
		arg.OrgID,
		arg.BindingID,
		arg.FilterValue,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.AccountID,
			&i.UserName,
			&i.UserNameLower,
			&i.ExternalID,
			&i.Subject,
			&i.Active,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSCIMUsersByUserName = `-- name: PageSCIMUsersByUserName :many
SELECT id, org_id, binding_id, account_id, user_name, user_name_lower, external_id,
       subject, active, attributes, created_at, updated_at
FROM scim_users WHERE org_id = ?1 AND binding_id = ?2 AND user_name_lower = ?3
ORDER BY id LIMIT ?5 OFFSET ?4
`

type PageSCIMUsersByUserNameParams struct {
	OrgID       string
	BindingID   string
	FilterValue string
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) PageSCIMUsersByUserName(ctx context.Context, arg PageSCIMUsersByUserNameParams) ([]ScimUser, error) {
	rows, err := q.db.QueryContext(ctx, pageSCIMUsersByUserName,
		arg.OrgID,
		arg.BindingID,
		arg.FilterValue,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BindingID,
			&i.AccountID,
			&i.UserName,
			&i.UserNameLower,
			&i.ExternalID,
			&i.Subject,
			&i.Active,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSCIMConnectionPrincipal = `-- name: RetireSCIMConnectionPrincipal :execrows
DELETE FROM principals
WHERE principals.id = ?
  AND principals.kind = 'machine'
  AND principals.class = 'provisioning-connection'
  AND NOT EXISTS (
    SELECT 1 FROM scim_bindings AS b WHERE b.connection_principal_id = principals.id
  )
`

// Step (3) of the binding-deletion state machine. It runs AFTER the binding row
// is gone -- scim_bindings.connection_principal_id references this row, so the
// reverse order is a foreign-key violation -- which is why the scoping is
// expressed as ORPHANHOOD rather than as a join onto a row that no longer
// exists: the statement can only remove a provisioning connection that NO
// binding still owns. Combined with an id read from the caller's own
// proof-scoped binding row, a caller cannot name another org's live connection:
// a live one is referenced and therefore unmatched, and an unreferenced one is
// already ownerless. The kind and class predicates keep the statement incapable
// of touching a human principal.
func (q *Queries) RetireSCIMConnectionPrincipal(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireSCIMConnectionPrincipal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSCIMMappingInert = `-- name: SetSCIMMappingInert :execrows
UPDATE scim_mappings SET inert = ? WHERE org_id = ? AND binding_id = ? AND group_id = ?
`

type SetSCIMMappingInertParams struct {
	Inert     int64
	OrgID     string
	BindingID string
	GroupID   string
}

// A mapping row whose group was deleted flips to inert (ADR section 5.4) and
// raises an attention state; the human edits or deletes it. It is never
// silently removed.
func (q *Queries) SetSCIMMappingInert(ctx context.Context, arg SetSCIMMappingInertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSCIMMappingInert,
		arg.Inert,
		arg.OrgID,
		arg.BindingID,
		arg.GroupID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSCIMBinding = `-- name: TouchSCIMBinding :execrows
UPDATE scim_bindings SET last_contact_at = ? WHERE org_id = ? AND id = ?
`

type TouchSCIMBindingParams struct {
	LastContactAt sql.NullString
	OrgID         string
	ID            string
}

// Push-only staleness bookkeeping (ADR section 9): the binding records
// last-contact, and the surface reports it. Nothing self-heals from it.
func (q *Queries) TouchSCIMBinding(ctx context.Context, arg TouchSCIMBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchSCIMBinding, arg.LastContactAt, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSCIMGroup = `-- name: UpdateSCIMGroup :execrows
UPDATE scim_groups
SET display_name = ?, display_name_lower = ?, external_id = ?, updated_at = ?
WHERE org_id = ? AND binding_id = ? AND id = ?
`

type UpdateSCIMGroupParams struct {
	DisplayName      string
	DisplayNameLower string
	ExternalID       string
	UpdatedAt        string
	OrgID            string
	BindingID        string
	ID               string
}

func (q *Queries) UpdateSCIMGroup(ctx context.Context, arg UpdateSCIMGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSCIMGroup,
		arg.DisplayName,
		arg.DisplayNameLower,
		arg.ExternalID,
		arg.UpdatedAt,
		arg.OrgID,
		arg.BindingID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSCIMMappingTemplate = `-- name: UpdateSCIMMappingTemplate :execrows
UPDATE scim_mappings SET template = ?
WHERE org_id = ? AND id = ?
`

type UpdateSCIMMappingTemplateParams struct {
	Template string
	OrgID    string
	ID       string
}

// Narrowing a mapping row keeps its ID: origins key on it, so a delete-and-
// recreate would release every origin the row holds and immediately recreate
// most of them -- momentarily revoking capabilities that never stopped being
// granted, and logging the holders out for a bookkeeping change.
func (q *Queries) UpdateSCIMMappingTemplate(ctx context.Context, arg UpdateSCIMMappingTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSCIMMappingTemplate, arg.Template, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSCIMUser = `-- name: UpdateSCIMUser :execrows
UPDATE scim_users
SET user_name = ?, user_name_lower = ?, external_id = ?, active = ?,
    attributes = ?, updated_at = ?
WHERE org_id = ? AND binding_id = ? AND id = ?
`

type UpdateSCIMUserParams struct {
	UserName      string
	UserNameLower string
	ExternalID    string
	Active        int64
	Attributes    string
	UpdatedAt     string
	OrgID         string
	BindingID     string
	ID            string
}

func (q *Queries) UpdateSCIMUser(ctx context.Context, arg UpdateSCIMUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSCIMUser,
		arg.UserName,
		arg.UserNameLower,
		arg.ExternalID,
		arg.Active,
		arg.Attributes,
		arg.UpdatedAt,
		arg.OrgID,
		arg.BindingID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
